/**
 * Purchase domain service layer.
 * Dual-mode: PR + Planning Sheet use backend when `VITE_USE_API=true`.
 * Domain models: `@/types/purchaseDomain`
 * Operational Zustand docs remain in `@/types/purchase` until migration.
 */
export type * from '../../types/purchaseDomain'
export type * from './purchaseApiTypes'
export type { PlanningSheetSummary } from './purchaseApiFacade'
export type { PurchaseOrderSeriesOption } from './purchaseService'

export {
  PURCHASE_REQUISITION_STATUSES,
  PURCHASE_REQUISITION_STATUS_LABELS,
  PURCHASE_REQUISITION_SOURCE_LABELS,
  PURCHASE_REQUISITION_PRIORITY_LABELS,
  PURCHASE_REQUISITION_APPROVAL_STATUS_LABELS,
  PURCHASE_REQUISITION_TYPE_LABELS,
  PURCHASE_LINE_ITEM_TYPE_LABELS,
  PURCHASE_REQUISITION_ATTACHMENT_KIND_LABELS,
  PURCHASE_PLANNING_PRIORITIES,
  PURCHASE_PLANNING_PRIORITY_LABELS,
  PURCHASE_PLANNING_PURCHASE_TYPES,
  PURCHASE_PLANNING_PURCHASE_TYPE_LABELS,
  PURCHASE_PLANNING_STATUSES,
  PURCHASE_PLANNING_STATUS_LABELS,
  PURCHASE_APPROVAL_STATUS_LABELS,
  PURCHASE_APPROVAL_ROLE_LABELS,
  PURCHASE_APPROVAL_ROLES,
  PURCHASE_APPROVAL_QUEUE_TAB_LABELS,
  PURCHASE_APPROVAL_DOCUMENT_TYPE_LABELS,
  PURCHASE_APPROVAL_AGEING_LABELS,
  PURCHASE_SETUP_TAB_LABELS,
  PURCHASE_ITEM_CATEGORY_LABELS,
  PURCHASE_ITEM_CATEGORIES,
  RFQ_DOMAIN_STATUSES,
  RFQ_DOMAIN_STATUS_LABELS,
  RFQ_VENDOR_INVITE_STATUS_LABELS,
  PURCHASE_ORDER_DOMAIN_STATUSES,
  PURCHASE_ORDER_DOMAIN_STATUS_LABELS,
  PURCHASE_ORDER_ORIGIN_LABELS,
  PURCHASE_ORDER_TYPE_LABELS,
  PURCHASE_ORDER_APPROVAL_STATUS_LABELS,
  PURCHASE_ORDER_INVOICE_STATUS_LABELS,
  PURCHASE_ORDER_LINE_STATUS_LABELS,
  PURCHASE_ORDER_LINE_ITEM_TYPE_LABELS,
  GRN_DOMAIN_STATUSES,
  GRN_DOMAIN_STATUS_LABELS,
  GRN_LINE_INSPECTION_STATUS_LABELS,
  QUALITY_INSPECTION_STATUSES,
  QUALITY_INSPECTION_STATUS_LABELS,
  QUALITY_INSPECTION_RESULT_LABELS,
  PURCHASE_INVOICE_STATUSES,
  PURCHASE_INVOICE_STATUS_LABELS,
  PURCHASE_INVOICE_ORIGIN_LABELS,
  INVOICE_MATCHING_RESULT_STATUS_LABELS,
  PURCHASE_RETURN_DOMAIN_STATUSES,
  PURCHASE_RETURN_DOMAIN_STATUS_LABELS,
  PURCHASE_RETURN_ORIGIN_LABELS,
  PURCHASE_RETURN_REASON_LABELS,
  VENDOR_QUOTATION_DOMAIN_STATUS_LABELS,
  QUOTATION_COMPARISON_METHOD_LABELS,
  QUOTATION_COMPARISON_CRITERION_LABELS,
  QUOTATION_COMPLIANCE_STATUS_LABELS,
} from '../../types/purchaseDomain'

/** Dual-mode (API when `VITE_USE_API=true`) — PR + Planning + RFQ flow */
export {
  getPurchaseRequisitions,
  getPurchaseRequisitionListSummary,
  getPurchaseRequisitionById,
  previewNextPurchaseRequisitionNumber,
  createPurchaseRequisition,
  updatePurchaseRequisition,
  submitPurchaseRequisition,
  approvePurchaseRequisition,
  rejectPurchaseRequisition,
  cancelPurchaseRequisition,
  deletePurchaseRequisition,
  duplicatePurchaseRequisition,
  convertPurchaseRequisitionToRfq,
  convertPurchaseRequisitionToPo,
  getPurchasePlanningSheet,
  getPurchasePlanningSheetById,
  getPurchasePlanningSheetSummary,
  updatePurchasePlanningSheetRow,
  assignPurchasePlanningBuyer,
  selectPurchasePlanningVendor,
  approvePurchasePlanningRow,
  holdPurchasePlanningRow,
  cancelPurchasePlanningRow,
  bulkAssignPurchasePlanningBuyer,
  bulkSelectPurchasePlanningVendor,
  bulkUpdatePurchasePlanningStatus,
  recalculatePurchasePlanningRows,
  canCreatePoFromPlanningRow,
  canSelectPlanningRowForPo,
  getPurchaseOrderSeriesOptions,
  createPurchaseOrderFromPlanningRow,
  createPurchaseOrdersFromPlanningSelection,
  getRFQs,
  getRFQById,
  getRfqList,
  createRFQ,
  updateRFQ,
  sendRFQ,
  cancelRFQ,
  getVendorQuotationList,
  getVendorQuotations,
  getVendorQuotationById,
  createVendorQuotation,
  updateVendorQuotation,
  submitVendorQuotation,
  getQuotationComparison,
  buildQuotationComparison,
  updateQuotationComparisonSelection,
  recommendQuotationVendor,
  approveQuotationRecommendation,
  createPurchaseOrderFromComparison,
  createPurchaseOrderFromPr,
  getPurchaseItems,
  getVendors,
  getPurchaseWarehouses,
  getPurchaseDashboard,
  getRecommendedVendorsForItems,
  getPurchaseOrders,
  getPurchaseOrderById,
  getPurchaseOrderList,
  getPurchaseOrderLinkedDocuments,
} from './purchaseApiFacade'

export {
  PurchaseServiceError,
  resetPurchaseMockData,
  getBlanketOrders,
  getBlanketOrderById,
  createPurchaseOrder,
  updatePurchaseOrder,
  submitPurchaseOrder,
  approvePurchaseOrder,
  releasePurchaseOrder,
  reopenPurchaseOrder,
  sendPurchaseOrderToVendor,
  closePurchaseOrder,
  cancelPurchaseOrder,
  revisePurchaseOrder,
  createPurchaseOrderFromVendorQuotation,
  createPurchaseOrderFromBlanket,
  createGRN,
  createGRNFromPo,
  getGRNs,
  getGrnList,
  getGRNById,
  updateGRN,
  submitGRN,
  postGRN,
  createQualityInspection,
  getQualityInspections,
  getQualityInspectionList,
  getQualityInspectionById,
  updateQualityInspection,
  acceptQualityInspection,
  rejectQualityInspection,
  holdQualityInspection,
  requestDeviationApproval,
  createPurchaseInvoice,
  createPurchaseInvoiceFromPo,
  createPurchaseInvoiceFromGrn,
  createPurchaseInvoiceFromServicePo,
  createDirectPurchaseInvoice,
  updatePurchaseInvoice,
  getPurchaseInvoices,
  getPurchaseInvoiceList,
  getPurchaseInvoiceById,
  computeInvoiceMatching,
  verifyPurchaseInvoice,
  submitPurchaseInvoiceForApproval,
  approvePurchaseInvoice,
  rejectPurchaseInvoice,
  holdPurchaseInvoice,
  approveInvoiceMatchingException,
  postPurchaseInvoice,
  createDebitNoteFromInvoice,
  createPurchaseReturn,
  updatePurchaseReturn,
  getPurchaseReturns,
  getPurchaseReturnList,
  getPurchaseReturnById,
  createPurchaseReturnFromGrn,
  createPurchaseReturnFromQualityInspection,
  createPurchaseReturnFromReason,
  submitPurchaseReturn,
  approvePurchaseReturn,
  postPurchaseReturn,
  cancelPurchaseReturn,
  createDebitNoteFromReturn,
  createReplacementPoFromReturn,
  getApprovals,
  getApprovalHistory,
  getAttachments,
  getPurchaseSetup,
  updatePurchaseSetup,
  emptyMoney,
} from './purchaseService'

export {
  getPurchaseApprovalQueue,
  getPurchaseApprovalReview,
  approvePurchaseDocument,
  rejectPurchaseDocument,
  sendBackPurchaseDocument,
  delegatePurchaseApproval,
} from './purchaseApiFacade'

export {
  getPurchaseReportCatalog,
  getPurchaseReportEntry,
  getPurchaseReportFilterOptions,
  isPurchaseReportId,
  runPurchaseReport,
} from './purchaseReportsService'
