/** Seed data for CRM masters — mirrors frontend crmMastersSeed.ts essentials */
export const CRM_MASTER_SEED_ROWS = [
    { kind: 'lead-sources', code: 'website', name: 'Website', sortOrder: 1, attributes: { sourceType: 'Digital' } },
    { kind: 'lead-sources', code: 'referral', name: 'Referral', sortOrder: 2, attributes: { sourceType: 'Relationship' } },
    { kind: 'lead-sources', code: 'cold_call', name: 'Cold Calling', sortOrder: 3, attributes: { sourceType: 'Outbound' } },
    { kind: 'lead-sources', code: 'trade_show', name: 'Trade Show', sortOrder: 4, attributes: { sourceType: 'Event' } },
    { kind: 'lead-sources', code: 'existing_customer', name: 'Existing Customer', sortOrder: 5, attributes: { sourceType: 'Account' } },
    { kind: 'lead-sources', code: 'indiamart', name: 'IndiaMART', sortOrder: 6, attributes: { sourceType: 'Digital' } },
    { kind: 'lead-sources', code: 'other', name: 'Other', sortOrder: 99, attributes: { sourceType: 'Other' } },
    { kind: 'industries', code: 'cement', name: 'Cement', sortOrder: 1, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'logistics', name: 'Logistics', sortOrder: 2, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'chemical', name: 'Chemical', sortOrder: 3, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'construction', name: 'Construction', sortOrder: 4, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'mining', name: 'Mining', sortOrder: 5, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'agro', name: 'Agro', sortOrder: 6, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'oil_gas', name: 'Oil and Gas', sortOrder: 7, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'transport_fleet', name: 'Transport Fleet', sortOrder: 8, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'infrastructure', name: 'Infrastructure', sortOrder: 9, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'container_transport', name: 'Container Transport', sortOrder: 10, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'manufacturing', name: 'Manufacturing', sortOrder: 11, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'steel', name: 'Steel & Metals', sortOrder: 12, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'automotive_oem', name: 'Automotive OEM', sortOrder: 13, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'fertilizer', name: 'Fertilizer & Agrochemicals', sortOrder: 14, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'power', name: 'Power & Energy', sortOrder: 15, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'ports', name: 'Ports & Maritime', sortOrder: 16, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'railways', name: 'Railways & Metro', sortOrder: 17, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'defence', name: 'Defence & Aerospace', sortOrder: 18, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'food_beverage', name: 'Food & Beverage', sortOrder: 19, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'pharma', name: 'Pharmaceuticals', sortOrder: 20, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'paper', name: 'Paper & Pulp', sortOrder: 21, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'textiles', name: 'Textiles', sortOrder: 22, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'plastic', name: 'Plastics & Polymers', sortOrder: 23, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'waste_mgmt', name: 'Waste Management', sortOrder: 24, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'renewable', name: 'Renewable Energy', sortOrder: 25, attributes: { category: 'Manufacturing', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'fmcg', name: 'FMCG', sortOrder: 26, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'government_psu', name: 'Government / PSU', sortOrder: 27, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'industries', code: 'other', name: 'Other', sortOrder: 99, attributes: { category: 'Core', defaultSalesProcess: 'B2B Enterprise' } },
    { kind: 'designations', code: 'purchase_head', name: 'Purchase Head', sortOrder: 1 },
    { kind: 'designations', code: 'purchase_manager', name: 'Purchase Manager', sortOrder: 2 },
    { kind: 'designations', code: 'plant_manager', name: 'Plant Manager', sortOrder: 3 },
    { kind: 'designations', code: 'project_manager', name: 'Project Manager', sortOrder: 4 },
    { kind: 'designations', code: 'operations_manager', name: 'Operations Manager', sortOrder: 5 },
    { kind: 'designations', code: 'fleet_manager', name: 'Fleet Manager', sortOrder: 6 },
    { kind: 'designations', code: 'logistics_manager', name: 'Logistics Manager', sortOrder: 7 },
    { kind: 'designations', code: 'stores_manager', name: 'Stores Manager', sortOrder: 8 },
    { kind: 'designations', code: 'quality_manager', name: 'Quality Manager', sortOrder: 9 },
    { kind: 'designations', code: 'finance_manager', name: 'Finance Manager', sortOrder: 10 },
    { kind: 'designations', code: 'sales_manager', name: 'Sales Manager', sortOrder: 11 },
    { kind: 'designations', code: 'director', name: 'Director', sortOrder: 12 },
    { kind: 'designations', code: 'owner', name: 'Owner / Proprietor', sortOrder: 13 },
    { kind: 'designations', code: 'other', name: 'Other', sortOrder: 99 },
    { kind: 'departments', code: 'procurement', name: 'Procurement', sortOrder: 1 },
    { kind: 'departments', code: 'purchase', name: 'Purchase', sortOrder: 2 },
    { kind: 'departments', code: 'operations', name: 'Operations', sortOrder: 3 },
    { kind: 'departments', code: 'production', name: 'Production', sortOrder: 4 },
    { kind: 'departments', code: 'fabrication', name: 'Fabrication', sortOrder: 5 },
    { kind: 'departments', code: 'assembly', name: 'Assembly', sortOrder: 6 },
    { kind: 'departments', code: 'finishing', name: 'Finishing', sortOrder: 7 },
    { kind: 'departments', code: 'quality', name: 'Quality', sortOrder: 8 },
    { kind: 'departments', code: 'stores', name: 'Stores / Inventory', sortOrder: 9 },
    { kind: 'departments', code: 'logistics', name: 'Logistics', sortOrder: 10 },
    { kind: 'departments', code: 'fleet', name: 'Fleet', sortOrder: 11 },
    { kind: 'departments', code: 'engineering', name: 'Engineering', sortOrder: 12 },
    { kind: 'departments', code: 'sales', name: 'Sales', sortOrder: 13 },
    { kind: 'departments', code: 'finance', name: 'Finance', sortOrder: 14 },
    { kind: 'departments', code: 'accounts', name: 'Accounts', sortOrder: 15 },
    { kind: 'departments', code: 'management', name: 'Management', sortOrder: 16 },
    { kind: 'departments', code: 'other', name: 'Other', sortOrder: 99 },
    { kind: 'territories', code: 'gujarat', name: 'Gujarat', sortOrder: 1, attributes: { region: 'West', state: 'Gujarat' } },
    { kind: 'territories', code: 'maharashtra', name: 'Maharashtra', sortOrder: 2, attributes: { region: 'West', state: 'Maharashtra' } },
    { kind: 'lead-stages', code: 'new', name: 'New', sortOrder: 1, attributes: { stageType: 'open' }, isSystem: true },
    { kind: 'lead-stages', code: 'contacted', name: 'Contacted', sortOrder: 2, attributes: { stageType: 'open' } },
    { kind: 'lead-stages', code: 'requirement_collected', name: 'Requirement Collected', sortOrder: 3, attributes: { stageType: 'open' } },
    { kind: 'lead-stages', code: 'qualified', name: 'Qualified', sortOrder: 4, attributes: { stageType: 'qualified' } },
    { kind: 'lead-stages', code: 'not_qualified', name: 'Not Qualified', sortOrder: 5, attributes: { stageType: 'closed' } },
    { kind: 'lead-stages', code: 'converted_to_opportunity', name: 'Converted to Opportunity', sortOrder: 6, isSystem: true },
    { kind: 'lead-stages', code: 'closed', name: 'Closed', sortOrder: 7, attributes: { stageType: 'closed' } },
    { kind: 'lead-priorities', code: 'low', name: 'Low', sortOrder: 1 },
    { kind: 'lead-priorities', code: 'medium', name: 'Medium', sortOrder: 2 },
    { kind: 'lead-priorities', code: 'high', name: 'High', sortOrder: 3 },
    { kind: 'lead-priorities', code: 'critical', name: 'Critical', sortOrder: 4 },
    { kind: 'opportunity-priorities', code: 'low', name: 'Low', sortOrder: 1, attributes: { valueThreshold: 0, color: '#8A94A6', isDefault: false } },
    { kind: 'opportunity-priorities', code: 'normal', name: 'Normal', sortOrder: 2, attributes: { valueThreshold: 0, color: '#8A94A6', isDefault: true } },
    { kind: 'opportunity-priorities', code: 'medium', name: 'Medium', sortOrder: 3, attributes: { valueThreshold: 2500000, color: '#0078D4' } },
    { kind: 'opportunity-priorities', code: 'high', name: 'High', sortOrder: 4, attributes: { valueThreshold: 5000000, color: '#CA5010' } },
    { kind: 'opportunity-priorities', code: 'strategic', name: 'Strategic', sortOrder: 5, attributes: { valueThreshold: 15000000, color: '#8764B8' } },
    { kind: 'opportunity-priorities', code: 'critical', name: 'Critical', sortOrder: 6, attributes: { valueThreshold: 30000000, color: '#D13438' } },
    { kind: 'lost-reasons', code: 'price_high', name: 'Price High', sortOrder: 1, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'competitor_selected', name: 'Competitor Selected', sortOrder: 2, attributes: { category: 'Competitive', closePipeline: true } },
    { kind: 'lost-reasons', code: 'delivery_timeline', name: 'Delivery Timeline Issue', sortOrder: 3, attributes: { category: 'Operations', closePipeline: true } },
    { kind: 'lost-reasons', code: 'payment_terms', name: 'Payment Terms Issue', sortOrder: 4, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'technical_mismatch', name: 'Technical Mismatch', sortOrder: 5, attributes: { category: 'Technical', closePipeline: true } },
    { kind: 'lost-reasons', code: 'no_response', name: 'No Response', sortOrder: 6, attributes: { category: 'Engagement', closePipeline: true } },
    { kind: 'lost-reasons', code: 'budget_hold', name: 'Budget Hold', sortOrder: 7, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'requirement_changed', name: 'Requirement Changed', sortOrder: 8, attributes: { category: 'Technical', closePipeline: true } },
    { kind: 'lost-reasons', code: 'relationship_issue', name: 'Relationship Issue', sortOrder: 9, attributes: { category: 'Relationship', closePipeline: true } },
    { kind: 'lost-reasons', code: 'spec_mismatch', name: 'Specification Mismatch', sortOrder: 10, attributes: { category: 'Technical', closePipeline: true } },
    { kind: 'lost-reasons', code: 'warranty_terms', name: 'Warranty Terms Unacceptable', sortOrder: 11, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'after_sales', name: 'After-Sales Concern', sortOrder: 12, attributes: { category: 'Service', closePipeline: true } },
    { kind: 'lost-reasons', code: 'incumbent_vendor', name: 'Incumbent Vendor Retained', sortOrder: 13, attributes: { category: 'Competitive', closePipeline: true } },
    { kind: 'lost-reasons', code: 'tender_cancelled', name: 'Tender Cancelled', sortOrder: 14, attributes: { category: 'Engagement', closePipeline: true } },
    { kind: 'lost-reasons', code: 'project_delayed', name: 'Project Delayed', sortOrder: 15, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'management_change', name: 'Management Change', sortOrder: 16, attributes: { category: 'Relationship', closePipeline: true } },
    { kind: 'lost-reasons', code: 'credit_limit', name: 'Credit Limit Issue', sortOrder: 17, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'gst_compliance', name: 'GST / Compliance Issue', sortOrder: 18, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'freight_cost', name: 'Freight Cost Too High', sortOrder: 19, attributes: { category: 'Operations', closePipeline: true } },
    { kind: 'lost-reasons', code: 'lead_time', name: 'Lead Time Too Long', sortOrder: 20, attributes: { category: 'Operations', closePipeline: true } },
    { kind: 'lost-reasons', code: 'quality_concern', name: 'Quality Concern Raised', sortOrder: 21, attributes: { category: 'Technical', closePipeline: true } },
    { kind: 'lost-reasons', code: 'reference_failed', name: 'Reference Check Failed', sortOrder: 22, attributes: { category: 'Relationship', closePipeline: true } },
    { kind: 'lost-reasons', code: 'demo_unsatisfactory', name: 'Demo Unsatisfactory', sortOrder: 23, attributes: { category: 'Technical', closePipeline: true } },
    { kind: 'lost-reasons', code: 'financing_issue', name: 'Customer Financing Issue', sortOrder: 24, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'scope_reduction', name: 'Scope Reduction', sortOrder: 25, attributes: { category: 'Technical', closePipeline: true } },
    { kind: 'lost-reasons', code: 'vendor_consolidation', name: 'Vendor Consolidation', sortOrder: 26, attributes: { category: 'Competitive', closePipeline: true } },
    { kind: 'lost-reasons', code: 'price_match_failed', name: 'Could Not Match Price', sortOrder: 27, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'regulatory_block', name: 'Regulatory Block', sortOrder: 28, attributes: { category: 'Commercial', closePipeline: true } },
    { kind: 'lost-reasons', code: 'internal_priority_shift', name: 'Internal Priority Shift', sortOrder: 29, attributes: { category: 'Engagement', closePipeline: true } },
    { kind: 'lost-reasons', code: 'competitor_bundle', name: 'Competitor Bundle Offer', sortOrder: 30, attributes: { category: 'Competitive', closePipeline: true } },
    { kind: 'lost-reasons', code: 'other', name: 'Other', sortOrder: 99, attributes: { category: 'Other', closePipeline: true } },
    { kind: 'activity-types', code: 'call', name: 'Call', sortOrder: 1, attributes: { useInActivity: true } },
    { kind: 'activity-types', code: 'meeting', name: 'Meeting', sortOrder: 2, attributes: { useInActivity: true } },
    { kind: 'activity-types', code: 'email', name: 'Email', sortOrder: 3, attributes: { useInActivity: true } },
    { kind: 'activity-types', code: 'note', name: 'Note', sortOrder: 4, attributes: { useInActivity: true } },
    { kind: 'document-types', code: 'general', name: 'General Document', sortOrder: 1, attributes: { requiredFor: 'Any', fileTypes: 'pdf,jpg,png,doc,docx', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'customer_po', name: 'Customer PO', sortOrder: 2, attributes: { requiredFor: 'Sales Order', fileTypes: 'pdf,jpg,png', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'customer_requirement', name: 'Customer Requirement', sortOrder: 3, attributes: { requiredFor: 'Quotation', fileTypes: 'pdf,doc,docx', maxSizeMb: 15 } },
    { kind: 'document-types', code: 'drawing', name: 'Drawing', sortOrder: 4, attributes: { requiredFor: 'Quotation', fileTypes: 'pdf,dwg', maxSizeMb: 25 } },
    { kind: 'document-types', code: 'technical_spec', name: 'Technical Specification', sortOrder: 5, attributes: { requiredFor: 'Quotation', fileTypes: 'pdf,doc,docx', maxSizeMb: 15 } },
    { kind: 'document-types', code: 'quotation_pdf', name: 'Quotation PDF', sortOrder: 6, attributes: { requiredFor: 'Quotation', fileTypes: 'pdf', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'approval_note', name: 'Approval Note', sortOrder: 7, attributes: { requiredFor: 'Quotation Approval', fileTypes: 'pdf', maxSizeMb: 5 } },
    { kind: 'document-types', code: 'email_copy', name: 'Email Copy', sortOrder: 8, attributes: { requiredFor: 'Communication', fileTypes: 'pdf,eml', maxSizeMb: 5 } },
    { kind: 'document-types', code: 'signed_quotation', name: 'Signed Quotation', sortOrder: 9, attributes: { requiredFor: 'Sales Order', fileTypes: 'pdf,jpg,png', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'tender_document', name: 'Tender Document', sortOrder: 10, attributes: { requiredFor: 'Opportunity', fileTypes: 'pdf,zip', maxSizeMb: 50 } },
    { kind: 'document-types', code: 'customer_communication', name: 'Customer Communication', sortOrder: 11, attributes: { requiredFor: 'Lead', fileTypes: 'pdf,eml,jpg', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'gst_certificate', name: 'GST Certificate', sortOrder: 12, attributes: { requiredFor: 'Company', fileTypes: 'pdf,jpg,png', maxSizeMb: 5 } },
    { kind: 'document-types', code: 'pan_card', name: 'PAN Card', sortOrder: 13, attributes: { requiredFor: 'Company', fileTypes: 'pdf,jpg,png', maxSizeMb: 5 } },
    { kind: 'document-types', code: 'company_profile', name: 'Company Profile', sortOrder: 14, attributes: { requiredFor: 'Lead', fileTypes: 'pdf,ppt,pptx', maxSizeMb: 20 } },
    { kind: 'document-types', code: 'site_photo', name: 'Site Photo', sortOrder: 15, attributes: { requiredFor: 'Opportunity', fileTypes: 'jpg,png,jpeg', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'inspection_report', name: 'Inspection Report', sortOrder: 16, attributes: { requiredFor: 'Sales Order', fileTypes: 'pdf', maxSizeMb: 15 } },
    { kind: 'document-types', code: 'delivery_challan', name: 'Delivery Challan', sortOrder: 17, attributes: { requiredFor: 'Dispatch', fileTypes: 'pdf,jpg,png', maxSizeMb: 10 } },
    { kind: 'document-types', code: 'invoice_copy', name: 'Invoice Copy', sortOrder: 18, attributes: { requiredFor: 'Finance', fileTypes: 'pdf', maxSizeMb: 10 } },
    // Commercial term categories (section types on quotation / SO)
    { kind: 'commercial-terms', code: 'payment', name: 'Payment Terms', sortOrder: 1, attributes: { termType: 'Payment', appliesTo: 'quotation', approvalRequired: true } },
    { kind: 'commercial-terms', code: 'delivery', name: 'Delivery Terms', sortOrder: 2, attributes: { termType: 'Delivery', appliesTo: 'quotation', approvalRequired: true } },
    { kind: 'commercial-terms', code: 'warranty', name: 'Warranty Terms', sortOrder: 3, attributes: { termType: 'Warranty', appliesTo: 'quotation', approvalRequired: true } },
    { kind: 'commercial-terms', code: 'validity', name: 'Quotation Validity', sortOrder: 4, attributes: { termType: 'Validity', appliesTo: 'quotation', approvalRequired: false } },
    { kind: 'commercial-terms', code: 'jurisdiction', name: 'Jurisdiction', sortOrder: 5, attributes: { termType: 'Jurisdiction', appliesTo: 'quotation,sales_order', approvalRequired: false } },
    { kind: 'commercial-terms', code: 'exclusions', name: 'Exclusions', sortOrder: 6, attributes: { termType: 'Exclusions', appliesTo: 'quotation,sales_order', approvalRequired: false } },
    { kind: 'commercial-terms', code: 'maintenance', name: 'Maintenance', sortOrder: 7, attributes: { termType: 'Maintenance', appliesTo: 'sales_order', approvalRequired: true } },
    { kind: 'commercial-terms', code: 'change_conditions', name: 'Change Conditions', sortOrder: 8, attributes: { termType: 'Change Conditions', appliesTo: 'quotation,sales_order', approvalRequired: true } },
    { kind: 'commercial-terms', code: 'packing', name: 'Packing & Forwarding', sortOrder: 9, attributes: { termType: 'Packing', appliesTo: 'quotation,sales_order', approvalRequired: false } },
    { kind: 'commercial-terms', code: 'insurance', name: 'Insurance', sortOrder: 10, attributes: { termType: 'Insurance', appliesTo: 'quotation,sales_order', approvalRequired: false } },
    { kind: 'commercial-terms', code: 'penalty', name: 'Penalty / LD Clause', sortOrder: 11, attributes: { termType: 'Penalty', appliesTo: 'sales_order', approvalRequired: true } },
    { kind: 'commercial-terms', code: 'force_majeure', name: 'Force Majeure', sortOrder: 12, attributes: { termType: 'Legal', appliesTo: 'quotation,sales_order', approvalRequired: false } },
    // Payment terms — trailer manufacturing commercial standards
    { kind: 'payment-terms', code: '100_advance', name: '100% Advance', sortOrder: 1, attributes: { advancePct: 100, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: '30_pi', name: '30% Advance, Balance Against PI', sortOrder: 2, attributes: { advancePct: 30, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: '50_50', name: '50% Advance, 50% Before Dispatch', sortOrder: 3, attributes: { advancePct: 50, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: 'credit_30', name: 'Credit 30 Days', sortOrder: 4, attributes: { advancePct: 0, creditDays: 30, approvalRequired: true } },
    { kind: 'payment-terms', code: 'milestone', name: 'Milestone Payment', sortOrder: 5, attributes: { advancePct: 25, creditDays: 0, approvalRequired: true } },
    { kind: 'payment-terms', code: 'adv_20', name: '20% Advance, Balance Before Dispatch', sortOrder: 6, attributes: { advancePct: 20, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: 'adv_40', name: '40% Advance, 60% Before Dispatch', sortOrder: 7, attributes: { advancePct: 40, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: 'credit_45', name: 'Credit 45 Days', sortOrder: 8, attributes: { advancePct: 0, creditDays: 45, approvalRequired: true } },
    { kind: 'payment-terms', code: 'credit_60', name: 'Credit 60 Days', sortOrder: 9, attributes: { advancePct: 0, creditDays: 60, approvalRequired: true } },
    { kind: 'payment-terms', code: 'credit_90', name: 'Credit 90 Days', sortOrder: 10, attributes: { advancePct: 0, creditDays: 90, approvalRequired: true } },
    { kind: 'payment-terms', code: 'lc_sight', name: 'LC at Sight', sortOrder: 11, attributes: { advancePct: 0, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: 'lc_30', name: 'LC 30 Days', sortOrder: 12, attributes: { advancePct: 0, creditDays: 30, approvalRequired: false } },
    { kind: 'payment-terms', code: 'against_delivery', name: 'Payment Against Delivery', sortOrder: 13, attributes: { advancePct: 0, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: 'against_proforma', name: 'Against Proforma Invoice', sortOrder: 14, attributes: { advancePct: 30, creditDays: 0, approvalRequired: false } },
    { kind: 'payment-terms', code: 'retention_10', name: '10% Retention for 12 Months', sortOrder: 15, attributes: { advancePct: 90, creditDays: 0, approvalRequired: true } },
];
//# sourceMappingURL=crmMasterSeedData.js.map