import type { RouteObject } from 'react-router-dom'
import {
  ReportsIndexPage,
  StockAgingReportPage,
  NegativeStockReportPage,
  SlowMovingReportPage,
  OpenPoReportPage,
  DelayedPoReportPage,
  WoStatusReportPage,
  WipAgingReportPage,
  NcrAgingReportPage,
  ReworkTrendReportPage,
  PendingDispatchReportPage,
  PodPendingReportPage,
  OpenOrdersReportPage,
  DeliveryCommitmentsReportPage,
  ProductRevisionReportPage,
  ObsoleteProductReportPage,
  ProductCostReportPage,
  ProductUsageReportPage,
  EngineeringChangeReportPage,
} from '@/modules/reports/ReportsPages'
import { CrmReportsIndexPage, CrmReportPage } from '@/modules/reports/CrmReportsPages'
import { BarcodeTraceReportAliasPage } from '@/modules/barcode'

export const reportsRouteChildren: RouteObject[] = [
  { path: 'reports', element: <ReportsIndexPage /> },
  { path: 'reports/inventory/stock-aging', element: <StockAgingReportPage /> },
  { path: 'reports/inventory/negative-stock', element: <NegativeStockReportPage /> },
  { path: 'reports/inventory/slow-moving', element: <SlowMovingReportPage /> },
  { path: 'reports/purchase/open-po', element: <OpenPoReportPage /> },
  { path: 'reports/purchase/delayed-po', element: <DelayedPoReportPage /> },
  { path: 'reports/production/wo-status', element: <WoStatusReportPage /> },
  { path: 'reports/production/wip-aging', element: <WipAgingReportPage /> },
  { path: 'reports/quality/ncr-aging', element: <NcrAgingReportPage /> },
  { path: 'reports/quality/rework-trend', element: <ReworkTrendReportPage /> },
  { path: 'reports/dispatch/pending-dispatch', element: <PendingDispatchReportPage /> },
  { path: 'reports/dispatch/pod-pending', element: <PodPendingReportPage /> },
  { path: 'reports/sales/open-orders', element: <OpenOrdersReportPage /> },
  { path: 'reports/sales/delivery-commitments', element: <DeliveryCommitmentsReportPage /> },
  { path: 'reports/products/revision', element: <ProductRevisionReportPage /> },
  { path: 'reports/products/obsolete', element: <ObsoleteProductReportPage /> },
  { path: 'reports/products/cost', element: <ProductCostReportPage /> },
  { path: 'reports/products/usage', element: <ProductUsageReportPage /> },
  { path: 'reports/products/engineering-change', element: <EngineeringChangeReportPage /> },
  { path: 'reports/crm', element: <CrmReportsIndexPage /> },
  { path: 'reports/crm/:reportId', element: <CrmReportPage /> },
  { path: 'reports/traceability/barcode', element: <BarcodeTraceReportAliasPage /> },
]
