import { AppError } from '../../../utils/errors.js'

export type JournalPostingErrorCode =
  | 'JOURNAL_NOT_APPROVED'
  | 'JOURNAL_ALREADY_POSTED'
  | 'JOURNAL_POSTING_NOT_ALLOWED'
  | 'JOURNAL_APPROVAL_INCOMPLETE'
  | 'JOURNAL_NUMBER_ALREADY_ASSIGNED'
  | 'JOURNAL_LINES_MISSING'
  | 'JOURNAL_CHANGED_AFTER_APPROVAL'
  | 'JOURNAL_POSTING_IN_PROGRESS'
  | 'JOURNAL_POSTING_FAILED'
  | 'POSTING_PERIOD_NO_LONGER_OPEN'
  | 'POSTING_CONCURRENT_ACTION'
  | 'IDEMPOTENCY_PAYLOAD_MISMATCH'
  | 'POSTING_EVENT_IN_PROGRESS'

const STATUS_BY_CODE: Record<JournalPostingErrorCode, number> = {
  JOURNAL_NOT_APPROVED: 422,
  JOURNAL_ALREADY_POSTED: 422,
  JOURNAL_POSTING_NOT_ALLOWED: 403,
  JOURNAL_APPROVAL_INCOMPLETE: 422,
  JOURNAL_NUMBER_ALREADY_ASSIGNED: 422,
  JOURNAL_LINES_MISSING: 400,
  JOURNAL_CHANGED_AFTER_APPROVAL: 409,
  JOURNAL_POSTING_IN_PROGRESS: 409,
  JOURNAL_POSTING_FAILED: 500,
  POSTING_PERIOD_NO_LONGER_OPEN: 422,
  POSTING_CONCURRENT_ACTION: 409,
  IDEMPOTENCY_PAYLOAD_MISMATCH: 409,
  POSTING_EVENT_IN_PROGRESS: 409,
}

export class JournalPostingError extends AppError {
  constructor(
    code: JournalPostingErrorCode,
    message: string,
    errors?: Array<{ field: string; message: string }>,
  ) {
    super(STATUS_BY_CODE[code] ?? 422, message, code, errors)
    this.name = 'JournalPostingError'
  }
}
