/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        erp: {
          bg: 'var(--erp-bg)',
          'bg-subtle': 'var(--erp-bg-subtle)',
          surface: 'var(--erp-surface)',
          'surface-alt': 'var(--erp-surface-alt)',
          'surface-raised': 'var(--erp-surface-raised)',
          border: 'var(--erp-border)',
          'border-strong': 'var(--erp-border-strong)',
          text: 'var(--erp-text)',
          muted: 'var(--erp-muted)',
          primary: 'var(--erp-primary)',
          'primary-soft': 'var(--erp-primary-soft)',
          'primary-muted': 'var(--erp-primary-muted)',
          accent: 'var(--erp-accent)',
          navy: 'var(--erp-navy)',
          shell: 'var(--erp-shell)',
          'shell-accent': 'var(--erp-shell-accent)',
          success: 'var(--erp-success-solid)',
          'success-fg': 'var(--erp-success-fg)',
          'success-soft': 'var(--erp-success-soft)',
          warning: 'var(--erp-warning-solid)',
          'warning-fg': 'var(--erp-warning-fg)',
          'warning-soft': 'var(--erp-warning-soft)',
          danger: 'var(--erp-danger-solid)',
          'danger-fg': 'var(--erp-danger-fg)',
          'danger-soft': 'var(--erp-danger-soft)',
          info: 'var(--erp-info-solid)',
          'info-fg': 'var(--erp-info-fg)',
          'info-soft': 'var(--erp-info-soft)',
          indigo: 'var(--erp-indigo)',
          cyan: 'var(--erp-cyan)',
        },
      },
      fontFamily: {
        sans: ['Segoe UI Variable', 'Segoe UI', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['Cascadia Mono', 'Consolas', 'Segoe UI Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'erp-2xs': ['var(--erp-font-2xs)', { lineHeight: 'var(--erp-lh-tight)' }],
        'erp-xs': ['var(--erp-font-xs)', { lineHeight: 'var(--erp-lh-snug)' }],
        'erp-sm': ['var(--erp-font-sm)', { lineHeight: 'var(--erp-lh-snug)' }],
        'erp-base': ['var(--erp-font-base)', { lineHeight: 'var(--erp-lh-normal)' }],
        'erp-lg': ['var(--erp-font-lg)', { lineHeight: 'var(--erp-lh-tight)' }],
        'erp-xl': ['var(--erp-font-xl)', { lineHeight: 'var(--erp-lh-tight)' }],
      },
      boxShadow: {
        erp: 'var(--erp-shadow)',
        'erp-md': 'var(--erp-shadow-md)',
        'erp-lg': 'var(--erp-shadow-lg)',
      },
      borderRadius: {
        erp: 'var(--erp-radius)',
        'erp-sm': 'var(--erp-radius-sm)',
      },
    },
  },
  plugins: [],
}
