import type { BankConnectorDto } from '../api/bank-connector.types'

/** Demo-mode seed — disabled connectors only; never “connected”. */
export function seedDemoBankConnectors(): BankConnectorDto[] {
  const now = new Date().toISOString()
  return [
    {
      id: 'demo-conn-hdfc-rest',
      tenantId: 'demo',
      legalEntityId: 'demo-le',
      treasuryAccountId: 'demo-bank-1',
      code: 'HDFC-REST-DEMO',
      name: 'HDFC REST (scaffold)',
      provider: 'GENERIC_REST',
      status: 'DISABLED',
      baseUrl: null,
      scheduleCron: null,
      configJson: { expectedFormat: 'MT940', notes: 'Demo seed — Coming soon' },
      lastTestAt: null,
      lastTestStatus: 'NOT_CONFIGURED',
      lastTestMessage: null,
      lastSyncAt: null,
      lastSyncStatus: null,
      lastSyncMessage: null,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      isLiveConnected: false,
      connectionLabel: 'Disabled',
      consent: null,
    },
    {
      id: 'demo-conn-icici-sftp',
      tenantId: 'demo',
      legalEntityId: 'demo-le',
      treasuryAccountId: 'demo-bank-1',
      code: 'ICICI-SFTP-DEMO',
      name: 'ICICI MT940 SFTP (scaffold)',
      provider: 'MT940_SFTP',
      status: 'DISABLED',
      baseUrl: null,
      scheduleCron: null,
      configJson: { expectedFormat: 'MT940', remotePath: '/outbound/mt940' },
      lastTestAt: null,
      lastTestStatus: 'NOT_CONFIGURED',
      lastTestMessage: null,
      lastSyncAt: null,
      lastSyncStatus: null,
      lastSyncMessage: null,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      isLiveConnected: false,
      connectionLabel: 'Disabled',
      consent: null,
    },
  ]
}
