-- Manufacturing Phase 6A — Production Planning workbench (ProductionPlan + lines).
-- Additive only. Not MRP II / CRP / costing / GL. Short index names for MySQL.

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER', 'LEAD', 'CONTACT', 'CRM_COMPANY', 'OPPORTUNITY', 'QUOTATION', 'SALES_ORDER',
  'PRODUCTION_DEMAND', 'PRODUCTION_ORDER', 'DAILY_PRODUCTION_BATCH', 'PRODUCTION_ISSUE',
  'STOCK_MOVEMENT', 'STOCK_RESERVATION', 'PURCHASE_REQUISITION',
  'QUALITY_INSPECTION', 'QUALITY_NCR', 'JOB_WORK_ORDER', 'PRODUCTION_RUNTIME_CHANGE',
  'PRODUCTION_WIP_MOVEMENT', 'MANUFACTURING_CORRECTION', 'PRODUCTION_PLAN'
) NOT NULL;

CREATE TABLE `production_plans` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `planNumber` VARCHAR(64) NOT NULL,
  `planName` VARCHAR(200) NOT NULL,
  `planDate` DATE NOT NULL,
  `sourceType` ENUM('SALES_ORDER', 'STOCK_REPLENISHMENT', 'FORECAST', 'MANUAL') NOT NULL DEFAULT 'MANUAL',
  `status` ENUM('DRAFT', 'PLANNED', 'WORK_ORDERS_CREATED', 'CLOSED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `warehouseId` VARCHAR(191) NULL,
  `plantCode` VARCHAR(32) NULL,
  `periodFrom` DATE NULL,
  `periodTo` DATE NULL,
  `notes` TEXT NULL,
  `ownerUserId` VARCHAR(191) NULL,
  `releasedAt` DATETIME(3) NULL,
  `releasedBy` VARCHAR(191) NULL,
  `closedAt` DATETIME(3) NULL,
  `closedBy` VARCHAR(191) NULL,
  `cancelledAt` DATETIME(3) NULL,
  `cancelledBy` VARCHAR(191) NULL,
  `cancelReason` TEXT NULL,
  `idempotencyKey` VARCHAR(150) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `mfg_plan_tenant_num_key` (`tenantId`, `planNumber`),
  UNIQUE INDEX `mfg_plan_tenant_idem_key` (`tenantId`, `idempotencyKey`),
  INDEX `mfg_plan_tenant_idx` (`tenantId`),
  INDEX `mfg_plan_tenant_status_idx` (`tenantId`, `status`),
  INDEX `mfg_plan_tenant_del_idx` (`tenantId`, `deletedAt`),
  CONSTRAINT `mfg_plan_tenant_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `mfg_plan_wh_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `master_warehouses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `production_plan_lines` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `planId` VARCHAR(191) NOT NULL,
  `lineNo` INT NOT NULL,
  `productItemId` VARCHAR(191) NOT NULL,
  `uomId` VARCHAR(191) NOT NULL,
  `demandQuantity` DECIMAL(18, 4) NOT NULL,
  `safetyStockQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `suggestedQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `availableFinishedStock` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `openWorkOrderQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `requiredDate` DATE NULL,
  `demandId` VARCHAR(191) NULL,
  `productionOrderId` VARCHAR(191) NULL,
  `salesOrderId` VARCHAR(191) NULL,
  `sourceDocumentId` VARCHAR(191) NULL,
  `sourceDocumentNo` VARCHAR(64) NULL,
  `ignored` BOOLEAN NOT NULL DEFAULT false,
  `bomReady` BOOLEAN NOT NULL DEFAULT false,
  `materialStatus` VARCHAR(32) NULL,
  `notes` TEXT NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `mfg_plan_line_tenant_plan_line_key` (`tenantId`, `planId`, `lineNo`),
  INDEX `mfg_plan_line_tenant_idx` (`tenantId`),
  INDEX `mfg_plan_line_tenant_plan_idx` (`tenantId`, `planId`),
  INDEX `mfg_plan_line_tenant_item_idx` (`tenantId`, `productItemId`),
  INDEX `mfg_plan_line_tenant_del_idx` (`tenantId`, `deletedAt`),
  CONSTRAINT `mfg_plan_line_tenant_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `mfg_plan_line_plan_fkey` FOREIGN KEY (`planId`) REFERENCES `production_plans` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `mfg_plan_line_item_fkey` FOREIGN KEY (`productItemId`) REFERENCES `master_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `mfg_plan_line_uom_fkey` FOREIGN KEY (`uomId`) REFERENCES `master_uoms` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `mfg_plan_line_demand_fkey` FOREIGN KEY (`demandId`) REFERENCES `production_demands` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `mfg_plan_line_wo_fkey` FOREIGN KEY (`productionOrderId`) REFERENCES `production_orders` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
