/**
 * Reduce the quotation template catalog to the two VF ISO product templates
 * (matches prisma/quotationTemplateSeedData.ts and frontend DEFAULT_QUOTATION_TEMPLATES):
 *   - ISO-TANK-26KL        (26 KL ISO Tank Container Quotation)
 *   - ISO-DRY-BULK-25CBM   (25 m³ ISO Tank Container Quotation)
 *
 * For every non-deleted tenant:
 *   1. Soft-deletes (deletedAt + isActive=false) all other templates — existing
 *      quotations are untouched; templates are catalog-only.
 *   2. Upserts / restores the two keep templates from the seed rows.
 *
 * Idempotent — safe to re-run. Usage (from backend/):
 *   npx tsx scripts/cleanup-quotation-templates.ts             # apply
 *   npx tsx scripts/cleanup-quotation-templates.ts --dry-run   # report only
 *   npx tsx scripts/cleanup-quotation-templates.ts --emit-sql  # also write scripts/quotation-template-cleanup.sql for phpMyAdmin
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { prisma } from '../src/config/database.js'
import {
  QUOTATION_TEMPLATE_KEEP_CODES,
  QUOTATION_TEMPLATE_SEED_ROWS,
  VF_WORD_PRINT_LAYOUT_SEED,
} from '../prisma/quotationTemplateSeedData.js'

const dryRun = process.argv.includes('--dry-run')
const emitSql = process.argv.includes('--emit-sql')
const KEEP_CODES = [...QUOTATION_TEMPLATE_KEEP_CODES]

async function main() {
  const tenants = await prisma.tenant.findMany({ where: { deletedAt: null }, select: { id: true, name: true } })
  console.log(`Keep codes: ${KEEP_CODES.join(', ')}`)

  for (const tenant of tenants) {
    const extras = await prisma.crmQuotationTemplate.findMany({
      where: { tenantId: tenant.id, deletedAt: null, code: { notIn: KEEP_CODES } },
      select: { id: true, code: true, templateName: true },
    })
    console.log(`\nTenant ${tenant.name}: ${extras.length} template(s) to remove`)
    for (const t of extras) console.log(`  - ${t.code} | ${t.templateName}`)

    if (!dryRun && extras.length > 0) {
      await prisma.crmQuotationTemplate.updateMany({
        where: { id: { in: extras.map((t) => t.id) } },
        data: { deletedAt: new Date(), isActive: false },
      })
    }

    for (const row of QUOTATION_TEMPLATE_SEED_ROWS) {
      const existing = await prisma.crmQuotationTemplate.findFirst({
        where: { tenantId: tenant.id, code: row.code },
        select: { id: true, deletedAt: true, isActive: true },
      })
      if (!existing) {
        console.log(`  + create ${row.code}`)
        if (dryRun) continue
        await prisma.crmQuotationTemplate.create({
          data: {
            tenantId: tenant.id,
            code: row.code,
            templateName: row.templateName,
            productFamily: row.productFamily,
            version: row.version,
            sections: row.sections,
            defaultTerms: row.defaultTerms,
            defaultWarranty: row.defaultWarranty,
            defaultExclusions: row.defaultExclusions,
            printLayout: VF_WORD_PRINT_LAYOUT_SEED,
            isActive: true,
          },
        })
      } else {
        console.log(`  ~ sync ${row.code}`)
        if (dryRun) continue
        await prisma.crmQuotationTemplate.update({
          where: { id: existing.id },
          data: {
            deletedAt: null,
            isActive: true,
            templateName: row.templateName,
            productFamily: row.productFamily,
            version: row.version,
            sections: row.sections,
            defaultTerms: row.defaultTerms,
            defaultWarranty: row.defaultWarranty,
            defaultExclusions: row.defaultExclusions,
            printLayout: VF_WORD_PRINT_LAYOUT_SEED,
          },
        })
      }
    }
  }

  if (emitSql) {
    // Escape backslashes too — MySQL string literals treat \n etc. as escapes,
    // which would corrupt the JSON `sections` payload.
    const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "''")
    const keepList = KEEP_CODES.map((c) => `'${c}'`).join(', ')
    const lines: string[] = [
      '-- Generated by backend/scripts/cleanup-quotation-templates.ts --emit-sql — do not edit by hand.',
      '-- Keeps only the two VF ISO quotation templates; idempotent, safe to re-run.',
      '-- Existing quotations are untouched (templates are catalog-only, soft delete).',
      '',
      '-- 1) Soft-delete every other template',
      'UPDATE `crm_quotation_templates`',
      "SET `deletedAt` = NOW(3), `isActive` = 0, `updatedAt` = NOW(3)",
      `WHERE \`deletedAt\` IS NULL AND \`code\` NOT IN (${keepList});`,
      '',
      '-- 2) Restore keep templates if previously soft-deleted or inactive',
      'UPDATE `crm_quotation_templates`',
      "SET `deletedAt` = NULL, `isActive` = 1, `updatedAt` = NOW(3)",
      `WHERE \`code\` IN (${keepList}) AND (\`deletedAt\` IS NOT NULL OR \`isActive\` = 0);`,
      '',
      '-- 3) Create keep templates for tenants missing them',
    ]
    for (const row of QUOTATION_TEMPLATE_SEED_ROWS) {
      lines.push(
        'INSERT INTO `crm_quotation_templates`',
        '  (`id`, `tenantId`, `code`, `templateName`, `productFamily`, `version`, `sections`, `defaultTerms`, `defaultWarranty`, `defaultExclusions`, `isActive`, `createdAt`, `updatedAt`)',
        `SELECT UUID(), t.\`id\`, '${row.code}', '${esc(row.templateName)}', '${esc(row.productFamily)}', ${row.version},`,
        `  '${esc(JSON.stringify(row.sections))}',`,
        `  '${esc(row.defaultTerms)}', '${esc(row.defaultWarranty)}', '${esc(row.defaultExclusions)}', 1, NOW(3), NOW(3)`,
        'FROM `tenants` t',
        'WHERE t.`deletedAt` IS NULL',
        `  AND NOT EXISTS (SELECT 1 FROM \`crm_quotation_templates\` q WHERE q.\`tenantId\` = t.\`id\` AND q.\`code\` = '${row.code}');`,
        '',
      )
    }
    lines.push('-- Verify:')
    lines.push('-- SELECT code, templateName, isActive, deletedAt FROM crm_quotation_templates ORDER BY code;')
    lines.push('')
    const outPath = join(dirname(fileURLToPath(import.meta.url)), 'quotation-template-cleanup.sql')
    writeFileSync(outPath, lines.join('\n'), 'utf8')
    console.log(`\nWrote ${outPath}`)
  }

  console.log(dryRun ? '\nDry run complete — no changes applied.' : '\nDone.')
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
