/**
 * Emit an idempotent SQL script that backfills the permission catalog and
 * role→permission links — for environments where you cannot run Node against
 * the live DB (e.g. paste into phpMyAdmin on shared hosting).
 *
 * Mirrors scripts/sync-permissions.ts exactly (same PERMISSIONS / ROLE_PERMISSIONS
 * source of truth). Safe to run repeatedly: INSERT IGNORE against the unique keys
 * (`permissions.name`, `role_permissions.roleId+permissionId`). Never deletes,
 * never updates existing rows, never touches users/tenants/business data.
 *
 * Usage (from backend/):
 *   npx tsx scripts/generate-permission-sync-sql.ts   # writes scripts/permission-sync.sql
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PERMISSIONS, ROLE_PERMISSIONS } from '../src/constants/permissions.js'

const lines: string[] = [
  '-- Generated by backend/scripts/generate-permission-sync-sql.ts — do not edit by hand.',
  `-- Source of truth: backend/src/constants/permissions.ts (${PERMISSIONS.length} permissions, ${Object.keys(ROLE_PERMISSIONS).length} roles).`,
  '-- Idempotent: INSERT IGNORE only — re-running is a no-op; existing grants are never removed or modified.',
  '-- After running: users must log out and log back in to receive updated session permissions.',
  '',
  '-- 1) Permission catalog (skips names that already exist)',
]

for (const name of PERMISSIONS) {
  const [module] = name.split('.')
  lines.push(
    'INSERT IGNORE INTO `permissions` (`id`, `name`, `module`, `description`, `createdAt`) ' +
      `VALUES (UUID(), '${name}', '${module}', '${name}', NOW(3));`,
  )
}

lines.push('')
lines.push('-- 2) Role → permission links (applies to every non-deleted role with a matching name, across all tenants)')

for (const [roleName, perms] of Object.entries(ROLE_PERMISSIONS)) {
  const inList = perms.map((p) => `'${p}'`).join(', ')
  lines.push('')
  lines.push(`-- ${roleName} (${perms.length} permissions)`)
  lines.push('INSERT IGNORE INTO `role_permissions` (`id`, `roleId`, `permissionId`)')
  lines.push('SELECT UUID(), r.`id`, p.`id`')
  lines.push('FROM `roles` r')
  lines.push(`JOIN \`permissions\` p ON p.\`name\` IN (${inList})`)
  lines.push(`WHERE r.\`name\` = '${roleName.replace(/'/g, "''")}' AND r.\`deletedAt\` IS NULL;`)
}

lines.push('')

const outPath = join(dirname(fileURLToPath(import.meta.url)), 'permission-sync.sql')
writeFileSync(outPath, lines.join('\n'), 'utf8')
console.log(`Wrote ${outPath} (${lines.length} lines).`)
