/**
 * Upsert only SIDEWALL-34FT-5FT (156 — 34′ × 5′ Side Wall Trailer).
 * Does NOT soft-delete other templates. Idempotent.
 *
 * Usage (from backend/):
 *   npx tsx scripts/seed-sidewall-34ft-5ft.ts
 *   npx tsx scripts/seed-sidewall-34ft-5ft.ts --dry-run
 *   npx tsx scripts/seed-sidewall-34ft-5ft.ts --emit-sql
 *   # → writes scripts/seed-sidewall-34ft-5ft.sql for phpMyAdmin
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { prisma } from '../src/config/database.js'
import {
  QUOTATION_TEMPLATE_SEED_ROWS,
  VF_WORD_PRINT_LAYOUT_SEED,
} from '../prisma/quotationTemplateSeedData.js'

const TARGET_CODES = ['SIDEWALL-34FT-5FT'] as const
const dryRun = process.argv.includes('--dry-run')
const emitSql = process.argv.includes('--emit-sql')

const ROWS = QUOTATION_TEMPLATE_SEED_ROWS.filter((r) =>
  (TARGET_CODES as readonly string[]).includes(r.code),
)

if (ROWS.length !== TARGET_CODES.length) {
  console.error(
    `Seed rows missing. Expected ${TARGET_CODES.join(', ')}; got ${ROWS.map((r) => r.code).join(', ') || '(none)'}`,
  )
  process.exit(1)
}

async function main() {
  console.log(`Target codes: ${TARGET_CODES.join(', ')}`)

  const tenants = await prisma.tenant.findMany({
    where: { deletedAt: null },
    select: { id: true, name: true, slug: true },
  })

  for (const tenant of tenants) {
    console.log(`\nTenant ${tenant.slug ?? tenant.name}`)
    for (const row of ROWS) {
      const existing = await prisma.crmQuotationTemplate.findFirst({
        where: { tenantId: tenant.id, code: row.code },
        select: { id: true, deletedAt: true, isActive: true },
      })
      if (!existing) {
        console.log(`  + create ${row.code}`)
        if (dryRun) continue
        await prisma.crmQuotationTemplate.create({
          data: {
            tenantId: tenant.id,
            code: row.code,
            templateName: row.templateName,
            productFamily: row.productFamily,
            version: row.version,
            sections: row.sections,
            defaultTerms: row.defaultTerms,
            defaultWarranty: row.defaultWarranty,
            defaultExclusions: row.defaultExclusions,
            printLayout: VF_WORD_PRINT_LAYOUT_SEED,
            isActive: true,
          },
        })
      } else {
        console.log(`  ~ sync ${row.code}`)
        if (dryRun) continue
        await prisma.crmQuotationTemplate.update({
          where: { id: existing.id },
          data: {
            deletedAt: null,
            isActive: true,
            templateName: row.templateName,
            productFamily: row.productFamily,
            version: row.version,
            sections: row.sections,
            defaultTerms: row.defaultTerms,
            defaultWarranty: row.defaultWarranty,
            defaultExclusions: row.defaultExclusions,
            printLayout: VF_WORD_PRINT_LAYOUT_SEED,
          },
        })
      }
    }
  }

  if (emitSql) {
    const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "''")
    const codeList = TARGET_CODES.map((c) => `'${c}'`).join(', ')
    const lines: string[] = [
      '-- Generated by backend/scripts/seed-sidewall-34ft-5ft.ts --emit-sql',
      '-- Upserts SIDEWALL-34FT-5FT only. Idempotent. Safe to re-run.',
      '-- Paste into phpMyAdmin on live.',
      '',
      '-- 1) Restore if soft-deleted / inactive',
      'UPDATE `crm_quotation_templates`',
      "SET `deletedAt` = NULL, `isActive` = 1, `updatedAt` = NOW(3)",
      `WHERE \`code\` IN (${codeList}) AND (\`deletedAt\` IS NOT NULL OR \`isActive\` = 0);`,
      '',
      '-- 2) Create for tenants missing them (full seed payload)',
    ]
    for (const row of ROWS) {
      const layoutJson = esc(JSON.stringify(VF_WORD_PRINT_LAYOUT_SEED))
      lines.push(
        'INSERT INTO `crm_quotation_templates`',
        '  (`id`, `tenantId`, `code`, `templateName`, `productFamily`, `version`, `sections`, `defaultTerms`, `defaultWarranty`, `defaultExclusions`, `printLayout`, `isActive`, `createdAt`, `updatedAt`)',
        `SELECT UUID(), t.\`id\`, '${row.code}', '${esc(row.templateName)}', '${esc(row.productFamily)}', ${row.version},`,
        `  '${esc(JSON.stringify(row.sections))}',`,
        `  '${esc(row.defaultTerms)}', '${esc(row.defaultWarranty)}', '${esc(row.defaultExclusions)}',`,
        `  '${layoutJson}', 1, NOW(3), NOW(3)`,
        'FROM `tenants` t',
        'WHERE t.`deletedAt` IS NULL',
        `  AND NOT EXISTS (SELECT 1 FROM \`crm_quotation_templates\` q WHERE q.\`tenantId\` = t.\`id\` AND q.\`code\` = '${row.code}');`,
        '',
        `-- 3) Sync payload if row already exists for ${row.code}`,
        'UPDATE `crm_quotation_templates`',
        'SET',
        `  \`templateName\` = '${esc(row.templateName)}',`,
        `  \`productFamily\` = '${esc(row.productFamily)}',`,
        `  \`version\` = ${row.version},`,
        `  \`sections\` = '${esc(JSON.stringify(row.sections))}',`,
        `  \`defaultTerms\` = '${esc(row.defaultTerms)}',`,
        `  \`defaultWarranty\` = '${esc(row.defaultWarranty)}',`,
        `  \`defaultExclusions\` = '${esc(row.defaultExclusions)}',`,
        `  \`printLayout\` = '${layoutJson}',`,
        '  `deletedAt` = NULL,',
        '  `isActive` = 1,',
        '  `updatedAt` = NOW(3)',
        `WHERE \`code\` = '${row.code}';`,
        '',
      )
    }
    lines.push('-- Verify:')
    lines.push(
      `SELECT code, templateName, productFamily, version, isActive, deletedAt FROM crm_quotation_templates WHERE code IN (${codeList}) ORDER BY code;`,
    )
    lines.push('')
    const outPath = join(dirname(fileURLToPath(import.meta.url)), 'seed-sidewall-34ft-5ft.sql')
    writeFileSync(outPath, lines.join('\n'), 'utf8')
    console.log(`\nWrote ${outPath}`)
  }

  console.log(dryRun ? '\nDry run complete — no changes applied.' : '\nDone.')
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
