-- HRMS Phase 11 — Exit, Offboarding & Full & Final Settlement

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER','LEAD','CONTACT','CRM_COMPANY','OPPORTUNITY','QUOTATION','SALES_ORDER',
  'PRODUCTION_DEMAND','PRODUCTION_ORDER','DAILY_PRODUCTION_BATCH','PRODUCTION_ISSUE',
  'STOCK_MOVEMENT','STOCK_RESERVATION','PURCHASE_REQUISITION','PURCHASE_PLANNING',
  'REQUEST_FOR_QUOTATION','VENDOR_QUOTATION','VENDOR_COMPARISON','PURCHASE_ORDER',
  'GOODS_RECEIPT','QUALITY_INSPECTION','QUALITY_NCR','PURCHASE_INVOICE','PURCHASE_RETURN',
  'JOB_WORK_ORDER','PRODUCTION_RUNTIME_CHANGE','PRODUCTION_WIP_MOVEMENT','MANUFACTURING_CORRECTION',
  'PRODUCTION_PLAN','DEMAND_CONSOLIDATION_PLAN','OUTBOUND_DISPATCH','PRODUCTION_FG_RECEIPT',
  'DISPATCH_REQUIREMENT','DISPATCH_PICK_LIST','DISPATCH_PACKING_SESSION','DISPATCH_PACKAGE',
  'DELIVERY_CHALLAN','PURCHASE_QUALITY_INSPECTION','INVENTORY_TRANSFER','INVENTORY_STOCK_COUNT',
  'INVENTORY_ADJUSTMENT','MANUFACTURING_ROUTING','DISPATCH_POSTING','DISPATCH_REVERSAL',
  'MAINTENANCE_TICKET','PREVENTIVE_MAINTENANCE_PLAN','EMPLOYEE','PAYSLIP','SALARY_PAYMENT_BATCH',
  'EMPLOYEE_LOAN','SALARY_ADVANCE','EMPLOYEE_EXIT','FULL_FINAL_SETTLEMENT'
) NOT NULL;

ALTER TABLE `default_account_mappings`
  MODIFY `mappingKey` ENUM(
    'CUSTOMER_RECEIVABLE','VENDOR_PAYABLE','SALES_REVENUE','SALES_RETURN','PURCHASE','PURCHASE_RETURN',
    'RAW_MATERIAL_INVENTORY','WIP_INVENTORY','FINISHED_GOODS_INVENTORY','STOCK_ADJUSTMENT','MATERIAL_CONSUMPTION',
    'GRIR_CLEARING','PURCHASE_PRICE_VARIANCE','COST_OF_GOODS_SOLD',
    'LABOUR_ABSORPTION','MACHINE_ABSORPTION','JOB_WORK_ABSORPTION','PRODUCTION_OVERHEAD_ABSORPTION',
    'PRODUCTION_VARIANCE','SCRAP_INVENTORY','SCRAP_LOSS','SUBCONTRACTING_EXPENSE','FREIGHT_INWARD','FREIGHT_OUTWARD',
    'GST_INPUT_CGST','GST_INPUT_SGST','GST_INPUT_IGST','GST_OUTPUT_CGST','GST_OUTPUT_SGST','GST_OUTPUT_IGST','GST_OUTPUT_CESS',
    'TDS_RECEIVABLE','TDS_PAYABLE','BANK_CHARGES','ROUNDING',
    'DEPRECIATION_EXPENSE','ACCUMULATED_DEPRECIATION','ASSET_DISPOSAL_GAIN','ASSET_DISPOSAL_LOSS','FIXED_ASSET_CLEARING',
    'ASSET_REVALUATION_SURPLUS','ASSET_IMPAIRMENT_LOSS','RETAINED_EARNINGS',
    'INTERNAL_TRANSFER_CLEARING','CHEQUE_RECEIPT_CLEARING','CHEQUE_PAYMENT_CLEARING',
    'BANK_INTEREST_INCOME','BANK_INTEREST_EXPENSE','COLLECTION_FEE_EXPENSE','MERCHANT_FEE_EXPENSE',
    'ACCRUED_EXPENSE_LIABILITY','PREPAID_EXPENSE_ASSET','UNREALIZED_FX_GAIN','UNREALIZED_FX_LOSS',
    'SALARY_BASIC_EXPENSE','SALARY_HRA_EXPENSE','SALARY_ALLOWANCE_EXPENSE','SALARY_OT_EXPENSE','SALARY_PAYABLE',
    'PF_EMPLOYEE_PAYABLE','PF_EMPLOYER_PAYABLE','PF_EMPLOYER_EXPENSE',
    'ESIC_EMPLOYEE_PAYABLE','ESIC_EMPLOYER_PAYABLE','ESIC_EMPLOYER_EXPENSE',
    'PT_PAYABLE','TDS_SALARY_PAYABLE','LWF_PAYABLE','LWF_EMPLOYER_PAYABLE','LWF_EMPLOYER_EXPENSE',
    'EMPLOYEE_LOAN_RECEIVABLE','SALARY_ADVANCE_RECEIVABLE',
    'EMPLOYEE_FNF_PAYABLE','EMPLOYEE_FNF_RECEIVABLE','LEAVE_ENCASHMENT_EXPENSE','NOTICE_PAY_EXPENSE','NOTICE_RECOVERY_INCOME','ASSET_RECOVERY_INCOME'
  ) NOT NULL;

ALTER TABLE `hr_employees`
  ADD COLUMN `noticePeriodDays` INTEGER NULL,
  ADD COLUMN `exitDate` DATE NULL,
  ADD COLUMN `lastWorkingDate` DATE NULL;

ALTER TABLE `hr_leave_types`
  ADD COLUMN `fnfSettlementAction` ENUM('ENCASH','LAPSE','IGNORE') NOT NULL DEFAULT 'IGNORE',
  ADD COLUMN `maxEncashDays` DECIMAL(8, 2) NULL;

CREATE TABLE `hr_exit_clearance_templates` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NULL,
  `code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `sequence` INTEGER NOT NULL DEFAULT 10,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_exit_clearance_templates_tenantId_code_key` (`tenantId`, `code`),
  INDEX `hr_exit_clearance_templates_tenantId_idx` (`tenantId`),
  INDEX `hr_exit_clearance_templates_tenantId_legalEntityId_idx` (`tenantId`, `legalEntityId`),
  CONSTRAINT `hr_exit_clearance_templates_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_exit_clearance_templates_legalEntityId_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_employee_exits` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `employeeId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `branchId` VARCHAR(191) NULL,
  `exitType` ENUM('RESIGNATION','TERMINATION','RETIREMENT','CONTRACT_END','ABSCONDING','OTHER') NOT NULL,
  `resignationDate` DATE NULL,
  `requestedLastWorkingDate` DATE NOT NULL,
  `approvedLastWorkingDate` DATE NULL,
  `noticePeriodDays` INTEGER NOT NULL DEFAULT 0,
  `noticeServedDays` INTEGER NOT NULL DEFAULT 0,
  `noticeShortfallDays` INTEGER NOT NULL DEFAULT 0,
  `noticeExcessDays` INTEGER NOT NULL DEFAULT 0,
  `noticeSettlementMode` VARCHAR(16) NOT NULL DEFAULT 'recover',
  `reason` VARCHAR(1000) NULL,
  `remarks` VARCHAR(1000) NULL,
  `status` ENUM('DRAFT','SUBMITTED','APPROVED','CLEARANCE_PENDING','READY_FOR_SETTLEMENT','SETTLED','CLOSED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `approvedByUserId` VARCHAR(191) NULL,
  `approvedAt` DATETIME(3) NULL,
  `rejectedReason` VARCHAR(500) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_employee_exits_tenantId_code_key` (`tenantId`, `code`),
  INDEX `hr_employee_exits_tenantId_idx` (`tenantId`),
  INDEX `hr_employee_exits_tenantId_employeeId_idx` (`tenantId`, `employeeId`),
  INDEX `hr_employee_exits_tenantId_legalEntityId_idx` (`tenantId`, `legalEntityId`),
  INDEX `hr_employee_exits_tenantId_branchId_idx` (`tenantId`, `branchId`),
  INDEX `hr_employee_exits_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `hr_employee_exits_tenantId_deletedAt_idx` (`tenantId`, `deletedAt`),
  CONSTRAINT `hr_employee_exits_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_employee_exits_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_employee_exits_legalEntityId_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_employee_exits_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_exit_clearance_items` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `exitId` VARCHAR(191) NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `sequence` INTEGER NOT NULL DEFAULT 10,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `hr_exit_clearance_items_tenantId_idx` (`tenantId`),
  INDEX `hr_exit_clearance_items_tenantId_exitId_idx` (`tenantId`, `exitId`),
  CONSTRAINT `hr_exit_clearance_items_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_exit_clearance_lines` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `exitId` VARCHAR(191) NOT NULL,
  `itemId` VARCHAR(191) NULL,
  `code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `sequence` INTEGER NOT NULL DEFAULT 10,
  `status` ENUM('PENDING','CLEARED','WAIVED') NOT NULL DEFAULT 'PENDING',
  `ownerUserId` VARCHAR(191) NULL,
  `remarks` VARCHAR(500) NULL,
  `clearedByUserId` VARCHAR(191) NULL,
  `clearedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_exit_clearance_lines_exitId_code_key` (`exitId`, `code`),
  INDEX `hr_exit_clearance_lines_tenantId_idx` (`tenantId`),
  INDEX `hr_exit_clearance_lines_tenantId_exitId_idx` (`tenantId`, `exitId`),
  INDEX `hr_exit_clearance_lines_tenantId_status_idx` (`tenantId`, `status`),
  CONSTRAINT `hr_exit_clearance_lines_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_exit_clearance_lines_exitId_fkey` FOREIGN KEY (`exitId`) REFERENCES `hr_employee_exits` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_exit_clearance_lines_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `hr_exit_clearance_items` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_exit_asset_lines` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `exitId` VARCHAR(191) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `assetCategory` VARCHAR(64) NULL,
  `status` ENUM('PENDING','RETURNED','NOT_RETURNED','DAMAGED','WAIVED') NOT NULL DEFAULT 'PENDING',
  `recoveryAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `remarks` VARCHAR(500) NULL,
  `clearedByUserId` VARCHAR(191) NULL,
  `clearedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `hr_exit_asset_lines_tenantId_idx` (`tenantId`),
  INDEX `hr_exit_asset_lines_tenantId_exitId_idx` (`tenantId`, `exitId`),
  INDEX `hr_exit_asset_lines_tenantId_status_idx` (`tenantId`, `status`),
  CONSTRAINT `hr_exit_asset_lines_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_exit_asset_lines_exitId_fkey` FOREIGN KEY (`exitId`) REFERENCES `hr_employee_exits` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_full_final_settlements` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `employeeExitId` VARCHAR(191) NOT NULL,
  `employeeId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `branchId` VARCHAR(191) NULL,
  `lastWorkingDate` DATE NOT NULL,
  `status` ENUM('DRAFT','CALCULATED','REVIEWED','APPROVED','POSTED','PAID','CLOSED') NOT NULL DEFAULT 'DRAFT',
  `earningsTotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `deductionsTotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `netSettlement` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `exceptionsJson` LONGTEXT NULL,
  `calculatedAt` DATETIME(3) NULL,
  `reviewedAt` DATETIME(3) NULL,
  `reviewedByUserId` VARCHAR(191) NULL,
  `approvedAt` DATETIME(3) NULL,
  `approvedByUserId` VARCHAR(191) NULL,
  `postedAt` DATETIME(3) NULL,
  `postedByUserId` VARCHAR(191) NULL,
  `accountingVoucherId` VARCHAR(191) NULL,
  `postingEventId` VARCHAR(191) NULL,
  `paidAt` DATETIME(3) NULL,
  `paidByUserId` VARCHAR(191) NULL,
  `paymentMethod` VARCHAR(16) NULL,
  `treasuryAccountId` VARCHAR(191) NULL,
  `paymentReference` VARCHAR(120) NULL,
  `paymentVoucherId` VARCHAR(191) NULL,
  `paymentPostingEventId` VARCHAR(191) NULL,
  `snapshotJson` LONGTEXT NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_full_final_settlements_employeeExitId_key` (`employeeExitId`),
  UNIQUE INDEX `hr_full_final_settlements_tenantId_code_key` (`tenantId`, `code`),
  INDEX `hr_full_final_settlements_tenantId_idx` (`tenantId`),
  INDEX `hr_full_final_settlements_tenantId_employeeId_idx` (`tenantId`, `employeeId`),
  INDEX `hr_full_final_settlements_tenantId_legalEntityId_idx` (`tenantId`, `legalEntityId`),
  INDEX `hr_full_final_settlements_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `hr_full_final_settlements_tenantId_deletedAt_idx` (`tenantId`, `deletedAt`),
  CONSTRAINT `hr_full_final_settlements_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_full_final_settlements_employeeExitId_fkey` FOREIGN KEY (`employeeExitId`) REFERENCES `hr_employee_exits` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_full_final_settlements_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_full_final_settlements_legalEntityId_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_full_final_settlements_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_fnf_components` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `settlementId` VARCHAR(191) NOT NULL,
  `kind` ENUM('EARNING','DEDUCTION') NOT NULL,
  `code` VARCHAR(48) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `amount` DECIMAL(14, 2) NOT NULL,
  `calculationBasis` VARCHAR(500) NULL,
  `sourceRef` VARCHAR(120) NULL,
  `sequence` INTEGER NOT NULL DEFAULT 10,
  `mappingKeyHint` VARCHAR(64) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `hr_fnf_components_tenantId_idx` (`tenantId`),
  INDEX `hr_fnf_components_tenantId_settlementId_idx` (`tenantId`, `settlementId`),
  CONSTRAINT `hr_fnf_components_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_fnf_components_settlementId_fkey` FOREIGN KEY (`settlementId`) REFERENCES `hr_full_final_settlements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
