-- Phase 4 — Reverse charge (RCM) register: liability → payment confirmation → ITC recognition

CREATE TABLE IF NOT EXISTS `gst_rcm_register_entries` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `vendorInvoiceId` VARCHAR(191) NOT NULL,
  `returnPeriod` VARCHAR(7) NOT NULL,
  `documentNumber` VARCHAR(64) NOT NULL,
  `documentDate` DATE NOT NULL,
  `vendorId` VARCHAR(191) NOT NULL,
  `vendorName` VARCHAR(300) NOT NULL,
  `vendorGstin` VARCHAR(20) NULL,
  `placeOfSupply` VARCHAR(100) NULL,
  `taxableValue` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `cgstAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `sgstAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `igstAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `cessAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalTaxAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `recoverableTaxAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `itcEligibility` VARCHAR(40) NULL,
  `status` ENUM(
    'LIABILITY_POSTED',
    'LIABILITY_PAID',
    'ITC_RECOGNIZED',
    'ITC_NOT_CLAIMABLE',
    'VOID'
  ) NOT NULL DEFAULT 'LIABILITY_POSTED',
  `glInputTaxBookedAtPost` BOOLEAN NOT NULL DEFAULT true,
  `liabilityPaidAt` DATETIME(3) NULL,
  `liabilityPaidBy` VARCHAR(191) NULL,
  `liabilityPaidDate` DATE NULL,
  `liabilityPaymentRef` VARCHAR(128) NULL,
  `liabilityPaidNotes` VARCHAR(1000) NULL,
  `itcRecognizedAt` DATETIME(3) NULL,
  `itcRecognizedBy` VARCHAR(191) NULL,
  `itcClaimNotes` VARCHAR(1000) NULL,
  `accountingVoucherId` VARCHAR(191) NULL,
  `postingEventId` VARCHAR(191) NULL,
  `notes` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gst_rcm_register_entries_vendorInvoiceId_key`(`vendorInvoiceId`),
  INDEX `gst_rcm_le_period_idx`(`tenantId`, `legalEntityId`, `returnPeriod`),
  INDEX `gst_rcm_le_status_idx`(`tenantId`, `legalEntityId`, `status`),
  INDEX `gst_rcm_vi_idx`(`tenantId`, `vendorInvoiceId`),
  CONSTRAINT `gst_rcm_register_entries_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gst_rcm_register_entries_legalEntityId_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
