import type { VendorPaymentValidationIssue } from './vendor-payment-calculation.types.js'

export const VENDOR_PAYMENT_CALC_CODES = {
  VENDOR_REQUIRED: 'VENDOR_PAYMENT_VENDOR_REQUIRED',
  VENDOR_INACTIVE: 'VENDOR_PAYMENT_VENDOR_INACTIVE',
  PURPOSE_INVALID: 'VENDOR_PAYMENT_PURPOSE_INVALID',
  METHOD_INVALID: 'VENDOR_PAYMENT_METHOD_INVALID',
  AMOUNT_INVALID: 'VENDOR_PAYMENT_AMOUNT_INVALID',
  SETTLEMENT_AMOUNT_INVALID: 'VENDOR_PAYMENT_SETTLEMENT_AMOUNT_INVALID',
  CASH_OUTFLOW_INVALID: 'VENDOR_PAYMENT_CASH_OUTFLOW_INVALID',
  ADJUSTMENT_LINE_DUPLICATE: 'VENDOR_PAYMENT_ADJUSTMENT_LINE_DUPLICATE',
  ADJUSTMENT_TYPE_INVALID: 'VENDOR_PAYMENT_ADJUSTMENT_TYPE_INVALID',
  ADJUSTMENT_ROLE_INVALID: 'VENDOR_PAYMENT_ADJUSTMENT_ROLE_INVALID',
  ADJUSTMENT_AMOUNT_INVALID: 'VENDOR_PAYMENT_ADJUSTMENT_AMOUNT_INVALID',
  TDS_CONFIGURATION_MISSING: 'VENDOR_PAYMENT_TDS_CONFIGURATION_MISSING',
  TDS_SECTION_MISSING: 'VENDOR_PAYMENT_TDS_SECTION_MISSING',
  TDS_RATE_INVALID: 'VENDOR_PAYMENT_TDS_RATE_INVALID',
  TDS_BASE_INVALID: 'VENDOR_PAYMENT_TDS_BASE_INVALID',
  TDS_AMOUNT_INVALID: 'VENDOR_PAYMENT_TDS_AMOUNT_INVALID',
  TDS_DOUBLE_RECOGNITION: 'VENDOR_PAYMENT_TDS_DOUBLE_RECOGNITION',
  CURRENCY_INVALID: 'VENDOR_PAYMENT_CURRENCY_INVALID',
  EXCHANGE_RATE_INVALID: 'VENDOR_PAYMENT_EXCHANGE_RATE_INVALID',
  BASE_CURRENCY_RATE_INVALID: 'VENDOR_PAYMENT_BASE_CURRENCY_RATE_INVALID',
  PAYMENT_ACCOUNT_MISSING: 'VENDOR_PAYMENT_PAYMENT_ACCOUNT_MISSING',
  PAYABLE_ACCOUNT_MISSING: 'VENDOR_PAYMENT_PAYABLE_ACCOUNT_MISSING',
  TDS_ACCOUNT_MISSING: 'VENDOR_PAYMENT_TDS_ACCOUNT_MISSING',
  DISCOUNT_ACCOUNT_MISSING: 'VENDOR_PAYMENT_DISCOUNT_ACCOUNT_MISSING',
  RETENTION_ACCOUNT_MISSING: 'VENDOR_PAYMENT_RETENTION_ACCOUNT_MISSING',
  WITHHOLDING_ACCOUNT_MISSING: 'VENDOR_PAYMENT_WITHHOLDING_ACCOUNT_MISSING',
  BANK_CHARGE_ACCOUNT_MISSING: 'VENDOR_PAYMENT_BANK_CHARGE_ACCOUNT_MISSING',
  PROCESSING_ACCOUNT_MISSING: 'VENDOR_PAYMENT_PROCESSING_ACCOUNT_MISSING',
  ROUND_OFF_ACCOUNT_MISSING: 'VENDOR_PAYMENT_ROUND_OFF_ACCOUNT_MISSING',
  ACCOUNT_INVALID: 'VENDOR_PAYMENT_ACCOUNT_INVALID',
  REFERENCE_REQUIRED: 'VENDOR_PAYMENT_REFERENCE_REQUIRED',
  CHEQUE_DETAILS_REQUIRED: 'VENDOR_PAYMENT_CHEQUE_DETAILS_REQUIRED',
  ROUND_OFF_EXCEEDS_LIMIT: 'VENDOR_PAYMENT_ROUND_OFF_EXCEEDS_LIMIT',
  ACCOUNTING_PREVIEW_UNBALANCED: 'VENDOR_PAYMENT_ACCOUNTING_PREVIEW_UNBALANCED',
  BASE_PREVIEW_UNBALANCED: 'VENDOR_PAYMENT_BASE_PREVIEW_UNBALANCED',
  CONTEXT_LEGAL_ENTITY_MISMATCH: 'VENDOR_PAYMENT_CONTEXT_LEGAL_ENTITY_MISMATCH',
  SETTLEMENT_EXCEEDS_OUTSTANDING: 'VENDOR_PAYMENT_SETTLEMENT_EXCEEDS_OUTSTANDING',
  PURPOSE_MAY_BE_MIXED: 'VENDOR_PAYMENT_PURPOSE_MAY_BE_MIXED',
  ADVANCE_WITH_OPEN_PAYABLES: 'VENDOR_PAYMENT_ADVANCE_WITH_OPEN_PAYABLES',
  NO_OPEN_VENDOR_INVOICES: 'VENDOR_PAYMENT_NO_OPEN_VENDOR_INVOICES',
  TDS_REVIEW_REQUIRED: 'VENDOR_PAYMENT_TDS_REVIEW_REQUIRED',
  OTHER_ADJUSTMENT_REVIEW_REQUIRED: 'VENDOR_PAYMENT_OTHER_ADJUSTMENT_REVIEW_REQUIRED',
  UNALLOCATED_AFTER_POSTING: 'VENDOR_PAYMENT_UNALLOCATED_AFTER_POSTING',
} as const

export type VendorPaymentCalcCode = (typeof VENDOR_PAYMENT_CALC_CODES)[keyof typeof VENDOR_PAYMENT_CALC_CODES]

export function calcError(
  code: string,
  message: string,
  field?: string | null,
  extras?: Partial<VendorPaymentValidationIssue>,
): VendorPaymentValidationIssue {
  return { code, message, field: field ?? null, severity: 'ERROR', ...extras }
}

export function calcWarning(
  code: string,
  message: string,
  field?: string | null,
  extras?: Partial<VendorPaymentValidationIssue>,
): VendorPaymentValidationIssue {
  return { code, message, field: field ?? null, severity: 'WARNING', ...extras }
}

export function calcInfo(
  code: string,
  message: string,
  field?: string | null,
  extras?: Partial<VendorPaymentValidationIssue>,
): VendorPaymentValidationIssue {
  return { code, message, field: field ?? null, severity: 'INFO', ...extras }
}
