import { z } from 'zod'
import { paginationSchema } from '../../../utils/pagination.js'

export const HR_EMPLOYMENT_TYPES = ['PERMANENT', 'PROBATION', 'CONTRACT', 'TRAINEE', 'INTERN', 'TEMPORARY'] as const
export const HR_WORKER_CATEGORIES = ['STAFF', 'WORKER', 'SUPERVISOR', 'MANAGEMENT'] as const
export const HR_EMPLOYEE_STATUSES = ['DRAFT', 'ACTIVE', 'ON_NOTICE', 'INACTIVE', 'EXITED'] as const
export const HR_GENDERS = ['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'] as const
export const HR_DOCUMENT_TYPES = [
  'PHOTO',
  'PAN',
  'AADHAAR',
  'BANK_PROOF',
  'APPOINTMENT_LETTER',
  'EXPERIENCE',
  'QUALIFICATION',
  'SKILL_CERTIFICATE',
  'SALARY_REVISION',
  'OTHER',
] as const

export const createEmployeeSchema = z.object({
  legalEntityId: z.string().uuid(),
  branchId: z.string().uuid(),
  departmentId: z.string().uuid(),
  designationId: z.string().uuid(),
  primaryWorkCentreId: z.string().uuid().optional(),
  userId: z.string().uuid().optional(),

  firstName: z.string().trim().min(1).max(100),
  middleName: z.string().trim().max(100).optional(),
  lastName: z.string().trim().min(1).max(100),
  displayName: z.string().trim().max(220).optional(),

  mobile: z.string().trim().max(20).optional(),
  email: z.string().trim().email().max(255).optional(),
  dateOfBirth: z.string().optional(),
  gender: z.enum(HR_GENDERS).optional(),

  addressLine: z.string().trim().max(300).optional(),
  city: z.string().trim().max(100).optional(),
  state: z.string().trim().max(100).optional(),
  pin: z.string().trim().max(12).optional(),
  country: z.string().trim().max(100).optional(),

  joinDate: z.string(),
  employmentType: z.enum(HR_EMPLOYMENT_TYPES),
  workerCategory: z.enum(HR_WORKER_CATEGORIES),
  reportingManagerEmployeeId: z.string().uuid().optional(),
  defaultShiftId: z.string().uuid().optional(),
  weeklyOffDay: z.number().int().min(0).max(6).nullable().optional(),
  status: z.enum(HR_EMPLOYEE_STATUSES).optional().default('DRAFT'),
})

export const updateEmployeeSchema = z
  .object({
    legalEntityId: z.string().uuid().optional(),
    branchId: z.string().uuid().optional(),
    departmentId: z.string().uuid().optional(),
    designationId: z.string().uuid().optional(),
    primaryWorkCentreId: z.string().uuid().nullable().optional(),
    userId: z.string().uuid().nullable().optional(),

    firstName: z.string().trim().min(1).max(100).optional(),
    middleName: z.string().trim().max(100).nullable().optional(),
    lastName: z.string().trim().min(1).max(100).optional(),
    displayName: z.string().trim().max(220).optional(),

    mobile: z.string().trim().max(20).nullable().optional(),
    email: z.string().trim().email().max(255).nullable().optional(),
    dateOfBirth: z.string().nullable().optional(),
    gender: z.enum(HR_GENDERS).nullable().optional(),

    addressLine: z.string().trim().max(300).nullable().optional(),
    city: z.string().trim().max(100).nullable().optional(),
    state: z.string().trim().max(100).nullable().optional(),
    pin: z.string().trim().max(12).nullable().optional(),
    country: z.string().trim().max(100).nullable().optional(),

    joinDate: z.string().optional(),
    employmentType: z.enum(HR_EMPLOYMENT_TYPES).optional(),
    workerCategory: z.enum(HR_WORKER_CATEGORIES).optional(),
    reportingManagerEmployeeId: z.string().uuid().nullable().optional(),
    defaultShiftId: z.string().uuid().nullable().optional(),
    weeklyOffDay: z.number().int().min(0).max(6).nullable().optional(),
    status: z.enum(HR_EMPLOYEE_STATUSES).optional(),
    /** Reason recorded against the employment-history rows generated by this update. */
    reason: z.string().trim().max(500).optional(),
  })
  .refine((data) => Object.keys(data).filter((k) => k !== 'reason').length > 0, {
    message: 'At least one field is required',
  })

export const listEmployeesQuerySchema = paginationSchema.extend({
  status: z.enum(HR_EMPLOYEE_STATUSES).optional(),
  legalEntityId: z.string().uuid().optional(),
  branchId: z.string().uuid().optional(),
  departmentId: z.string().uuid().optional(),
  designationId: z.string().uuid().optional(),
  employmentType: z.enum(HR_EMPLOYMENT_TYPES).optional(),
  workerCategory: z.enum(HR_WORKER_CATEGORIES).optional(),
})

export const employeeIdParamSchema = z.object({
  tenantId: z.string().uuid().optional(),
  tenantSlug: z.string().min(2).max(100).optional(),
  employeeId: z.string().uuid(),
})

export const employeeBankIdParamSchema = employeeIdParamSchema.extend({
  bankId: z.string().uuid(),
})

export const employeeDocumentIdParamSchema = employeeIdParamSchema.extend({
  documentId: z.string().uuid(),
})

export const createBankDetailSchema = z.object({
  bankName: z.string().trim().min(1).max(150),
  accountHolderName: z.string().trim().min(1).max(150),
  accountNumber: z.string().trim().min(4).max(34),
  ifsc: z.string().trim().min(4).max(11),
  isPrimary: z.boolean().optional().default(false),
  effectiveFrom: z.string().optional(),
  effectiveTo: z.string().optional(),
})

export const updateBankDetailSchema = z
  .object({
    bankName: z.string().trim().min(1).max(150).optional(),
    accountHolderName: z.string().trim().min(1).max(150).optional(),
    accountNumber: z.string().trim().min(4).max(34).optional(),
    ifsc: z.string().trim().min(4).max(11).optional(),
    isPrimary: z.boolean().optional(),
    effectiveFrom: z.string().nullable().optional(),
    effectiveTo: z.string().nullable().optional(),
  })
  .refine((data) => Object.keys(data).length > 0, { message: 'At least one field is required' })

export const upsertStatutoryDetailSchema = z.object({
  pan: z.string().trim().max(10).optional().nullable(),
  aadhaarRef: z.string().trim().max(64).optional().nullable(),
  uan: z.string().trim().max(20).optional().nullable(),
  esicNumber: z.string().trim().max(30).optional().nullable(),
})

export const uploadDocumentMetaSchema = z.object({
  documentType: z.enum(HR_DOCUMENT_TYPES).default('OTHER'),
  notes: z.string().trim().max(500).optional(),
})

export type CreateEmployeeInput = z.infer<typeof createEmployeeSchema>
export type UpdateEmployeeInput = z.infer<typeof updateEmployeeSchema>
export type ListEmployeesQuery = z.infer<typeof listEmployeesQuerySchema>
export type CreateBankDetailInput = z.infer<typeof createBankDetailSchema>
export type UpdateBankDetailInput = z.infer<typeof updateBankDetailSchema>
export type UpsertStatutoryDetailInput = z.infer<typeof upsertStatutoryDetailSchema>
export type UploadDocumentMeta = z.infer<typeof uploadDocumentMetaSchema>
