import type { ReportColumn, ReportDefinition } from './types.js'

const COMMON_FILTERS = ['dateFrom', 'dateTo', 'plantCode', 'page', 'pageSize', 'sortBy', 'sortDir', 'search']

function col(key: string, label: string, type: ReportColumn['type'] = 'string', extra: Partial<ReportColumn> = {}): ReportColumn {
  return { key, label, type, sortable: true, ...extra }
}

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    key: 'production-control',
    name: 'Production Control Tower',
    module: 'PRODUCTION',
    description: 'Work order KPIs, health breakdown, and the attention list of orders needing action.',
    permission: 'manufacturing.reports.production',
    filters: [...COMMON_FILTERS, 'status', 'productItemId', 'supervisorId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('productItemCode', 'Item Code'),
      col('productItemName', 'Item Name'),
      col('status', 'Status'),
      col('healthStatus', 'Health'),
      col('plannedQuantity', 'Planned Qty', 'number'),
      col('completedGoodQuantity', 'Completed Qty', 'number'),
      col('requiredCompletionDate', 'Due Date', 'date'),
      col('overdue', 'Overdue', 'boolean'),
      col('materialControlStatus', 'Material Status'),
      col('qualityStatus', 'Quality Status'),
    ],
    defaultColumns: ['orderNumber', 'productItemCode', 'status', 'healthStatus', 'plannedQuantity', 'completedGoodQuantity', 'requiredCompletionDate', 'overdue'],
    exportSupported: true,
    dateBasis: 'requiredCompletionDate',
    calculationNotes: 'Attention list = open work orders (not COMPLETED/CLOSED/CANCELLED) that are overdue OR have healthStatus != ON_TRACK. No OEE, no cost.',
    availability: 'READY',
  },
  {
    key: 'shopfloor-live',
    name: 'Shopfloor Live Board',
    module: 'PRODUCTION',
    description: 'Currently active stages across the shop floor — work centre, machine, operator, health. Auto-refresh view.',
    permission: 'manufacturing.reports.shopfloor',
    filters: ['plantCode', 'workCentreId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('productItemCode', 'Item Code'),
      col('priority', 'Priority'),
      col('stageName', 'Stage'),
      col('workCentre', 'Work Centre'),
      col('machine', 'Machine'),
      col('activeAssignmentCount', 'Active Assignments', 'number'),
      col('openIssueCount', 'Open Issues', 'number'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('plannedQuantity', 'Planned Qty', 'number'),
      col('healthStatus', 'Health'),
      col('startedAt', 'Started At', 'datetime'),
      col('totalDowntimeMinutes', 'Downtime (min)', 'number'),
    ],
    defaultColumns: ['orderNumber', 'stageName', 'workCentre', 'machine', 'goodQuantity', 'plannedQuantity', 'healthStatus'],
    exportSupported: true,
    dateBasis: 'startedAt',
    calculationNotes: 'Stages currently IN_PROGRESS. No OEE or capacity-utilisation figures are computed. Suggested client refresh: 30s.',
    availability: 'READY',
  },
  {
    key: 'shift-dashboard',
    name: 'Shift Production Dashboard',
    module: 'PRODUCTION',
    description: 'Daily production batches grouped by shift, with good/rework/rejected/scrap totals.',
    permission: 'manufacturing.reports.shift',
    filters: [...COMMON_FILTERS, 'shift', 'workCentreId', 'supervisorId'],
    columns: [
      col('batchNumber', 'Batch #'),
      col('productionDate', 'Date', 'date'),
      col('shiftCode', 'Shift'),
      col('workCentre', 'Work Centre'),
      col('status', 'Status'),
      col('lineCount', 'Lines', 'number'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('reworkQuantity', 'Rework Qty', 'number'),
      col('rejectedQuantity', 'Rejected Qty', 'number'),
      col('scrapQuantity', 'Scrap Qty', 'number'),
    ],
    defaultColumns: ['batchNumber', 'productionDate', 'shiftCode', 'workCentre', 'goodQuantity', 'rejectedQuantity'],
    exportSupported: true,
    dateBasis: 'productionDate',
    calculationNotes: 'Aggregated from DailyProductionBatch + DailyProductionLine. Batches without shiftCode are grouped under UNASSIGNED.',
    availability: 'READY',
  },
  {
    key: 'work-order-progress',
    name: 'Work Order Progress',
    module: 'PRODUCTION',
    description: 'Per work-order progress: planned vs completed quantity and stage completion.',
    permission: 'manufacturing.reports.production',
    filters: [...COMMON_FILTERS, 'status', 'productItemId', 'workOrderId', 'workCentreId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('productItemCode', 'Item Code'),
      col('status', 'Status'),
      col('healthStatus', 'Health'),
      col('plannedQuantity', 'Planned Qty', 'number'),
      col('completedGoodQuantity', 'Completed Qty', 'number'),
      col('reworkQuantity', 'Rework Qty', 'number'),
      col('rejectedQuantity', 'Rejected Qty', 'number'),
      col('scrapQuantity', 'Scrap Qty', 'number'),
      col('completionPercent', 'Completion %', 'percent'),
      col('stagesTotal', 'Stages Total', 'number'),
      col('stagesCompleted', 'Stages Completed', 'number'),
      col('requiredCompletionDate', 'Due Date', 'date'),
    ],
    defaultColumns: ['orderNumber', 'productItemCode', 'status', 'plannedQuantity', 'completedGoodQuantity', 'completionPercent', 'requiredCompletionDate'],
    exportSupported: true,
    dateBasis: 'requiredCompletionDate',
    calculationNotes: 'completionPercent taken from ProductionOrder.completionPercent (maintained by the stage-ledger posting engine).',
    availability: 'READY',
  },
  {
    key: 'plan-vs-actual',
    name: 'Plan vs Actual',
    module: 'PRODUCTION',
    description: 'Production plan lines (PLANNED/WORK_ORDERS_CREATED/CLOSED) vs actual completed quantity.',
    permission: 'manufacturing.reports.production',
    filters: [...COMMON_FILTERS, 'productItemId'],
    columns: [
      col('planNumber', 'Plan #'),
      col('planName', 'Plan Name'),
      col('planStatus', 'Plan Status'),
      col('productItemCode', 'Item Code'),
      col('demandQuantity', 'Demand Qty', 'number'),
      col('suggestedQuantity', 'Suggested Qty', 'number'),
      col('actualCompletedQuantity', 'Actual Completed Qty', 'number'),
      col('variance', 'Variance', 'number'),
      col('requiredDate', 'Required Date', 'date'),
      col('workOrderLinked', 'WO Linked', 'boolean'),
    ],
    defaultColumns: ['planNumber', 'productItemCode', 'demandQuantity', 'actualCompletedQuantity', 'variance', 'requiredDate'],
    exportSupported: true,
    dateBasis: 'requiredDate',
    calculationNotes: 'Only plans with status PLANNED, WORK_ORDERS_CREATED, or CLOSED are included (DRAFT/CANCELLED excluded). actualCompletedQuantity is the linked ProductionOrder.completedGoodQuantity; lines without a linked work order show 0 with a warning.',
    availability: 'READY',
  },
  {
    key: 'stage-performance',
    name: 'Stage Performance',
    module: 'PRODUCTION',
    description: 'Cycle time and output quality by routing stage.',
    permission: 'manufacturing.reports.work_centres',
    filters: [...COMMON_FILTERS, 'workCentreId'],
    columns: [
      col('stageCode', 'Stage Code'),
      col('stageName', 'Stage Name'),
      col('workCentre', 'Work Centre'),
      col('completedCount', 'Completed', 'number'),
      col('avgCycleTimeMinutes', 'Avg Cycle Time (min)', 'number'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('reworkQuantity', 'Rework Qty', 'number'),
      col('rejectedQuantity', 'Rejected Qty', 'number'),
      col('scrapQuantity', 'Scrap Qty', 'number'),
    ],
    defaultColumns: ['stageCode', 'stageName', 'workCentre', 'completedCount', 'avgCycleTimeMinutes', 'goodQuantity'],
    exportSupported: true,
    dateBasis: 'completedAt',
    calculationNotes: 'Cycle time = completedAt - startedAt for COMPLETED stages in range. Grouped by stage code + work centre. No OEE.',
    availability: 'READY',
  },
  {
    key: 'work-centre-performance',
    name: 'Work Centre Performance',
    module: 'PRODUCTION',
    description: 'Throughput and downtime by work centre (no OEE/capacity-utilisation).',
    permission: 'manufacturing.reports.work_centres',
    filters: [...COMMON_FILTERS, 'workCentreId'],
    columns: [
      col('workCentreCode', 'Work Centre Code'),
      col('workCentreName', 'Work Centre Name'),
      col('activeStages', 'Active Stages', 'number'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('reworkQuantity', 'Rework Qty', 'number'),
      col('rejectedQuantity', 'Rejected Qty', 'number'),
      col('downtimeMinutes', 'Downtime (min)', 'number'),
      col('downtimeEvents', 'Downtime Events', 'number'),
    ],
    defaultColumns: ['workCentreCode', 'workCentreName', 'goodQuantity', 'downtimeMinutes', 'downtimeEvents'],
    exportSupported: true,
    dateBasis: 'createdAt',
    calculationNotes: 'Throughput from DailyProductionLine, downtime from ProductionDowntime. Deliberately excludes OEE/availability/performance/quality-factor calculations (not in scope for Phase 7D).',
    availability: 'READY',
  },
  {
    key: 'work-centre-oee',
    name: 'Work Centre OEE',
    module: 'PRODUCTION',
    description: 'Availability, performance, quality, and OEE by active work centre.',
    permission: 'manufacturing.reports.work_centres',
    filters: [...COMMON_FILTERS, 'workCentreId'],
    columns: [
      col('workCentreCode', 'Work Centre Code'),
      col('workCentreName', 'Work Centre Name'),
      col('plannedMinutes', 'Planned Minutes', 'number'),
      col('downtimeMinutes', 'Downtime Minutes', 'number'),
      col('actualMachineMinutes', 'Machine Minutes', 'number'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('scrapQuantity', 'Scrap Qty', 'number'),
      col('rejectedQuantity', 'Rejected Qty', 'number'),
      col('availabilityPercent', 'Availability %', 'percent'),
      col('performancePercent', 'Performance %', 'percent'),
      col('qualityPercent', 'Quality %', 'percent'),
      col('oeePercent', 'OEE %', 'percent'),
    ],
    defaultColumns: [
      'workCentreCode',
      'plannedMinutes',
      'downtimeMinutes',
      'availabilityPercent',
      'performancePercent',
      'qualityPercent',
      'oeePercent',
    ],
    exportSupported: true,
    dateBasis: 'Daily production / downtime date',
    calculationNotes:
      'Availability=(plannedMinutes-downtimeMinutes)/plannedMinutes; plannedMinutes=shiftMinutesPerDay×daysInRange×workCentreCount. ' +
      'Performance=(idealCycleMinutes×goodQty)/actualMachineMinutes. Quality=goodQty/(goodQty+scrapQty+rejectedQty). OEE=A×P×Q. ' +
      'Returns no rows with an explanatory warning while ManufacturingSettings.oeeEnabled is false.',
    availability: 'PARTIAL',
  },
  {
    key: 'issues-downtime',
    name: 'Issues & Downtime',
    module: 'PRODUCTION',
    description: 'Production issues with linked downtime duration.',
    permission: 'manufacturing.reports.downtime',
    filters: [...COMMON_FILTERS, 'status', 'severity', 'workCentreId'],
    columns: [
      col('issueNumber', 'Issue #'),
      col('orderNumber', 'Order #'),
      col('issueType', 'Type'),
      col('severity', 'Severity'),
      col('status', 'Status'),
      col('title', 'Title'),
      col('startedAt', 'Started At', 'datetime'),
      col('resolvedAt', 'Resolved At', 'datetime'),
      col('actualDowntimeMinutes', 'Downtime (min)', 'number'),
      col('productionBlocked', 'Blocked Production', 'boolean'),
    ],
    defaultColumns: ['issueNumber', 'orderNumber', 'issueType', 'severity', 'status', 'actualDowntimeMinutes'],
    exportSupported: true,
    dateBasis: 'startedAt',
    calculationNotes: 'One row per ProductionIssue; actualDowntimeMinutes falls back to the sum of linked ProductionDowntime.durationMinutes when the issue field itself is null.',
    availability: 'READY',
  },
  {
    key: 'material-readiness',
    name: 'Material Readiness',
    module: 'MATERIALS',
    description: 'Material requirement lines by readiness (required vs reserved vs issued vs shortage).',
    permission: 'manufacturing.reports.materials',
    filters: [...COMMON_FILTERS, 'status', 'workOrderId', 'warehouseId', 'productItemId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('itemCode', 'Item Code'),
      col('itemName', 'Item Name'),
      col('warehouse', 'Warehouse'),
      col('requiredQty', 'Required Qty', 'number'),
      col('reservedQty', 'Reserved Qty', 'number'),
      col('issuedQty', 'Issued Qty', 'number'),
      col('shortageQty', 'Shortage Qty', 'number'),
      col('status', 'Line Status'),
    ],
    defaultColumns: ['orderNumber', 'itemCode', 'requiredQty', 'issuedQty', 'shortageQty', 'status'],
    exportSupported: true,
    dateBasis: 'createdAt',
    calculationNotes: 'One row per ProductionOrderMaterial line for open (not CLOSED/CANCELLED) work orders.',
    availability: 'READY',
  },
  {
    key: 'material-reconciliation',
    name: 'Material Reconciliation',
    module: 'MATERIALS',
    description: 'Per work-order material reconciliation status (reused from the close-readiness reconciliation engine).',
    permission: 'manufacturing.reports.materials',
    filters: [...COMMON_FILTERS, 'workOrderId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('status', 'Reconciliation Status'),
      col('canClose', 'Can Close', 'boolean'),
      col('differenceCount', 'Differences', 'number'),
      col('blockerCount', 'Blockers', 'number'),
      col('heldLineCount', 'Held Lines', 'number'),
    ],
    defaultColumns: ['orderNumber', 'status', 'canClose', 'differenceCount', 'blockerCount'],
    exportSupported: true,
    dateBasis: 'createdAt',
    calculationNotes: 'Reuses material-position.service/material-reconciliation.service (Phase 7A) per work order — bounded to the 200 most recently updated open/on-hold work orders per query.',
    availability: 'READY',
  },
  {
    key: 'wip-position',
    name: 'WIP Position',
    module: 'WIP',
    description: 'Current work-in-progress custody (issued material not yet consumed/returned) by work order and item.',
    permission: 'manufacturing.reports.wip',
    filters: [...COMMON_FILTERS, 'workOrderId', 'productItemId', 'warehouseId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('itemCode', 'Item Code'),
      col('itemName', 'Item Name'),
      col('warehouse', 'Warehouse'),
      col('issuedQty', 'Issued Qty', 'number'),
      col('returnedQty', 'Returned Qty', 'number'),
      col('wipQuantity', 'WIP Qty', 'number'),
      col('status', 'Line Status'),
    ],
    defaultColumns: ['orderNumber', 'itemCode', 'issuedQty', 'returnedQty', 'wipQuantity'],
    exportSupported: true,
    dateBasis: 'updatedAt',
    calculationNotes: 'wipQuantity = issuedQty - returnedQty (custody still with the work order) for open work orders. No parallel stock ledger — Inventory remains SoT for physical stock.',
    availability: 'READY',
  },
  {
    key: 'wip-ageing',
    name: 'WIP Ageing',
    module: 'WIP',
    description: 'Age buckets (0-1, 2-3, 4-7, 8-15, 16-30, 30+ days) of in-progress stages holding WIP.',
    permission: 'manufacturing.reports.wip',
    filters: [...COMMON_FILTERS, 'workCentreId'],
    columns: [
      col('orderNumber', 'Order #'),
      col('stageName', 'Stage'),
      col('workCentre', 'Work Centre'),
      col('ageDays', 'Age (days)', 'number'),
      col('ageBucket', 'Age Bucket'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('ageSource', 'Age Source'),
    ],
    defaultColumns: ['orderNumber', 'stageName', 'ageDays', 'ageBucket'],
    exportSupported: true,
    dateBasis: 'startedAt',
    calculationNotes: 'Age = now - stage.startedAt (falls back to stage.updatedAt with a warning when startedAt is null) for stages currently IN_PROGRESS/ON_HOLD. Buckets: 0-1,2-3,4-7,8-15,16-30,30+.',
    availability: 'READY',
  },
  {
    key: 'job-work-ageing',
    name: 'Job Work Ageing',
    module: 'JOB_WORK',
    description: 'Age buckets of open job work orders (material out with the subcontractor).',
    permission: 'manufacturing.reports.job_work',
    filters: [...COMMON_FILTERS, 'vendorId'],
    columns: [
      col('jwNumber', 'JW #'),
      col('vendor', 'Vendor'),
      col('processName', 'Process'),
      col('status', 'Status'),
      col('ageDays', 'Age (days)', 'number'),
      col('ageBucket', 'Age Bucket'),
      col('sentQty', 'Sent Qty', 'number'),
      col('receivedQty', 'Received Qty', 'number'),
    ],
    defaultColumns: ['jwNumber', 'vendor', 'status', 'ageDays', 'ageBucket'],
    exportSupported: true,
    dateBasis: 'materialSentAt',
    calculationNotes: 'Age = now - materialSentAt (falls back to createdAt) for job work orders not CLOSED/CANCELLED. Buckets: 0-1,2-3,4-7,8-15,16-30,30+.',
    availability: 'READY',
  },
  {
    key: 'job-work-reconciliation',
    name: 'Job Work Reconciliation',
    module: 'JOB_WORK',
    description: 'Sent vs received/accepted/rejected/rework quantity variance per job work order.',
    permission: 'manufacturing.reports.job_work',
    filters: [...COMMON_FILTERS, 'vendorId', 'status'],
    columns: [
      col('jwNumber', 'JW #'),
      col('vendor', 'Vendor'),
      col('status', 'Status'),
      col('sentQty', 'Sent Qty', 'number'),
      col('receivedQty', 'Received Qty', 'number'),
      col('acceptedQty', 'Accepted Qty', 'number'),
      col('rejectedQty', 'Rejected Qty', 'number'),
      col('reworkQty', 'Rework Qty', 'number'),
      col('outstandingQty', 'Outstanding Qty', 'number'),
      col('differenceApproved', 'Difference Approved', 'boolean'),
    ],
    defaultColumns: ['jwNumber', 'vendor', 'sentQty', 'receivedQty', 'outstandingQty', 'status'],
    exportSupported: true,
    dateBasis: 'materialSentAt',
    calculationNotes: 'outstandingQty = sentQty - receivedQty (material still with vendor). RECONCILIATION_PENDING status highlighted.',
    availability: 'READY',
  },
  {
    key: 'quality-dashboard',
    name: 'Quality Dashboard',
    module: 'QUALITY',
    description: 'Inspection and NCR counts by status/severity with trend chart.',
    permission: 'quality.reports.view',
    filters: [...COMMON_FILTERS, 'qualityStatus', 'severity'],
    columns: [
      col('category', 'Category'),
      col('status', 'Status'),
      col('count', 'Count', 'number'),
    ],
    defaultColumns: ['category', 'status', 'count'],
    exportSupported: true,
    dateBasis: 'requestedAt',
    calculationNotes: 'Counts of QualityInspection grouped by category/status and QualityNcr grouped by severity/status within the date range.',
    availability: 'READY',
  },
  {
    key: 'quality-inspections',
    name: 'Quality Inspections',
    module: 'QUALITY',
    description: 'Inspection register with decision and disposition.',
    permission: 'quality.reports.view',
    filters: [...COMMON_FILTERS, 'qualityStatus', 'productItemId', 'workOrderId'],
    columns: [
      col('inspectionNumber', 'Inspection #'),
      col('category', 'Category'),
      col('status', 'Status'),
      col('decision', 'Decision'),
      col('itemCode', 'Item Code'),
      col('orderNumber', 'Order #'),
      col('inspectedQty', 'Inspected Qty', 'number'),
      col('acceptedQty', 'Accepted Qty', 'number'),
      col('rejectedQty', 'Rejected Qty', 'number'),
      col('reworkQty', 'Rework Qty', 'number'),
      col('requestedAt', 'Requested At', 'datetime'),
      col('decidedAt', 'Decided At', 'datetime'),
    ],
    defaultColumns: ['inspectionNumber', 'category', 'status', 'decision', 'itemCode', 'requestedAt'],
    exportSupported: true,
    dateBasis: 'requestedAt',
    calculationNotes: 'One row per QualityInspection in range.',
    availability: 'READY',
  },
  {
    key: 'production-quality',
    name: 'Production Quality / First-Pass Yield',
    module: 'QUALITY',
    description: 'First-pass yield by item: accepted quantity vs total inspected quantity.',
    permission: 'quality.reports.production',
    filters: [...COMMON_FILTERS, 'productItemId'],
    columns: [
      col('itemCode', 'Item Code'),
      col('itemName', 'Item Name'),
      col('inspectedQty', 'Inspected Qty', 'number'),
      col('acceptedQty', 'Accepted Qty', 'number'),
      col('reworkQty', 'Rework Qty', 'number'),
      col('rejectedQty', 'Rejected Qty', 'number'),
      col('firstPassYieldPercent', 'First-Pass Yield %', 'percent'),
    ],
    defaultColumns: ['itemCode', 'inspectedQty', 'acceptedQty', 'firstPassYieldPercent'],
    exportSupported: true,
    dateBasis: 'requestedAt',
    calculationNotes:
      'firstPassYieldPercent = acceptedQty / inspectedQty * 100, aggregated per item from QualityInspection.decidedAt in range. ' +
      'The schema records the accepted/rework/rejected split at decision time but does not track whether an accepted unit passed on the ' +
      'first attempt without any prior rework loop, so this is a "decision-based" first-pass yield (accepted-at-decision ÷ inspected), not a ' +
      'strict rework-excluded first-pass yield. Treat as directional, not audit-grade.',
    availability: 'PARTIAL',
  },
  {
    key: 'ncr-register',
    name: 'NCR Register',
    module: 'QUALITY',
    description: 'Non-conformance report register with disposition and closure status.',
    permission: 'quality.reports.ncr',
    filters: [...COMMON_FILTERS, 'status', 'severity', 'productItemId'],
    columns: [
      col('ncrNumber', 'NCR #'),
      col('title', 'Title'),
      col('status', 'Status'),
      col('severity', 'Severity'),
      col('disposition', 'Disposition'),
      col('orderNumber', 'Order #'),
      col('itemCode', 'Item Code'),
      col('targetDate', 'Target Date', 'date'),
      col('closedAt', 'Closed At', 'datetime'),
      col('ageDays', 'Age (days)', 'number'),
    ],
    defaultColumns: ['ncrNumber', 'title', 'status', 'severity', 'targetDate', 'ageDays'],
    exportSupported: true,
    dateBasis: 'createdAt',
    calculationNotes: 'ageDays = now - createdAt for open NCRs; closed NCRs show age at closure.',
    availability: 'READY',
  },
  {
    key: 'rework-rejection',
    name: 'Rework & Rejection Analysis',
    module: 'QUALITY',
    description: 'Rework/rejected/scrap quantity by item and stage.',
    permission: 'quality.reports.production',
    filters: [...COMMON_FILTERS, 'productItemId', 'workCentreId'],
    columns: [
      col('itemCode', 'Item Code'),
      col('stageName', 'Stage'),
      col('goodQuantity', 'Good Qty', 'number'),
      col('reworkQuantity', 'Rework Qty', 'number'),
      col('rejectedQuantity', 'Rejected Qty', 'number'),
      col('scrapQuantity', 'Scrap Qty', 'number'),
      col('reworkRatePercent', 'Rework Rate %', 'percent'),
      col('rejectionRatePercent', 'Rejection Rate %', 'percent'),
    ],
    defaultColumns: ['itemCode', 'stageName', 'goodQuantity', 'reworkQuantity', 'rejectedQuantity', 'rejectionRatePercent'],
    exportSupported: true,
    dateBasis: 'updatedAt',
    calculationNotes: 'Aggregated from ProductionOrderStage totals grouped by product item + stage name. Rates computed against (good+rework+rejected+scrap).',
    availability: 'READY',
  },
  {
    key: 'dispatch-readiness',
    name: 'Dispatch Readiness',
    module: 'DISPATCH',
    description: 'Open sales order lines vs quantity already dispatched (Phase 7C0 fulfilment ledger).',
    permission: 'dispatch.reports.view',
    filters: [...COMMON_FILTERS, 'customerId', 'salesOrderId'],
    columns: [
      col('salesOrderNo', 'SO #'),
      col('customer', 'Customer'),
      col('lineNo', 'Line', 'number'),
      col('orderedQty', 'Ordered Qty', 'number'),
      col('dispatchedQty', 'Dispatched Qty', 'number'),
      col('cancelledQty', 'Cancelled Qty', 'number'),
      col('remainingQty', 'Remaining Qty', 'number'),
      col('readyToDispatch', 'Ready To Dispatch', 'boolean'),
    ],
    defaultColumns: ['salesOrderNo', 'customer', 'orderedQty', 'dispatchedQty', 'remainingQty'],
    exportSupported: true,
    dateBasis: 'orderDate',
    calculationNotes:
      'orderedQty/dispatchedQty computed from CrmSalesOrder.lines JSON + confirmed OutboundDispatchLine + SalesOrderLineFulfilment.cancelledQty (Dispatch Phase 7C0 — no pick/pack/challan). ' +
      'FG stock availability is NOT joined: SO lines reference master products while dispatch lines reference master items, and there is no reliable mapping between them yet — readyToDispatch only reflects remainingQty > 0, not physical stock.',
    availability: 'READY',
  },
  {
    key: 'sales-order-fulfilment',
    name: 'Sales Order Fulfilment',
    module: 'DISPATCH',
    description: 'Per sales-order fulfilment percentage from confirmed dispatches.',
    permission: 'dispatch.reports.fulfilment',
    filters: [...COMMON_FILTERS, 'customerId', 'status'],
    columns: [
      col('salesOrderNo', 'SO #'),
      col('customer', 'Customer'),
      col('status', 'SO Status'),
      col('orderedQty', 'Ordered Qty', 'number'),
      col('dispatchedQty', 'Dispatched Qty', 'number'),
      col('fulfilmentPercent', 'Fulfilment %', 'percent'),
      col('orderDate', 'Order Date', 'date'),
    ],
    defaultColumns: ['salesOrderNo', 'customer', 'orderedQty', 'dispatchedQty', 'fulfilmentPercent'],
    exportSupported: true,
    dateBasis: 'orderDate',
    calculationNotes: 'fulfilmentPercent = dispatchedQty / orderedQty * 100, from CONFIRMED OutboundDispatch lines linked by salesOrderId.',
    availability: 'READY',
  },
  {
    key: 'dispatch-performance',
    name: 'Dispatch Performance',
    module: 'DISPATCH',
    description: 'Confirmed dispatch volume and lead time trend.',
    permission: 'dispatch.reports.view',
    filters: [...COMMON_FILTERS, 'dispatchStatus'],
    columns: [
      col('dispatchNo', 'Dispatch #'),
      col('salesOrderNo', 'SO #'),
      col('status', 'Status'),
      col('confirmedAt', 'Confirmed At', 'datetime'),
      col('lineCount', 'Lines', 'number'),
      col('totalQty', 'Total Qty', 'number'),
      col('leadTimeDays', 'Lead Time (days)', 'number'),
    ],
    defaultColumns: ['dispatchNo', 'salesOrderNo', 'status', 'confirmedAt', 'totalQty'],
    exportSupported: true,
    dateBasis: 'confirmedAt',
    calculationNotes: 'leadTimeDays = dispatch.confirmedAt - salesOrder.orderDate, only when the dispatch is linked to a sales order.',
    availability: 'READY',
  },
  {
    key: 'invoice-readiness',
    name: 'Invoice Readiness',
    module: 'DISPATCH',
    description: 'Confirmed dispatches with quantity not yet invoiced (dispatch minus ACTIVE source-link consumption).',
    permission: 'dispatch.reports.invoice_readiness',
    filters: [...COMMON_FILTERS, 'customerId', 'salesOrderId'],
    columns: [
      col('dispatchNo', 'Dispatch #'),
      col('salesOrderNo', 'SO #'),
      col('customer', 'Customer'),
      col('confirmedAt', 'Confirmed At', 'datetime'),
      col('totalQty', 'Dispatched Qty', 'number'),
      col('invoicedQty', 'Invoiced Qty', 'number'),
      col('invoiceReadyQty', 'Invoice-Ready Qty', 'number'),
      col('invoiceReady', 'Invoice Ready', 'boolean'),
    ],
    defaultColumns: ['dispatchNo', 'salesOrderNo', 'confirmedAt', 'invoiceReadyQty', 'invoiceReady'],
    exportSupported: true,
    dateBasis: 'confirmedAt',
    calculationNotes:
      'Invoice-Ready Qty = Confirmed Dispatched Qty − ACTIVE SalesInvoiceSourceLink consumption (OUTBOUND_DISPATCH). ' +
      'Rows with invoiceReadyQty <= 0 are excluded. No invoice document is created here.',
    availability: 'READY',
    unavailableReason: undefined,
  },
  {
    key: 'revenue-bridge',
    name: 'O2C Revenue Bridge',
    module: 'DISPATCH',
    description: 'Ordered → Dispatched → Invoiced → Collected amounts per sales order.',
    permission: 'dispatch.reports.fulfilment',
    filters: [...COMMON_FILTERS, 'customerId', 'salesOrderId'],
    columns: [
      col('salesOrderNo', 'SO #'),
      col('customer', 'Customer'),
      col('orderDate', 'Order Date', 'date'),
      col('orderedAmount', 'Ordered', 'currency'),
      col('dispatchedAmount', 'Dispatched', 'currency'),
      col('invoicedAmount', 'Invoiced', 'currency'),
      col('collectedAmount', 'Collected', 'currency'),
      col('dispatchGap', 'Dispatch Gap', 'currency'),
      col('invoiceGap', 'Invoice Gap', 'currency'),
      col('collectionGap', 'Collection Gap', 'currency'),
    ],
    defaultColumns: ['salesOrderNo', 'customer', 'orderedAmount', 'dispatchedAmount', 'invoicedAmount', 'collectedAmount'],
    exportSupported: true,
    dateBasis: 'orderDate',
    calculationNotes:
      'orderedAmount from SO header/lines; dispatchedAmount = ordered × fulfilment ratio; invoicedAmount from POSTED sales invoices linked to the SO; ' +
      'collectedAmount from POSTED customer receipt allocations on those invoices.',
    availability: 'READY',
  },
  {
    key: 'collection-due-today',
    name: 'Collection Due Today',
    module: 'DISPATCH',
    description: 'Open receivable invoice balances with due date equal to today (tenant timezone).',
    permission: 'dispatch.reports.view',
    filters: ['customerId', 'legalEntityId', 'page', 'pageSize', 'sortBy', 'sortDir', 'search'],
    columns: [
      col('invoiceNumber', 'Invoice #'),
      col('customer', 'Customer'),
      col('dueDate', 'Due Date', 'date'),
      col('openAmount', 'Open Amount', 'currency'),
      col('currencyCode', 'Currency'),
    ],
    defaultColumns: ['invoiceNumber', 'customer', 'dueDate', 'openAmount'],
    exportSupported: true,
    dateBasis: 'dueDate',
    calculationNotes:
      'Debit-side receivable open items with openAmount > 0 and dueDate = today in tenant timezone. ' +
      'Complements AR outstanding reports with an O2C ops workbench slice.',
    availability: 'READY',
  },
  {
    key: 'delivery-challans',
    name: 'Delivery Challans',
    module: 'DISPATCH',
    description: 'Delivery challan register (not implemented — Dispatch is Phase 7C0 thin-slice only).',
    permission: 'dispatch.reports.view',
    filters: COMMON_FILTERS,
    columns: [col('challanNo', 'Challan #'), col('status', 'Status')],
    defaultColumns: ['challanNo', 'status'],
    exportSupported: false,
    dateBasis: 'n/a',
    calculationNotes: 'Not computed — no DeliveryChallan model exists in this build.',
    availability: 'UNAVAILABLE',
    unavailableReason:
      'Delivery challans are not implemented. Dispatch Phase 7C0 only ships OutboundDispatch + SalesOrderLineFulfilment (no DeliveryChallan/DispatchRequirement/pick-pack). Use "Dispatch Readiness" or "Sales Order Fulfilment" instead.',
  },
  {
    key: 'supplier-quality',
    name: 'Supplier Quality',
    module: 'QUALITY',
    description: 'Incoming/supplier quality register (not implemented — no GRN module).',
    permission: 'quality.reports.view',
    filters: COMMON_FILTERS,
    columns: [col('vendorCode', 'Vendor Code'), col('status', 'Status')],
    defaultColumns: ['vendorCode', 'status'],
    exportSupported: false,
    dateBasis: 'n/a',
    calculationNotes: 'Not computed — no GRN / incoming-inspection model exists in this build.',
    availability: 'UNAVAILABLE',
    unavailableReason:
      'Supplier/incoming quality is not implemented. There is no GRN module in this build, so there is no incoming-inspection source data to report on.',
  },
]

export function findReportDefinition(key: string): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find((d) => d.key === key)
}
