export const NOTIFICATION_TYPES_UI = [
  { type: 'LEAD_ASSIGNED', label: 'Lead assigned', mandatory: false },
  { type: 'LEAD_UNATTENDED', label: 'Lead not contacted', mandatory: true },
  { type: 'OPPORTUNITY_ASSIGNED', label: 'Opportunity assigned', mandatory: false },
  { type: 'OPPORTUNITY_STAGE_CHANGED', label: 'Opportunity stage change', mandatory: false },
  { type: 'FOLLOW_UP_DUE', label: 'Follow-up due today', mandatory: false },
  { type: 'FOLLOW_UP_OVERDUE', label: 'Follow-up overdue', mandatory: true },
  { type: 'ACTIVITY_ASSIGNED', label: 'Activity assigned', mandatory: false },
  { type: 'OPPORTUNITY_INACTIVE', label: 'Opportunity inactive', mandatory: false },
  { type: 'OPPORTUNITY_CLOSE_DATE_MISSED', label: 'Close date missed', mandatory: true },
  { type: 'QUOTATION_APPROVAL_REQUESTED', label: 'Quotation approval', mandatory: true },
  { type: 'QUOTATION_APPROVED', label: 'Quotation approved', mandatory: false },
  { type: 'QUOTATION_REJECTED', label: 'Quotation rejected', mandatory: true },
  { type: 'QUOTATION_EXPIRING', label: 'Quotation expiring', mandatory: false },
  { type: 'QUOTATION_ACCEPTED_AWAITING_SO', label: 'Accepted quote awaiting SO', mandatory: false },
  { type: 'INTEGRATION_SYNC_FAILED', label: 'CRM integration failure', mandatory: true },
  { type: 'PR_PENDING_APPROVAL', label: 'PR pending approval', mandatory: true },
  { type: 'PO_PENDING_APPROVAL', label: 'PO pending approval', mandatory: true },
  { type: 'RFQ_RESPONSE_DUE', label: 'RFQ response due', mandatory: false },
  { type: 'PO_DELIVERY_APPROACHING', label: 'PO delivery approaching', mandatory: false },
  { type: 'PO_OVERDUE', label: 'PO delivery overdue', mandatory: true },
  { type: 'GRN_PENDING_INSPECTION', label: 'GRN pending inspection', mandatory: false },
  { type: 'INVOICE_MISMATCH', label: 'Purchase invoice mismatch', mandatory: true },
  { type: 'INVOICE_PENDING_APPROVAL', label: 'Purchase invoice pending approval', mandatory: true },
] as const
