-- Dispatch Phase 7C3 — packing (operational allocation, no stock movement).
-- Pack/unpack/move does not post stock movements or change onHandQty.

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER', 'LEAD', 'CONTACT', 'CRM_COMPANY', 'OPPORTUNITY', 'QUOTATION', 'SALES_ORDER',
  'PRODUCTION_DEMAND', 'PRODUCTION_ORDER', 'DAILY_PRODUCTION_BATCH', 'PRODUCTION_ISSUE',
  'STOCK_MOVEMENT', 'STOCK_RESERVATION', 'PURCHASE_REQUISITION',
  'QUALITY_INSPECTION', 'QUALITY_NCR', 'JOB_WORK_ORDER', 'PRODUCTION_RUNTIME_CHANGE',
  'PRODUCTION_WIP_MOVEMENT', 'MANUFACTURING_CORRECTION', 'PRODUCTION_PLAN',
  'DEMAND_CONSOLIDATION_PLAN', 'OUTBOUND_DISPATCH', 'PRODUCTION_FG_RECEIPT',
  'DISPATCH_REQUIREMENT', 'DISPATCH_PICK_LIST', 'DISPATCH_PACKING_SESSION', 'DISPATCH_PACKAGE'
) NOT NULL;

CREATE TABLE `dispatch_package_types` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `defaultTareWeight` DECIMAL(18, 4) NULL,
  `defaultLength` DECIMAL(18, 4) NULL,
  `defaultWidth` DECIMAL(18, 4) NULL,
  `defaultHeight` DECIMAL(18, 4) NULL,
  `weightUomId` VARCHAR(191) NULL,
  `dimensionUomId` VARCHAR(191) NULL,
  `reusable` BOOLEAN NOT NULL DEFAULT true,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `dispatch_pkg_type_tenant_code_uidx`(`tenantId`, `code`),
  INDEX `dispatch_pkg_type_tenant_active_idx`(`tenantId`, `active`),
  CONSTRAINT `dispatch_package_types_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_types_weightUomId_fkey` FOREIGN KEY (`weightUomId`) REFERENCES `master_uoms`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_types_dimensionUomId_fkey` FOREIGN KEY (`dimensionUomId`) REFERENCES `master_uoms`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `dispatch_packing_sessions` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `packingSessionNumber` VARCHAR(64) NOT NULL,
  `outboundDispatchId` VARCHAR(191) NOT NULL,
  `warehouseId` VARCHAR(191) NOT NULL,
  `status` ENUM('DRAFT', 'READY', 'IN_PROGRESS', 'PARTIALLY_PACKED', 'PACKED', 'VERIFIED', 'BLOCKED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `assignedTo` VARCHAR(191) NULL,
  `packingStation` VARCHAR(64) NULL,
  `plannedPackingDate` DATE NULL,
  `startedAt` DATETIME(3) NULL,
  `startedBy` VARCHAR(191) NULL,
  `completedAt` DATETIME(3) NULL,
  `completedBy` VARCHAR(191) NULL,
  `verifiedAt` DATETIME(3) NULL,
  `verifiedBy` VARCHAR(191) NULL,
  `totalPickedQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalPackedQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalUnpackedQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalShortageQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalPackages` INT NOT NULL DEFAULT 0,
  `grossWeight` DECIMAL(18, 4) NULL,
  `netWeight` DECIMAL(18, 4) NULL,
  `weightUomId` VARCHAR(191) NULL,
  `sourceVersion` INTEGER NOT NULL DEFAULT 1,
  `idempotencyKey` VARCHAR(150) NULL,
  `remarks` TEXT NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `dispatch_pack_sess_tenant_number_uidx`(`tenantId`, `packingSessionNumber`),
  UNIQUE INDEX `dispatch_pack_sess_tenant_idem_uidx`(`tenantId`, `idempotencyKey`),
  INDEX `dispatch_pack_sess_tenant_ob_idx`(`tenantId`, `outboundDispatchId`),
  INDEX `dispatch_pack_sess_tenant_status_idx`(`tenantId`, `status`),
  INDEX `dispatch_pack_sess_tenant_del_idx`(`tenantId`, `deletedAt`),
  CONSTRAINT `dispatch_packing_sessions_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packing_sessions_outboundDispatchId_fkey` FOREIGN KEY (`outboundDispatchId`) REFERENCES `outbound_dispatches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packing_sessions_warehouseId_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `master_warehouses`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packing_sessions_weightUomId_fkey` FOREIGN KEY (`weightUomId`) REFERENCES `master_uoms`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `dispatch_packages` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `packageNumber` VARCHAR(64) NOT NULL,
  `packingSessionId` VARCHAR(191) NOT NULL,
  `outboundDispatchId` VARCHAR(191) NOT NULL,
  `warehouseId` VARCHAR(191) NOT NULL,
  `packageTypeId` VARCHAR(191) NULL,
  `packageTypeCodeSnapshot` VARCHAR(32) NULL,
  `packageReference` VARCHAR(100) NULL,
  `packageSequence` INT NOT NULL,
  `tareWeight` DECIMAL(18, 4) NULL,
  `grossWeight` DECIMAL(18, 4) NULL,
  `netWeight` DECIMAL(18, 4) NULL,
  `length` DECIMAL(18, 4) NULL,
  `width` DECIMAL(18, 4) NULL,
  `height` DECIMAL(18, 4) NULL,
  `weightUomId` VARCHAR(191) NULL,
  `dimensionUomId` VARCHAR(191) NULL,
  `sealNumber` VARCHAR(64) NULL,
  `externalMarking` VARCHAR(200) NULL,
  `status` ENUM('OPEN', 'PARTIALLY_FILLED', 'COMPLETE', 'VERIFIED', 'REOPENED', 'CANCELLED') NOT NULL DEFAULT 'OPEN',
  `verifiedAt` DATETIME(3) NULL,
  `verifiedBy` VARCHAR(191) NULL,
  `sourceVersion` INT NOT NULL DEFAULT 1,
  `remarks` TEXT NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `dispatch_package_tenant_number_uidx`(`tenantId`, `packageNumber`),
  UNIQUE INDEX `dispatch_package_sess_seq_uidx`(`packingSessionId`, `packageSequence`),
  INDEX `dispatch_package_tenant_sess_idx`(`tenantId`, `packingSessionId`),
  INDEX `dispatch_package_tenant_ob_idx`(`tenantId`, `outboundDispatchId`),
  INDEX `dispatch_package_tenant_status_idx`(`tenantId`, `status`),
  CONSTRAINT `dispatch_packages_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packages_packingSessionId_fkey` FOREIGN KEY (`packingSessionId`) REFERENCES `dispatch_packing_sessions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packages_outboundDispatchId_fkey` FOREIGN KEY (`outboundDispatchId`) REFERENCES `outbound_dispatches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packages_warehouseId_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `master_warehouses`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packages_packageTypeId_fkey` FOREIGN KEY (`packageTypeId`) REFERENCES `dispatch_package_types`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packages_weightUomId_fkey` FOREIGN KEY (`weightUomId`) REFERENCES `master_uoms`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packages_dimensionUomId_fkey` FOREIGN KEY (`dimensionUomId`) REFERENCES `master_uoms`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `dispatch_package_lines` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `packageId` VARCHAR(191) NOT NULL,
  `packingSessionId` VARCHAR(191) NOT NULL,
  `outboundDispatchLineId` VARCHAR(191) NOT NULL,
  `dispatchRequirementId` VARCHAR(191) NULL,
  `salesOrderId` VARCHAR(191) NULL,
  `salesOrderLineId` VARCHAR(64) NULL,
  `pickListId` VARCHAR(191) NULL,
  `pickLineId` VARCHAR(191) NOT NULL,
  `itemId` VARCHAR(191) NOT NULL,
  `packedQuantity` DECIMAL(18, 4) NOT NULL,
  `lotRef` VARCHAR(100) NULL,
  `serialRef` VARCHAR(100) NULL,
  `heatNumber` VARCHAR(100) NULL,
  `sourcePickEventId` VARCHAR(191) NULL,
  `status` ENUM('PACKED', 'MOVED', 'UNPACKED', 'CANCELLED') NOT NULL DEFAULT 'PACKED',
  `sourceVersion` INT NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  INDEX `dispatch_pkg_line_tenant_pkg_idx`(`tenantId`, `packageId`),
  INDEX `dispatch_pkg_line_tenant_sess_idx`(`tenantId`, `packingSessionId`),
  INDEX `dispatch_pkg_line_tenant_pick_line_idx`(`tenantId`, `pickLineId`),
  INDEX `dispatch_pkg_line_tenant_ob_line_idx`(`tenantId`, `outboundDispatchLineId`),
  CONSTRAINT `dispatch_package_lines_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_lines_packageId_fkey` FOREIGN KEY (`packageId`) REFERENCES `dispatch_packages`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_lines_packingSessionId_fkey` FOREIGN KEY (`packingSessionId`) REFERENCES `dispatch_packing_sessions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_lines_outboundDispatchLineId_fkey` FOREIGN KEY (`outboundDispatchLineId`) REFERENCES `outbound_dispatch_lines`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_lines_pickListId_fkey` FOREIGN KEY (`pickListId`) REFERENCES `dispatch_pick_lists`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_lines_pickLineId_fkey` FOREIGN KEY (`pickLineId`) REFERENCES `dispatch_pick_lines`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_package_lines_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `master_items`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `dispatch_packing_events` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `packingSessionId` VARCHAR(191) NOT NULL,
  `packageId` VARCHAR(191) NULL,
  `packageLineId` VARCHAR(191) NULL,
  `eventType` ENUM(
    'SESSION_CREATED', 'SESSION_STARTED', 'PACKAGE_CREATED', 'PACK', 'UNPACK',
    'MOVE_BETWEEN_PACKAGES', 'PACKAGE_COMPLETED', 'PACKAGE_REOPENED', 'PACKAGE_VERIFIED',
    'SHORTAGE_REPORTED', 'SHORTAGE_RESOLVED', 'SESSION_COMPLETED', 'SESSION_VERIFIED', 'SESSION_CANCELLED'
  ) NOT NULL,
  `itemId` VARCHAR(191) NULL,
  `quantity` DECIMAL(18, 4) NULL,
  `lotRef` VARCHAR(100) NULL,
  `serialRef` VARCHAR(100) NULL,
  `heatNumber` VARCHAR(100) NULL,
  `sourcePackageId` VARCHAR(191) NULL,
  `destinationPackageId` VARCHAR(191) NULL,
  `reasonCode` VARCHAR(64) NULL,
  `remarks` TEXT NULL,
  `performedBy` VARCHAR(191) NOT NULL,
  `performedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `idempotencyKey` VARCHAR(150) NULL,
  `reversalOfEventId` VARCHAR(191) NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `dispatch_pack_event_tenant_idem_uidx`(`tenantId`, `idempotencyKey`),
  INDEX `dispatch_pack_event_tenant_sess_idx`(`tenantId`, `packingSessionId`),
  INDEX `dispatch_pack_event_tenant_pkg_idx`(`tenantId`, `packageId`),
  CONSTRAINT `dispatch_packing_events_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packing_events_packingSessionId_fkey` FOREIGN KEY (`packingSessionId`) REFERENCES `dispatch_packing_sessions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packing_events_packageId_fkey` FOREIGN KEY (`packageId`) REFERENCES `dispatch_packages`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `dispatch_packing_events_packageLineId_fkey` FOREIGN KEY (`packageLineId`) REFERENCES `dispatch_package_lines`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
