-- Phase 3 — GSTR-2B import batches + ITC recon follow-up

CREATE TABLE IF NOT EXISTS `gstr2b_import_batches` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `returnPeriod` VARCHAR(7) NOT NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'FILE',
  `fileName` VARCHAR(260) NULL,
  `providerMode` VARCHAR(32) NOT NULL DEFAULT 'SIMULATED',
  `status` ENUM('IMPORTED', 'RECONCILING', 'RECONCILED', 'VOID') NOT NULL DEFAULT 'IMPORTED',
  `rowCount` INTEGER NOT NULL DEFAULT 0,
  `matchedCount` INTEGER NOT NULL DEFAULT 0,
  `mismatchCount` INTEGER NOT NULL DEFAULT 0,
  `missingInBooks` INTEGER NOT NULL DEFAULT 0,
  `missingIn2b` INTEGER NOT NULL DEFAULT 0,
  `payloadChecksum` VARCHAR(128) NULL,
  `importNotes` VARCHAR(1000) NULL,
  `importedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `importedBy` VARCHAR(191) NULL,
  `reconciledAt` DATETIME(3) NULL,
  `reconciledBy` VARCHAR(191) NULL,
  `voidedAt` DATETIME(3) NULL,
  `voidReason` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gstr2b_batch_le_period_idx`(`tenantId`, `legalEntityId`, `returnPeriod`),
  INDEX `gstr2b_batch_status_idx`(`tenantId`, `status`),
  CONSTRAINT `gstr2b_import_batches_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gstr2b_import_batches_legalEntityId_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gstr2b_import_rows` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `batchId` VARCHAR(191) NOT NULL,
  `lineNo` INTEGER NOT NULL DEFAULT 0,
  `supplierGstin` VARCHAR(20) NOT NULL,
  `supplierName` VARCHAR(300) NULL,
  `invoiceNumber` VARCHAR(128) NOT NULL,
  `invoiceNumberNorm` VARCHAR(128) NOT NULL,
  `invoiceDate` DATE NOT NULL,
  `taxableValue` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `cgstAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `sgstAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `igstAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `cessAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `placeOfSupply` VARCHAR(100) NULL,
  `documentTypeHint` VARCHAR(40) NULL,
  `matchStatus` ENUM(
    'UNMATCHED','MATCHED','PARTIAL_MATCH','MISSING_IN_BOOKS','MISSING_IN_2B',
    'VALUE_MISMATCH','TAX_MISMATCH','GSTIN_MISMATCH','DUPLICATE','REVIEW_REQUIRED'
  ) NOT NULL DEFAULT 'UNMATCHED',
  `matchScore` INTEGER NOT NULL DEFAULT 0,
  `matchedVendorInvoiceId` VARCHAR(191) NULL,
  `matchNotes` VARCHAR(1000) NULL,
  `itcClaimClass` ENUM(
    'REVIEW_REQUIRED','ELIGIBLE','PARTIALLY_ELIGIBLE','INELIGIBLE','BLOCKED',
    'CAPITAL_GOODS','INPUT_SERVICE','INPUT_GOODS','RCM_ELIGIBLE','NOT_APPLICABLE'
  ) NOT NULL DEFAULT 'REVIEW_REQUIRED',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gstr2b_row_batch_idx`(`tenantId`, `batchId`),
  INDEX `gstr2b_row_gstin_inv_idx`(`tenantId`, `supplierGstin`, `invoiceNumberNorm`),
  INDEX `gstr2b_row_match_idx`(`tenantId`, `matchStatus`),
  CONSTRAINT `gstr2b_import_rows_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gstr2b_import_rows_batchId_fkey` FOREIGN KEY (`batchId`) REFERENCES `gstr2b_import_batches`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gstr2b_vendor_follow_ups` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `batchId` VARCHAR(191) NULL,
  `rowId` VARCHAR(191) NULL,
  `vendorInvoiceId` VARCHAR(191) NULL,
  `vendorId` VARCHAR(191) NULL,
  `vendorGstin` VARCHAR(20) NULL,
  `vendorName` VARCHAR(300) NULL,
  `reasonCode` VARCHAR(64) NOT NULL,
  `status` ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'WAIVED') NOT NULL DEFAULT 'OPEN',
  `notes` VARCHAR(2000) NULL,
  `assignedToUserId` VARCHAR(191) NULL,
  `resolvedAt` DATETIME(3) NULL,
  `resolvedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gstr2b_fu_le_status_idx`(`tenantId`, `legalEntityId`, `status`),
  INDEX `gstr2b_fu_gstin_idx`(`tenantId`, `vendorGstin`),
  CONSTRAINT `gstr2b_vendor_follow_ups_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gstr2b_vendor_follow_ups_batchId_fkey` FOREIGN KEY (`batchId`) REFERENCES `gstr2b_import_batches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `gstr2b_vendor_follow_ups_rowId_fkey` FOREIGN KEY (`rowId`) REFERENCES `gstr2b_import_rows`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
