-- Controlled emergency overrides — audit register; does not alter posted transactions.

CREATE TABLE `emergency_overrides` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `overrideNo` VARCHAR(64) NOT NULL,
  `module` VARCHAR(64) NOT NULL,
  `documentType` VARCHAR(64) NOT NULL,
  `documentId` VARCHAR(191) NOT NULL,
  `documentNo` VARCHAR(64) NULL,
  `blockedAction` VARCHAR(64) NOT NULL,
  `primaryBlockerCode` VARCHAR(64) NULL,
  `blockerCodesJson` JSON NOT NULL,
  `originalBlockersSnapshot` JSON NULL,
  `businessReason` TEXT NOT NULL,
  `urgency` ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL DEFAULT 'HIGH',
  `riskAcknowledged` BOOLEAN NOT NULL DEFAULT false,
  `supportingAttachmentKey` VARCHAR(500) NULL,
  `requestedByUserId` VARCHAR(191) NULL,
  `requestedByName` VARCHAR(200) NULL,
  `approvedByUserId` VARCHAR(191) NULL,
  `approvedByName` VARCHAR(200) NULL,
  `approvalReference` VARCHAR(64) NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `scope` VARCHAR(500) NULL,
  `remarks` TEXT NULL,
  `status` ENUM('REQUESTED', 'GRANTED', 'CONSUMED', 'EXPIRED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'REQUESTED',
  `grantedAt` DATETIME(3) NULL,
  `consumedAt` DATETIME(3) NULL,
  `consumedByAction` VARCHAR(64) NULL,
  `consumedDocumentId` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eo_tenant_no_uidx`(`tenantId`, `overrideNo`),
  INDEX `eo_tenant_doc_idx`(`tenantId`, `documentType`, `documentId`),
  INDEX `eo_tenant_status_idx`(`tenantId`, `status`),
  INDEX `eo_tenant_expires_idx`(`tenantId`, `expiresAt`),
  CONSTRAINT `eo_tenant_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
