-- Restore PRODUCTION_FG_RECEIPT on code_series.entityType.
-- Migration 20260721030000_dispatch_phase7c0_fulfilment rewrote the ENUM and omitted
-- PRODUCTION_FG_RECEIPT previously added by 20260721010000_manufacturing_phase7a1_warehouse_mapping.
-- MySQL non-strict mode coerces the unknown value to '' → Prisma: Value '' not found in enum.

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER', 'LEAD', 'CONTACT', 'CRM_COMPANY', 'OPPORTUNITY', 'QUOTATION', 'SALES_ORDER',
  'PRODUCTION_DEMAND', 'PRODUCTION_ORDER', 'DAILY_PRODUCTION_BATCH', 'PRODUCTION_ISSUE',
  'STOCK_MOVEMENT', 'STOCK_RESERVATION', 'PURCHASE_REQUISITION',
  'QUALITY_INSPECTION', 'QUALITY_NCR', 'JOB_WORK_ORDER', 'PRODUCTION_RUNTIME_CHANGE',
  'PRODUCTION_WIP_MOVEMENT', 'MANUFACTURING_CORRECTION', 'PRODUCTION_PLAN',
  'DEMAND_CONSOLIDATION_PLAN', 'OUTBOUND_DISPATCH', 'PRODUCTION_FG_RECEIPT'
) NOT NULL;
