-- Tax compliance Phase 2 — e-invoice + e-way bill document registers (simulated NIC).

CREATE TABLE `gst_e_invoices` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `salesInvoiceId` VARCHAR(191) NOT NULL,
  `invoiceNumber` VARCHAR(64) NULL,
  `invoiceDate` DATE NOT NULL,
  `customerName` VARCHAR(300) NOT NULL,
  `customerGstin` VARCHAR(20) NULL,
  `taxableAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `taxAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `status` ENUM('PENDING', 'GENERATED', 'CANCELLED', 'EXCEPTION') NOT NULL DEFAULT 'PENDING',
  `irn` VARCHAR(100) NULL,
  `ackNo` VARCHAR(64) NULL,
  `ackDate` DATETIME(3) NULL,
  `qrPayload` TEXT NULL,
  `cancelReason` VARCHAR(500) NULL,
  `cancelledAt` DATETIME(3) NULL,
  `cancelledBy` VARCHAR(191) NULL,
  `exceptionMessage` VARCHAR(1000) NULL,
  `providerMode` VARCHAR(32) NOT NULL DEFAULT 'SIMULATED',
  `providerRef` VARCHAR(150) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `gst_einv_tenant_si_key` (`tenantId`, `salesInvoiceId`),
  UNIQUE INDEX `gst_einv_tenant_irn_key` (`tenantId`, `irn`),
  INDEX `gst_einv_tenant_idx` (`tenantId`),
  INDEX `gst_einv_le_status_idx` (`tenantId`, `legalEntityId`, `status`),
  INDEX `gst_einv_le_date_idx` (`tenantId`, `legalEntityId`, `invoiceDate`),
  CONSTRAINT `gst_einv_tenant_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gst_einv_le_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gst_einv_si_fkey` FOREIGN KEY (`salesInvoiceId`) REFERENCES `sales_invoices` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gst_e_way_bills` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `sourceType` ENUM('SALES_INVOICE', 'DELIVERY_CHALLAN') NOT NULL,
  `salesInvoiceId` VARCHAR(191) NULL,
  `deliveryChallanId` VARCHAR(191) NULL,
  `documentNumber` VARCHAR(64) NOT NULL,
  `documentDate` DATE NOT NULL,
  `partyName` VARCHAR(300) NOT NULL,
  `partyGstin` VARCHAR(20) NULL,
  `fromPlace` VARCHAR(200) NOT NULL,
  `toPlace` VARCHAR(200) NOT NULL,
  `distanceKm` INT NOT NULL DEFAULT 0,
  `vehicleNumber` VARCHAR(64) NULL,
  `transporterName` VARCHAR(200) NULL,
  `taxableAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `status` ENUM('REQUIRED', 'NOT_REQUIRED', 'GENERATED', 'CANCELLED', 'EXPIRED', 'EXCEPTION') NOT NULL DEFAULT 'REQUIRED',
  `ewbNumber` VARCHAR(64) NULL,
  `validUpto` DATETIME(3) NULL,
  `cancelReason` VARCHAR(500) NULL,
  `cancelledAt` DATETIME(3) NULL,
  `cancelledBy` VARCHAR(191) NULL,
  `exceptionMessage` VARCHAR(1000) NULL,
  `providerMode` VARCHAR(32) NOT NULL DEFAULT 'SIMULATED',
  `providerRef` VARCHAR(150) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `gst_ewb_tenant_si_key` (`tenantId`, `salesInvoiceId`),
  UNIQUE INDEX `gst_ewb_tenant_dc_key` (`tenantId`, `deliveryChallanId`),
  UNIQUE INDEX `gst_ewb_tenant_ewb_key` (`tenantId`, `ewbNumber`),
  INDEX `gst_ewb_tenant_idx` (`tenantId`),
  INDEX `gst_ewb_le_status_idx` (`tenantId`, `legalEntityId`, `status`),
  INDEX `gst_ewb_le_date_idx` (`tenantId`, `legalEntityId`, `documentDate`),
  CONSTRAINT `gst_ewb_tenant_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gst_ewb_le_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gst_ewb_si_fkey` FOREIGN KEY (`salesInvoiceId`) REFERENCES `sales_invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `gst_ewb_dc_fkey` FOREIGN KEY (`deliveryChallanId`) REFERENCES `delivery_challans` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
