import { AppError } from '../../../utils/errors.js'

export type PostingErrorCode =
  | 'AUTHORIZATION_NOT_VERIFIED'
  | 'WORKFLOW_NOT_SATISFIED'
  | 'FINANCE_NOT_ACTIVATED'
  | 'ACCOUNTING_PERIOD_NOT_FOUND'
  | 'ACCOUNTING_PERIOD_CLOSED'
  | 'ACCOUNTING_PERIOD_UNDER_REVIEW'
  | 'BACKDATED_POSTING_NOT_ALLOWED'
  | 'FINANCIAL_YEAR_NOT_FOUND'
  | 'FINANCIAL_YEAR_INACTIVE'
  | 'IDEMPOTENCY_PAYLOAD_MISMATCH'
  | 'POSTING_EVENT_IN_PROGRESS'
  | 'NUMBER_SERIES_NOT_CONFIGURED'
  | 'NUMBER_SERIES_INACTIVE'
  | 'INSUFFICIENT_LINES'
  | 'ZERO_TOTAL_POSTING'
  | 'UNBALANCED'
  | 'UNBALANCED_BASE'
  | 'ACCOUNT_RESOLUTION_FAILED'
  | 'ACCOUNT_NOT_FOUND'
  | 'ACCOUNT_IS_GROUP'
  | 'ACCOUNT_INACTIVE'
  | 'CONTROL_ACCOUNT_BLOCKED'
  | 'MANUAL_POSTING_BLOCKED'
  | 'PARTY_REQUIRED'
  | 'PARTY_NOT_FOUND'
  | 'PARTY_TYPE_NOT_SUPPORTED'
  | 'INVALID_LINE_ACCOUNT_REFERENCE'
  | 'MULTI_CURRENCY_NOT_ENABLED'
  | 'INVALID_CURRENCY'
  | 'INVALID_EXCHANGE_RATE'
  | 'POSTING_TRANSACTION_FAILED'
  | 'POSTING_CONCURRENT_ACTION'
  | 'VALIDATION_FAILED'

const STATUS_BY_CODE: Record<PostingErrorCode, number> = {
  AUTHORIZATION_NOT_VERIFIED: 403,
  WORKFLOW_NOT_SATISFIED: 403,
  FINANCE_NOT_ACTIVATED: 422,
  ACCOUNTING_PERIOD_NOT_FOUND: 422,
  ACCOUNTING_PERIOD_CLOSED: 422,
  ACCOUNTING_PERIOD_UNDER_REVIEW: 422,
  BACKDATED_POSTING_NOT_ALLOWED: 422,
  FINANCIAL_YEAR_NOT_FOUND: 422,
  FINANCIAL_YEAR_INACTIVE: 422,
  IDEMPOTENCY_PAYLOAD_MISMATCH: 409,
  POSTING_EVENT_IN_PROGRESS: 409,
  NUMBER_SERIES_NOT_CONFIGURED: 422,
  NUMBER_SERIES_INACTIVE: 422,
  INSUFFICIENT_LINES: 400,
  ZERO_TOTAL_POSTING: 400,
  UNBALANCED: 400,
  UNBALANCED_BASE: 400,
  ACCOUNT_RESOLUTION_FAILED: 422,
  ACCOUNT_NOT_FOUND: 422,
  ACCOUNT_IS_GROUP: 422,
  ACCOUNT_INACTIVE: 422,
  CONTROL_ACCOUNT_BLOCKED: 422,
  MANUAL_POSTING_BLOCKED: 422,
  PARTY_REQUIRED: 422,
  PARTY_NOT_FOUND: 422,
  PARTY_TYPE_NOT_SUPPORTED: 422,
  INVALID_LINE_ACCOUNT_REFERENCE: 400,
  MULTI_CURRENCY_NOT_ENABLED: 422,
  INVALID_CURRENCY: 400,
  INVALID_EXCHANGE_RATE: 400,
  POSTING_TRANSACTION_FAILED: 500,
  POSTING_CONCURRENT_ACTION: 409,
  VALIDATION_FAILED: 400,
}

export class PostingError extends AppError {
  constructor(
    code: PostingErrorCode,
    message: string,
    errors?: Array<{ field: string; message: string }>,
  ) {
    super(STATUS_BY_CODE[code] ?? 422, message, code, errors)
    this.name = 'PostingError'
  }
}
