import type { CrmMasterCatalogItem, CrmMasterUsedIn } from '../types/crmMasters'

const USED_IN_COMPANY: CrmMasterUsedIn[] = ['companies', 'leads', 'opportunities', 'customer360', 'reports']
const USED_IN_PIPELINE: CrmMasterUsedIn[] = ['leads', 'opportunities', 'quotations', 'sales-orders', 'reports']
const USED_IN_QUOTATION: CrmMasterUsedIn[] = ['quotations', 'sales-orders', 'invoices', 'reports']
const STATUS_FIELD = { key: 'status', label: 'Status', type: 'select' as const, section: 'basic' as const, options: [{ value: 'active', label: 'Active' }, { value: 'inactive', label: 'Inactive' }] }

export const CRM_MASTERS_CATALOG: CrmMasterCatalogItem[] = [
  {
    kind: 'lead-sources',
    slug: 'lead-sources',
    title: 'Lead Source Master',
    description: 'Inbound and outbound lead source definitions for company and analytics.',
    purpose: 'Classify how prospects enter the CRM funnel for attribution, ROI, and campaign planning.',
    group: 'company',
    usedIn: USED_IN_COMPANY,
    importExport: true,
    fields: [
      { key: 'code', label: 'Source Code', type: 'text', required: true },
      { key: 'name', label: 'Source Name', type: 'text', required: true },
      { key: 'sourceType', label: 'Source Type', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'industries',
    slug: 'industries',
    title: 'Industry Master',
    description: 'Industry segments for company classification and CRM analytics.',
    purpose: 'Segment accounts and leads by vertical for tailored sales playbooks.',
    group: 'company',
    usedIn: USED_IN_COMPANY,
    importExport: true,
    fields: [
      { key: 'code', label: 'Industry Code', type: 'text', required: true },
      { key: 'name', label: 'Industry Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'designations',
    slug: 'designations',
    title: 'Designation Master',
    description: 'Job titles and decision roles for contacts and stakeholders.',
    purpose: 'Standardize contact titles for filters, reporting, and engagement routing.',
    group: 'company',
    usedIn: ['contacts', 'companies', 'customer360', 'leads', 'reports'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Designation Code', type: 'text', required: true },
      { key: 'name', label: 'Designation Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'departments',
    slug: 'departments',
    title: 'Department Master',
    description: 'Organizational departments for contacts, purchase, and production.',
    purpose: 'Classify people and requests by department for routing and analytics.',
    group: 'company',
    usedIn: ['contacts', 'companies', 'customer360', 'reports'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Department Code', type: 'text', required: true },
      { key: 'name', label: 'Department Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'territories',
    slug: 'territories',
    title: 'Territory Master',
    description: 'Sales territories for assignment, owner mapping, and performance.',
    purpose: 'Define geographic and regional sales coverage with manager accountability.',
    group: 'company',
    usedIn: [...USED_IN_COMPANY, 'sales-orders'],
    importExport: true,
    showNotes: false,
    fields: [
      { key: 'code', label: 'Territory Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Territory Name', type: 'text', required: true, section: 'basic' },
      { key: 'region', label: 'Region', type: 'text', section: 'basic' },
      { key: 'state', label: 'State', type: 'text', section: 'basic' },
      { key: 'country', label: 'Country', type: 'text', section: 'basic' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'lead-stages',
    slug: 'lead-stages',
    title: 'Lead Stage Master',
    description: 'Pipeline stages, order, colours, and required actions for leads.',
    purpose: 'Control lead lifecycle progression and conversion workflow.',
    group: 'pipeline',
    usedIn: ['leads', 'reports'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Stage Code', type: 'text', required: true },
      { key: 'name', label: 'Stage Name', type: 'text', required: true },
      { key: 'stageType', label: 'Stage Type', type: 'select', options: [{ value: 'open', label: 'Open' }, { value: 'qualified', label: 'Qualified' }, { value: 'converted', label: 'Converted' }, { value: 'closed', label: 'Closed' }] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'nextAction', label: 'Next Suggested Action', type: 'text' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'lead-priorities',
    slug: 'lead-priorities',
    title: 'Lead Priority Master',
    description: 'Lead priority levels, SLA hours, and dashboard alert rules.',
    purpose: 'Prioritize follow-up workload and SLA enforcement on leads.',
    group: 'pipeline',
    usedIn: ['leads', 'reports'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Priority Code', type: 'text', required: true },
      { key: 'name', label: 'Priority Name', type: 'text', required: true },
      { key: 'slaHours', label: 'SLA Follow-up Hours', type: 'number' },
      { key: 'color', label: 'Color', type: 'text' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'lead-reasons',
    slug: 'lead-reasons',
    title: 'Lead Status / Reason Master',
    description: 'Inactive, closed, not qualified, and archive reason lists.',
    purpose: 'Capture structured reasons when leads are closed or disqualified.',
    group: 'pipeline',
    usedIn: ['leads', 'reports'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Reason Code', type: 'text', required: true },
      { key: 'name', label: 'Reason Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: [{ value: 'inactive', label: 'Inactive' }, { value: 'closed', label: 'Closed' }, { value: 'not_qualified', label: 'Not Qualified' }, { value: 'archive', label: 'Archive' }] },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'opportunity-stages',
    slug: 'opportunity-stages',
    title: 'Opportunity Stage Master',
    description: 'Opportunity pipeline stages with probability and ageing limits.',
    purpose: 'Define the opportunity sales pipeline with forecast probability.',
    group: 'pipeline',
    usedIn: USED_IN_PIPELINE,
    importExport: true,
    showNotes: false,
    fields: [
      { key: 'code', label: 'Stage Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Stage Name', type: 'text', required: true, section: 'basic' },
      { key: 'probability', label: 'Probability %', type: 'number', section: 'configuration' },
      {
        key: 'stageType',
        label: 'Stage Type',
        type: 'select',
        section: 'configuration',
        options: [
          { value: 'open', label: 'Open' },
          { value: 'won', label: 'Won' },
          { value: 'lost', label: 'Lost' },
          { value: 'hold', label: 'On Hold' },
        ],
      },
      { key: 'color', label: 'Stage Color', type: 'color', section: 'configuration' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'opportunity-priorities',
    slug: 'opportunity-priorities',
    title: 'Opportunity Priority Master',
    description: 'Deal priority tiers for CEO dashboard and escalation.',
    purpose: 'Escalate high-value or strategic deals for executive attention.',
    group: 'pipeline',
    usedIn: USED_IN_PIPELINE,
    importExport: true,
    showNotes: false,
    fields: [
      { key: 'code', label: 'Priority Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Priority Name', type: 'text', required: true, section: 'basic' },
      { key: 'valueThreshold', label: 'Value Threshold (₹)', type: 'number', section: 'basic' },
      { key: 'color', label: 'Priority Color', type: 'color', section: 'basic' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'activity-types',
    slug: 'activity-types',
    title: 'Engagement Type Master',
    description: 'Unified engagement types for activity timeline logging and scheduled follow-ups.',
    purpose: 'Maintain one register for calls, meetings, follow-up tasks, and system timeline events.',
    group: 'communication',
    usedIn: ['leads', 'opportunities', 'quotations', 'customer360'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Type Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Type Name', type: 'text', required: true, section: 'basic' },
      { key: 'useInActivity', label: 'Use in Activity Log', type: 'boolean', section: 'basic' },
      { key: 'useInFollowUp', label: 'Use in Follow-up Schedule', type: 'boolean', section: 'basic' },
      { key: 'defaultDuration', label: 'Default Duration (min)', type: 'number', section: 'configuration' },
      { key: 'defaultReminder', label: 'Default Reminder (min)', type: 'number', section: 'configuration' },
      { key: 'icon', label: 'Icon', type: 'text', section: 'configuration' },
      { key: 'color', label: 'Color', type: 'color', section: 'configuration' },
      { key: 'systemGenerated', label: 'System Generated', type: 'boolean', section: 'configuration' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'lost-reasons',
    slug: 'lost-reasons',
    title: 'Lost Reason Master',
    description: 'Reasons for lost opportunities and deal analytics.',
    purpose: 'Structured lost-deal analysis for pipeline improvement.',
    group: 'pipeline',
    usedIn: ['opportunities', 'reports'],
    importExport: true,
    fields: [
      { key: 'code', label: 'Reason Code', type: 'text', required: true },
      { key: 'name', label: 'Reason Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'commercial-terms',
    slug: 'commercial-terms',
    title: 'Commercial Terms Master',
    description: 'Quotation commercial term blocks and approval rules.',
    purpose: 'Reusable commercial clauses for quotation documents.',
    group: 'quotation',
    usedIn: USED_IN_QUOTATION,
    importExport: true,
    descriptionFormat: 'richtext',
    fields: [
      { key: 'code', label: 'Term Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Term Name', type: 'text', required: true, section: 'basic' },
      { key: 'termType', label: 'Term Type', type: 'text', section: 'configuration' },
      {
        key: 'appliesTo',
        label: 'Applies To',
        type: 'multiselect',
        section: 'configuration',
        options: [
          { value: 'quotation', label: 'Quotation' },
          { value: 'sales_order', label: 'Sales Order' },
        ],
      },
      { key: 'approvalRequired', label: 'Approval Required', type: 'boolean', section: 'configuration' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'payment-terms',
    slug: 'payment-terms',
    title: 'Payment Terms Master',
    description: 'Standard payment terms for quotations and sales orders.',
    purpose: 'Define advance, credit days, and milestone payment structures.',
    group: 'quotation',
    usedIn: USED_IN_QUOTATION,
    importExport: true,
    showNotes: false,
    fields: [
      { key: 'code', label: 'Term Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Payment Term Name', type: 'text', required: true, section: 'basic' },
      { key: 'advancePct', label: 'Advance %', type: 'number', section: 'basic' },
      { key: 'creditDays', label: 'Credit Days', type: 'number', section: 'basic' },
      { key: 'approvalRequired', label: 'Approval Required', type: 'boolean', section: 'basic' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'delivery-terms',
    slug: 'delivery-terms',
    title: 'Delivery Terms Master',
    description: 'Delivery incoterms and lead times for quotations.',
    purpose: 'Standardize incoterms (FOB, CIF, DAP) and delivery commitments.',
    group: 'quotation',
    usedIn: USED_IN_QUOTATION,
    importExport: true,
    showNotes: false,
    fields: [
      { key: 'code', label: 'Term Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Delivery Term Name', type: 'text', required: true, section: 'basic' },
      { key: 'defaultDeliveryTime', label: 'Default Delivery Time', type: 'text', section: 'basic' },
      { key: 'approvalRequired', label: 'Approval Required', type: 'boolean', section: 'basic' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'warranty-terms',
    slug: 'warranty-terms',
    title: 'Warranty Terms Master',
    description: 'Warranty clauses and exclusions for quotation print/PDF.',
    purpose: 'Manage warranty coverage, duration, and exclusions on quotes.',
    group: 'quotation',
    usedIn: USED_IN_QUOTATION,
    importExport: true,
    showNotes: false,
    fields: [
      { key: 'code', label: 'Term Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Warranty Term Name', type: 'text', required: true, section: 'basic' },
      { key: 'warrantyDuration', label: 'Warranty Duration', type: 'text', section: 'basic' },
      { key: 'approvalRequired', label: 'Approval Required', type: 'boolean', section: 'basic' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'approval-rules',
    slug: 'approval-rules',
    title: 'Approval Rule Master',
    description: 'Quotation and sales order approval routing configuration.',
    purpose: 'Automate approval routing based on value, margin, and terms.',
    group: 'governance',
    usedIn: ['quotations', 'sales-orders'],
    importExport: true,
    showNotes: false,
    showDescription: false,
    basicSectionLabel: 'General',
    configurationSectionLabel: 'Routing Rules',
    fields: [
      { key: 'code', label: 'Rule Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Rule Name', type: 'text', required: true, section: 'basic' },
      { key: 'module', label: 'Module', type: 'text', section: 'configuration' },
      { key: 'triggerField', label: 'Trigger Field', type: 'text', section: 'configuration' },
      { key: 'condition', label: 'Condition', type: 'text', section: 'configuration' },
      { key: 'approvalRole', label: 'Approval Role', type: 'text', section: 'configuration' },
      STATUS_FIELD,
    ],
  },
  {
    kind: 'document-types',
    slug: 'document-types',
    title: 'Document Type / Attachment Master',
    description: 'CRM attachment categories for leads, opportunities, quotations, and companies.',
    purpose: 'Classify attachments on upload and enforce file-type / size rules.',
    group: 'governance',
    usedIn: ['leads', 'opportunities', 'quotations', 'sales-orders', 'customer360'],
    importExport: true,
    showNotes: false,
    showDescription: false,
    basicSectionLabel: 'General',
    fields: [
      { key: 'code', label: 'Type Code', type: 'text', required: true, section: 'basic' },
      { key: 'name', label: 'Document Type', type: 'text', required: true, section: 'basic' },
      { key: 'requiredFor', label: 'Required For', type: 'text', section: 'basic' },
      { key: 'fileTypes', label: 'File Types Allowed', type: 'text', section: 'basic' },
      { key: 'maxSizeMb', label: 'Max Size (MB)', type: 'number', section: 'basic' },
      STATUS_FIELD,
    ],
  },
]

/** Linked masters managed by existing operational pages */
export const CRM_LINKED_MASTERS = [
  {
    slug: 'companies',
    title: 'Company Master',
    description: 'Customers, prospects, GSTIN, territory, source, industry, and commercial profile.',
    group: 'company' as const,
    listRoute: '/masters/companies',
    newRoute: '/masters/companies/new',
    masterRoute: '/masters/companies',
    importExport: true,
  },
  {
    slug: 'contacts',
    title: 'Contact Master',
    description: 'People linked to companies — designation, decision role, and communication.',
    group: 'company' as const,
    listRoute: '/masters/contacts',
    newRoute: '/masters/contacts/new',
    masterRoute: '/masters/contacts',
    importExport: true,
  },
  {
    slug: 'quotation-templates',
    title: 'Quotation Template Master',
    description: 'Product quotation templates, sections, and print layout.',
    group: 'quotation' as const,
    listRoute: '/crm/quotation-templates',
    newRoute: '/crm/quotation-templates/new',
    masterRoute: '/crm/quotation-templates',
    importExport: false,
  },
]

export function getCrmMasterCatalog(slug: string) {
  if (slug === 'users' || slug === 'owners' || slug === 'competitors' || slug === 'follow-up-types' || slug === 'product-interests') return undefined
  return CRM_MASTERS_CATALOG.find((c) => c.slug === slug)
}

export function getCrmLinkedMaster(slug: string) {
  return CRM_LINKED_MASTERS.find((c) => c.slug === slug)
}
