/** System preset filter snapshots — applied when user picks a built-in view name. */
import { DEFAULT_COMPANY_FILTERS, filtersToRecord } from '../utils/crmCompaniesPortfolio'

export const LEAD_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': { search: '', stage: '', status: '', sortBy: 'lastModified' },
  'My Leads': { search: '', stage: '', status: 'open', sortBy: 'lastModified' },
  "Today's Follow-ups": { search: '', stage: '', status: 'open', sortBy: 'lastModified' },
  'High Value': { search: '', stage: 'qualified', status: '', valueMin: '500000', sortBy: 'expectedValue' },
  Manufacturing: { search: '', industry: 'Manufacturing', stage: '', status: '', sortBy: 'prospect' },
  Converted: { search: '', stage: '', status: 'converted', sortBy: 'lastModified' },
  Lost: { search: '', stage: 'closed', status: 'closed', sortBy: 'lastModified' },
  'Recently Updated': { search: '', stage: '', status: '', sortBy: 'lastModified' },
}

export const QUOTATION_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': { search: '', status: '', segment: '', sortBy: 'date' },
  'Pending Approval': { search: '', status: 'pending_approval', segment: 'pending', sortBy: 'date' },
  Drafts: { search: '', status: 'draft', segment: 'draft', sortBy: 'date' },
  Approved: { search: '', status: 'approved', segment: 'approved', sortBy: 'value' },
  Converted: { search: '', status: 'converted', segment: '', sortBy: 'date' },
}

export const COMPANY_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': filtersToRecord(DEFAULT_COMPANY_FILTERS),
  'Overdue Follow-ups': filtersToRecord({ ...DEFAULT_COMPANY_FILTERS, overdueFollowUp: true, sortBy: 'followUp' }),
  'Active Pipeline': filtersToRecord({ ...DEFAULT_COMPANY_FILTERS, pipelineStatus: 'active', activeOpportunity: true }),
}

export const CONTACT_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': {
    search: '', customer: '', designation: '', city: '', territory: '',
    primaryOnly: 'false', overdueOnly: 'false', sortBy: 'name',
  },
  'Primary Contacts': {
    search: '', customer: '', designation: '', city: '', territory: '',
    primaryOnly: 'true', overdueOnly: 'false', sortBy: 'company',
  },
  'Overdue Follow-ups': {
    search: '', customer: '', designation: '', city: '', territory: '',
    primaryOnly: 'false', overdueOnly: 'true', sortBy: 'followUp',
  },
}

export const OPPORTUNITY_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': { search: '', stage: '', owner: '', sortBy: 'value' },
  Negotiation: { search: '', stage: 'negotiation', owner: '', sortBy: 'value' },
  'Quotation Stage': { search: '', stage: 'quotation_sent', owner: '', sortBy: 'closeDate' },
  'High Value': { search: '', stage: '', owner: '', sortBy: 'value' },
}

export const SALES_ORDER_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': { search: '', status: '', source: '', sortBy: 'orderDate' },
  'Draft Orders': { search: '', status: 'open', source: '', sortBy: 'orderDate' },
  Confirmed: { search: '', status: 'confirmed', source: '', sortBy: 'orderDate' },
  'From Quotation': { search: '', status: '', source: 'quotation', sortBy: 'orderDate' },
}

export const PR_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': {
    search: '',
    status: '',
    documentDateFrom: '',
    documentDateTo: '',
    requiredByFrom: '',
    requiredByTo: '',
    department: '',
    locationId: '',
    requesterId: '',
    priority: '',
    source: '',
    sortBy: 'documentDate',
  },
  Drafts: {
    search: '',
    status: 'draft',
    documentDateFrom: '',
    documentDateTo: '',
    requiredByFrom: '',
    requiredByTo: '',
    department: '',
    locationId: '',
    requesterId: '',
    priority: '',
    source: '',
    sortBy: 'documentDate',
  },
  'Pending Approval': {
    search: '',
    status: 'pending_approval',
    documentDateFrom: '',
    documentDateTo: '',
    requiredByFrom: '',
    requiredByTo: '',
    department: '',
    locationId: '',
    requesterId: '',
    priority: '',
    source: '',
    sortBy: 'documentDate',
  },
  Approved: {
    search: '',
    status: 'approved',
    documentDateFrom: '',
    documentDateTo: '',
    requiredByFrom: '',
    requiredByTo: '',
    department: '',
    locationId: '',
    requesterId: '',
    priority: '',
    source: '',
    sortBy: 'estimatedValue',
  },
  Converted: {
    search: '',
    status: 'converted',
    documentDateFrom: '',
    documentDateTo: '',
    requiredByFrom: '',
    requiredByTo: '',
    department: '',
    locationId: '',
    requesterId: '',
    priority: '',
    source: '',
    sortBy: 'documentDate',
  },
  Urgent: {
    search: '',
    status: '',
    documentDateFrom: '',
    documentDateTo: '',
    requiredByFrom: '',
    requiredByTo: '',
    department: '',
    locationId: '',
    requesterId: '',
    priority: 'urgent',
    source: '',
    sortBy: 'requiredBy',
  },
}

export const PO_REGISTER_PRESETS: Record<string, Record<string, string>> = {
  'My View': {
    search: '',
    status: '',
    vendorName: '',
    locationName: '',
    buyerName: '',
    approvalStatus: '',
    invoiceStatus: '',
    origin: '',
    documentDateFrom: '',
    documentDateTo: '',
    expectedDeliveryFrom: '',
    expectedDeliveryTo: '',
    sortBy: 'documentDate',
  },
  Drafts: {
    search: '',
    status: 'draft',
    vendorName: '',
    locationName: '',
    buyerName: '',
    approvalStatus: '',
    invoiceStatus: '',
    origin: '',
    documentDateFrom: '',
    documentDateTo: '',
    expectedDeliveryFrom: '',
    expectedDeliveryTo: '',
    sortBy: 'documentDate',
  },
  'Pending Approval': {
    search: '',
    status: 'pending_approval',
    vendorName: '',
    locationName: '',
    buyerName: '',
    approvalStatus: '',
    invoiceStatus: '',
    origin: '',
    documentDateFrom: '',
    documentDateTo: '',
    expectedDeliveryFrom: '',
    expectedDeliveryTo: '',
    sortBy: 'documentDate',
  },
  'Released or Later': {
    search: '',
    status: 'released_or_later',
    vendorName: '',
    locationName: '',
    buyerName: '',
    approvalStatus: '',
    invoiceStatus: '',
    origin: '',
    documentDateFrom: '',
    documentDateTo: '',
    expectedDeliveryFrom: '',
    expectedDeliveryTo: '',
    sortBy: 'expectedDeliveryDate',
  },
  Overdue: {
    search: '',
    status: 'overdue',
    vendorName: '',
    locationName: '',
    buyerName: '',
    approvalStatus: '',
    invoiceStatus: '',
    origin: '',
    documentDateFrom: '',
    documentDateTo: '',
    expectedDeliveryFrom: '',
    expectedDeliveryTo: '',
    sortBy: 'expectedDeliveryDate',
  },
}
