import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { OperationalPageShell } from '@/components/design-system/OperationalPageShell'
import { ErpCommandBar } from '@/components/erp/ErpCommandBar'
import { ErpCardSection } from '@/components/erp/card-form'
import { FormField } from '@/components/forms/FormField'
import { Input, Select } from '@/components/forms/Inputs'
import { LoadingState } from '@/design-system/components/LoadingState'
import { createJobWorkOrder, getJobWorkOrderById, getWorkOrders, updateJobWorkOrder } from '@/services/manufacturing'
import type { WorkOrder } from '@/types/manufacturingWorkOrder'
import { JW_RATE_BASIS_LABELS, type JobWorkRateBasis } from '@/types/manufacturingJobWork'
import { notify } from '@/store/toastStore'

export function JobWorkFormPage() {
  const { jobWorkId } = useParams(); const navigate = useNavigate(); const isEdit = Boolean(jobWorkId)
  const [workOrders, setWorkOrders] = useState<WorkOrder[]>([]); const [workOrderId, setWorkOrderId] = useState(''); const [vendorName, setVendorName] = useState(''); const [process, setProcess] = useState(''); const [quantity, setQuantity] = useState(1); const [rate, setRate] = useState(0); const [rateBasis, setRateBasis] = useState<JobWorkRateBasis>('per_piece'); const [expectedReturnDate, setExpectedReturnDate] = useState(new Date().toISOString().slice(0, 10)); const [loading, setLoading] = useState(isEdit); const [saving, setSaving] = useState(false)
  useEffect(() => { void getWorkOrders().then(setWorkOrders) }, [])
  useEffect(() => { if (!jobWorkId) return; void getJobWorkOrderById(jobWorkId).then((item) => { if (!item) return; setWorkOrderId(item.workOrderId); setVendorName(item.vendorName); setProcess(item.process); setQuantity(item.orderedQty); setRate(item.rate); setRateBasis(item.rateBasis); setExpectedReturnDate(item.expectedReturnDate); setLoading(false) }) }, [jobWorkId])
  const save = async () => { const wo = workOrders.find((item) => item.id === workOrderId); if (!wo || !vendorName || !process || quantity <= 0) { notify.error('Work order, vendor, process and quantity are required'); return }; setSaving(true); const input = { workOrderId: wo.id, workOrderNo: wo.woNumber, vendorId: `vendor-${vendorName.replace(/\W/g, '').toLowerCase()}`, vendorName, process, quantity, rate, rateBasis, expectedReturnDate, itemId: wo.finishedItemId, itemCode: wo.finishedItemCode, itemName: wo.finishedItemName, uom: wo.uom }; const r = isEdit && jobWorkId ? await updateJobWorkOrder(jobWorkId, input) : await createJobWorkOrder(input); setSaving(false); if (!r.ok || !r.jobWork) { notify.error(r.error ?? 'Save failed'); return }; notify.success(isEdit ? 'Job work updated' : 'Job work created'); navigate(`/manufacturing/job-work/${r.jobWork.id}`) }
  if (loading) return <LoadingState />
  return <OperationalPageShell variant="dynamics" layout="enterprise" badge="Manufacturing" title={isEdit ? 'Edit Job Work' : 'New Job Work'} breadcrumbs={[{ label: 'Manufacturing & Production', to: '/manufacturing' }, { label: 'Job Work', to: '/manufacturing/job-work' }, { label: isEdit ? 'Edit' : 'New' }]} autoBreadcrumbs={false} commandBar={<ErpCommandBar inline sticky={false} primaryAction={{ id: 'save', label: saving ? 'Saving…' : 'Save', disabled: saving, onClick: () => void save() }} secondaryActions={[{ id: 'cancel', label: 'Cancel', onClick: () => navigate('/manufacturing/job-work') }]} />}>
    <ErpCardSection title="Job work details"><div className="grid gap-3 sm:grid-cols-2"><FormField label="Work Order" required><Select id="jw-wo" value={workOrderId} onChange={(e) => setWorkOrderId(e.target.value)}><option value="">Select work order</option>{workOrders.map((wo) => <option key={wo.id} value={wo.id}>{wo.woNumber} — {wo.finishedItemCode}</option>)}</Select></FormField><FormField label="Vendor" required><Input id="jw-vendor" value={vendorName} onChange={(e) => setVendorName(e.target.value)} /></FormField><FormField label="Process" required><Input id="jw-process" value={process} onChange={(e) => setProcess(e.target.value)} /></FormField><FormField label="Quantity" required><Input id="jw-qty" type="number" min="0.001" value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} /></FormField><FormField label="Rate" required><Input id="jw-rate" type="number" min="0" value={rate} onChange={(e) => setRate(Number(e.target.value))} /></FormField><FormField label="Rate Basis"><Select id="jw-basis" value={rateBasis} onChange={(e) => setRateBasis(e.target.value as JobWorkRateBasis)}>{(Object.keys(JW_RATE_BASIS_LABELS) as JobWorkRateBasis[]).map((key) => <option key={key} value={key}>{JW_RATE_BASIS_LABELS[key]}</option>)}</Select></FormField><FormField label="Expected Return" required><Input id="jw-return" type="date" value={expectedReturnDate} onChange={(e) => setExpectedReturnDate(e.target.value)} /></FormField></div></ErpCardSection>
  </OperationalPageShell>
}
