export const PERMISSIONS = [
  'tenant.view',
  'tenant.create',
  'tenant.update',
  'tenant.delete',
  'tenant.manage',

  'user.view',
  'user.create',
  'user.update',
  'user.delete',
  'user.assign_role',

  'role.view',
  'role.create',
  'role.update',
  'role.delete',

  'crm.lead.view',
  'crm.lead.create',
  'crm.lead.update',
  'crm.lead.delete',
  'crm.lead.assign',
  'crm.lead.qualify',
  'crm.lead.convert',

  'crm.contact.view',
  'crm.contact.create',
  'crm.contact.update',
  'crm.contact.delete',

  'crm.company.view',
  'crm.company.create',
  'crm.company.update',
  'crm.company.delete',

  'crm.activity.view',
  'crm.activity.create',
  'crm.activity.update',
  'crm.activity.complete',
  'crm.activity.delete',

  'crm.pipeline.view',
  'crm.pipeline.manage',

  'crm.opportunity.view',
  'crm.opportunity.create',
  'crm.opportunity.update',
  'crm.opportunity.close',
  'crm.opportunity.delete',

  'crm.quotation.view',
  'crm.quotation.create',
  'crm.quotation.update',
  'crm.quotation.delete',
  'crm.quotation.approve',

  'crm.sales_order.view',

  'crm.follow_up.view',
  'crm.follow_up.create',
  'crm.follow_up.update',
  'crm.follow_up.delete',

  'crm.import.view',
  'crm.import.execute',

  'crm.master.view',
  'crm.master.create',
  'crm.master.update',
  'crm.master.delete',

  'crm.dashboard.view',
  'crm.report.view',
  'crm.search.view',
  'crm.export.view',
  'crm.export.execute',
  'crm.note.view',
  'crm.note.create',
  'crm.note.update',
  'crm.note.delete',
  'crm.attachment.view',
  'crm.attachment.create',
  'crm.attachment.delete',

  'master.lookup.view',

  'master.country.view',
  'master.country.create',
  'master.country.update',
  'master.country.delete',

  'master.state.view',
  'master.state.create',
  'master.state.update',
  'master.state.delete',

  'master.city.view',
  'master.city.create',
  'master.city.update',
  'master.city.delete',

  'master.uom.view',
  'master.uom.create',
  'master.uom.update',
  'master.uom.delete',

  'master.warehouse.view',
  'master.warehouse.create',
  'master.warehouse.update',
  'master.warehouse.delete',

  'master.location.view',
  'master.location.create',
  'master.location.update',
  'master.location.delete',

  'master.item_category.view',
  'master.item_category.create',
  'master.item_category.update',
  'master.item_category.delete',

  'master.hsn.view',
  'master.hsn.create',
  'master.hsn.update',
  'master.hsn.delete',

  'master.gst_group.view',
  'master.gst_group.create',
  'master.gst_group.update',
  'master.gst_group.delete',

  'master.gst_rate.view',
  'master.gst_rate.create',
  'master.gst_rate.update',
  'master.gst_rate.delete',

  'master.item.view',
  'master.item.create',
  'master.item.update',
  'master.item.delete',
  'master.item.import',

  'master.product.view',
  'master.product.create',
  'master.product.update',
  'master.product.delete',

  'master.vendor.view',
  'master.vendor.create',
  'master.vendor.update',
  'master.vendor.delete',
  'master.vendor.import',

  'master.hsn.import',
] as const

export type PermissionName = (typeof PERMISSIONS)[number]

const MASTER_VIEW_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('master.') && p.endsWith('.view'))

export const ROLE_PERMISSIONS: Record<string, PermissionName[]> = {
  'Super Admin': [...PERMISSIONS],
  'Tenant Admin': PERMISSIONS.filter((p) => p !== 'tenant.manage' && p !== 'tenant.create' && p !== 'tenant.delete'),
  'Master Data Manager': PERMISSIONS.filter((p) => p.startsWith('master.')),
  'Purchase Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'master.vendor.create',
    'master.vendor.update',
    'master.vendor.delete',
    'master.vendor.import',
  ],
  'Inventory Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'master.item.create',
    'master.item.update',
    'master.item.delete',
    'master.item.import',
    'master.item_category.create',
    'master.item_category.update',
    'master.item_category.delete',
    'master.uom.create',
    'master.uom.update',
    'master.uom.delete',
    'master.warehouse.create',
    'master.warehouse.update',
    'master.warehouse.delete',
    'master.location.create',
    'master.location.update',
    'master.location.delete',
  ],
  'Sales Manager': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update', 'crm.lead.delete', 'crm.lead.assign', 'crm.lead.qualify', 'crm.lead.convert',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update', 'crm.contact.delete',
    'crm.company.view', 'crm.company.create', 'crm.company.update', 'crm.company.delete',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete', 'crm.activity.delete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update', 'crm.follow_up.delete',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update', 'crm.opportunity.close', 'crm.opportunity.delete',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update', 'crm.quotation.delete', 'crm.quotation.approve',
    'crm.sales_order.view',
    'crm.import.view', 'crm.import.execute',
    'crm.master.view', 'crm.master.create', 'crm.master.update', 'crm.master.delete',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view', 'crm.export.view', 'crm.export.execute',
    'crm.note.view', 'crm.note.create', 'crm.note.update', 'crm.note.delete',
    'crm.attachment.view', 'crm.attachment.create', 'crm.attachment.delete',
    'user.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
  ],
  'Production Manager': [
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
    'master.item_category.view',
    'master.uom.view',
    'master.warehouse.view',
    'master.location.view',
  ],
  'CRM Admin': PERMISSIONS.filter(
    (p) => p.startsWith('crm.') || p === 'user.view' || p === 'master.product.view' || p === 'master.lookup.view',
  ),
  'Sales Executive': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update',
    'crm.company.view',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
  ],
  Viewer: [
    'crm.lead.view', 'crm.contact.view', 'crm.company.view',
    'crm.activity.view', 'crm.follow_up.view', 'crm.pipeline.view', 'crm.opportunity.view',
    'crm.quotation.view', 'crm.sales_order.view',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view',
    'user.view',
    ...MASTER_VIEW_PERMISSIONS,
  ],
}

export const DEFAULT_PIPELINE_STAGES = [
  { name: 'New', slug: 'new_lead', sequence: 1, probability: 10 },
  { name: 'Contacted', slug: 'qualified', sequence: 2, probability: 20 },
  { name: 'Qualified', slug: 'requirement_discussion', sequence: 3, probability: 35 },
  { name: 'Demo Scheduled', slug: 'technical_review', sequence: 4, probability: 45 },
  { name: 'Proposal Sent', slug: 'quotation_prepared', sequence: 5, probability: 55 },
  { name: 'Negotiation', slug: 'negotiation', sequence: 6, probability: 75 },
  { name: 'Won', slug: 'won', sequence: 7, probability: 100, isClosedWon: true },
  { name: 'Lost', slug: 'lost', sequence: 8, probability: 0, isClosedLost: true },
] as const
