-- HRMS Phase 10 — Employee Loans, Salary Advances & Payroll Recovery

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER','LEAD','CONTACT','CRM_COMPANY','OPPORTUNITY','QUOTATION','SALES_ORDER',
  'PRODUCTION_DEMAND','PRODUCTION_ORDER','DAILY_PRODUCTION_BATCH','PRODUCTION_ISSUE',
  'STOCK_MOVEMENT','STOCK_RESERVATION','PURCHASE_REQUISITION','PURCHASE_PLANNING',
  'REQUEST_FOR_QUOTATION','VENDOR_QUOTATION','VENDOR_COMPARISON','PURCHASE_ORDER',
  'GOODS_RECEIPT','QUALITY_INSPECTION','QUALITY_NCR','PURCHASE_INVOICE','PURCHASE_RETURN',
  'JOB_WORK_ORDER','PRODUCTION_RUNTIME_CHANGE','PRODUCTION_WIP_MOVEMENT','MANUFACTURING_CORRECTION',
  'PRODUCTION_PLAN','DEMAND_CONSOLIDATION_PLAN','OUTBOUND_DISPATCH','PRODUCTION_FG_RECEIPT',
  'DISPATCH_REQUIREMENT','DISPATCH_PICK_LIST','DISPATCH_PACKING_SESSION','DISPATCH_PACKAGE',
  'DELIVERY_CHALLAN','PURCHASE_QUALITY_INSPECTION','INVENTORY_TRANSFER','INVENTORY_STOCK_COUNT',
  'INVENTORY_ADJUSTMENT','MANUFACTURING_ROUTING','DISPATCH_POSTING','DISPATCH_REVERSAL',
  'MAINTENANCE_TICKET','PREVENTIVE_MAINTENANCE_PLAN','EMPLOYEE','PAYSLIP','SALARY_PAYMENT_BATCH',
  'EMPLOYEE_LOAN','SALARY_ADVANCE'
) NOT NULL;

ALTER TABLE `default_account_mappings`
  MODIFY `mappingKey` ENUM(
    'CUSTOMER_RECEIVABLE',
    'VENDOR_PAYABLE',
    'SALES_REVENUE',
    'SALES_RETURN',
    'PURCHASE',
    'PURCHASE_RETURN',
    'RAW_MATERIAL_INVENTORY',
    'WIP_INVENTORY',
    'FINISHED_GOODS_INVENTORY',
    'STOCK_ADJUSTMENT',
    'MATERIAL_CONSUMPTION',
    'GRIR_CLEARING',
    'PURCHASE_PRICE_VARIANCE',
    'COST_OF_GOODS_SOLD',
    'LABOUR_ABSORPTION',
    'MACHINE_ABSORPTION',
    'JOB_WORK_ABSORPTION',
    'PRODUCTION_OVERHEAD_ABSORPTION',
    'PRODUCTION_VARIANCE',
    'SCRAP_INVENTORY',
    'SCRAP_LOSS',
    'SUBCONTRACTING_EXPENSE',
    'FREIGHT_INWARD',
    'FREIGHT_OUTWARD',
    'GST_INPUT_CGST',
    'GST_INPUT_SGST',
    'GST_INPUT_IGST',
    'GST_OUTPUT_CGST',
    'GST_OUTPUT_SGST',
    'GST_OUTPUT_IGST',
    'GST_OUTPUT_CESS',
    'TDS_RECEIVABLE',
    'TDS_PAYABLE',
    'BANK_CHARGES',
    'ROUNDING',
    'DEPRECIATION_EXPENSE',
    'ACCUMULATED_DEPRECIATION',
    'ASSET_DISPOSAL_GAIN',
    'ASSET_DISPOSAL_LOSS',
    'FIXED_ASSET_CLEARING',
    'ASSET_REVALUATION_SURPLUS',
    'ASSET_IMPAIRMENT_LOSS',
    'RETAINED_EARNINGS',
    'INTERNAL_TRANSFER_CLEARING',
    'CHEQUE_RECEIPT_CLEARING',
    'CHEQUE_PAYMENT_CLEARING',
    'BANK_INTEREST_INCOME',
    'BANK_INTEREST_EXPENSE',
    'COLLECTION_FEE_EXPENSE',
    'MERCHANT_FEE_EXPENSE',
    'ACCRUED_EXPENSE_LIABILITY',
    'PREPAID_EXPENSE_ASSET',
    'UNREALIZED_FX_GAIN',
    'UNREALIZED_FX_LOSS',
    'SALARY_BASIC_EXPENSE',
    'SALARY_HRA_EXPENSE',
    'SALARY_ALLOWANCE_EXPENSE',
    'SALARY_OT_EXPENSE',
    'SALARY_PAYABLE',
    'PF_EMPLOYEE_PAYABLE',
    'PF_EMPLOYER_PAYABLE',
    'PF_EMPLOYER_EXPENSE',
    'ESIC_EMPLOYEE_PAYABLE',
    'ESIC_EMPLOYER_PAYABLE',
    'ESIC_EMPLOYER_EXPENSE',
    'PT_PAYABLE',
    'TDS_SALARY_PAYABLE',
    'LWF_PAYABLE',
    'LWF_EMPLOYER_PAYABLE',
    'LWF_EMPLOYER_EXPENSE',
    'EMPLOYEE_LOAN_RECEIVABLE',
    'SALARY_ADVANCE_RECEIVABLE'
  ) NOT NULL;

CREATE TABLE `hr_employee_loans` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `employeeId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `branchId` VARCHAR(191) NULL,
  `type` ENUM('LOAN','SALARY_ADVANCE') NOT NULL,
  `requestDate` DATE NOT NULL,
  `requestedAmount` DECIMAL(14, 2) NOT NULL,
  `approvedAmount` DECIMAL(14, 2) NULL,
  `disbursedAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `recoveredAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `outstandingAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `recoveryStartYear` INTEGER NULL,
  `recoveryStartMonth` INTEGER NULL,
  `installmentAmount` DECIMAL(14, 2) NULL,
  `installmentCount` INTEGER NULL,
  `reason` VARCHAR(1000) NULL,
  `status` ENUM('DRAFT','SUBMITTED','APPROVED','REJECTED','DISBURSED','RECOVERING','CLOSED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `rejectionReason` VARCHAR(500) NULL,
  `approvedByUserId` VARCHAR(191) NULL,
  `approvedAt` DATETIME(3) NULL,
  `rejectedByUserId` VARCHAR(191) NULL,
  `rejectedAt` DATETIME(3) NULL,
  `disbursedAt` DATETIME(3) NULL,
  `disbursementMethod` ENUM('BANK','CASH') NULL,
  `treasuryAccountId` VARCHAR(191) NULL,
  `disbursementReference` VARCHAR(120) NULL,
  `disbursementVoucherId` VARCHAR(191) NULL,
  `disbursementPostingEventId` VARCHAR(191) NULL,
  `closedAt` DATETIME(3) NULL,
  `closedByUserId` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_employee_loans_tenantId_code_key` (`tenantId`, `code`),
  INDEX `hr_employee_loans_tenantId_idx` (`tenantId`),
  INDEX `hr_employee_loans_tenantId_employeeId_idx` (`tenantId`, `employeeId`),
  INDEX `hr_employee_loans_tenantId_legalEntityId_idx` (`tenantId`, `legalEntityId`),
  INDEX `hr_employee_loans_tenantId_branchId_idx` (`tenantId`, `branchId`),
  INDEX `hr_employee_loans_tenantId_type_idx` (`tenantId`, `type`),
  INDEX `hr_employee_loans_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `hr_employee_loans_tenantId_deletedAt_idx` (`tenantId`, `deletedAt`),
  CONSTRAINT `hr_employee_loans_tenantId_fkey`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_employee_loans_employeeId_fkey`
    FOREIGN KEY (`employeeId`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_employee_loans_legalEntityId_fkey`
    FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_employee_loans_branchId_fkey`
    FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_loan_recovery_schedules` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `loanId` VARCHAR(191) NOT NULL,
  `installmentNo` INTEGER NOT NULL,
  `year` INTEGER NOT NULL,
  `month` INTEGER NOT NULL,
  `dueAmount` DECIMAL(14, 2) NOT NULL,
  `recoveredAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `status` ENUM('PENDING','RECOVERED','PARTIAL','SKIPPED') NOT NULL DEFAULT 'PENDING',
  `payrollRunId` VARCHAR(191) NULL,
  `payrollEmployeeResultId` VARCHAR(191) NULL,
  `skipReason` VARCHAR(500) NULL,
  `notes` VARCHAR(500) NULL,
  `recoveredAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_loan_recovery_schedules_loanId_installmentNo_key` (`loanId`, `installmentNo`),
  UNIQUE INDEX `hr_loan_recovery_schedules_loanId_year_month_key` (`loanId`, `year`, `month`),
  INDEX `hr_loan_recovery_schedules_tenantId_idx` (`tenantId`),
  INDEX `hr_loan_recovery_schedules_tenantId_loanId_idx` (`tenantId`, `loanId`),
  INDEX `hr_loan_recovery_schedules_tenantId_year_month_status_idx` (`tenantId`, `year`, `month`, `status`),
  INDEX `hr_loan_recovery_schedules_tenantId_payrollEmployeeResultId_idx` (`tenantId`, `payrollEmployeeResultId`),
  CONSTRAINT `hr_loan_recovery_schedules_tenantId_fkey`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_loan_recovery_schedules_loanId_fkey`
    FOREIGN KEY (`loanId`) REFERENCES `hr_employee_loans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_loan_repayments` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `loanId` VARCHAR(191) NOT NULL,
  `amount` DECIMAL(14, 2) NOT NULL,
  `repaymentDate` DATE NOT NULL,
  `method` ENUM('BANK','CASH','OTHER') NOT NULL,
  `treasuryAccountId` VARCHAR(191) NULL,
  `reference` VARCHAR(120) NULL,
  `reason` VARCHAR(500) NULL,
  `accountingVoucherId` VARCHAR(191) NULL,
  `postingEventId` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `hr_loan_repayments_tenantId_idx` (`tenantId`),
  INDEX `hr_loan_repayments_tenantId_loanId_idx` (`tenantId`, `loanId`),
  CONSTRAINT `hr_loan_repayments_tenantId_fkey`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_loan_repayments_loanId_fkey`
    FOREIGN KEY (`loanId`) REFERENCES `hr_employee_loans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
