/**
 * 184 — 34 m³ Tip Trailer quotation sections.
 * Source: `184.34m3 Tip Trailer.docx` (VF/QUO/26-27/184).
 */

function specRow(sectionNo: string, label: string, value: string, required = true) {
  return { sectionNo, label, value, required }
}

export const TIP_TRAILER_34M3_SEED_VERSION = 1

export const TIP_TRAILER_34M3_SEED_SECTIONS: Array<Record<string, unknown>> = [
  {
    sectionType: 'cover',
    title: 'Quotation',
    content: [
      'Ref. No.: {{reference_no}}',
      '',
      'Sub: Quotation for supply of 34 m³ Tip Semi Trailer',
      'Model VFTT-34T — 34 m³ Tri Axle Tip Semi Trailer',
      'PTO pump included with tyres',
      'High tensile steel tip trailer with Hyva tipping kit',
    ].join('\n'),
    sequenceNo: 1,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'customer_details',
    title: 'Customer Details',
    content: [
      'To,',
      '{{customer_name}}',
      '{{customer_address}}',
      '',
      'Kind Attn: {{contact_person}}',
      'Mobile: {{contact_mobile}}',
      'Email: {{contact_email}}',
    ].join('\n'),
    sequenceNo: 2,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'introduction',
    title: 'Opening Paragraph',
    content: [
      'Dear Sir,',
      '',
      'We appreciate your interest in our products and are delighted to provide the following price for {{product_name}}.',
      '',
      'Quantity: {{quantity}}',
      '34 m³ Tip Semi Trailer — PTO pump included with tyres',
    ].join('\n'),
    sequenceNo: 3,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'price_table',
    title: 'Commercial Price',
    content: '',
    sequenceNo: 4,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'specification',
    title: 'Technical Specifications',
    content: '',
    sequenceNo: 5,
    editable: true,
    contentFormat: 'spec_table',
    specRows: [
      specRow('1.1', 'Model No.', 'VFTT-34T'),
      specRow('1.2', 'Type', '34 m³ Tri Axle Tip Semi Trailer'),
      specRow('1.3', 'Tare Weight', 'Approx. 10,200 kg'),
      specRow('1.4', 'Construction', 'Tip Trailer made of High Tensile Steel'),
    ],
  },
  {
    sectionType: 'technical',
    title: 'Body Size / Dimensions',
    content: '',
    sequenceNo: 6,
    editable: true,
    contentFormat: 'spec_table',
    specRows: [
      specRow('2.1', 'Length', '9,475 mm'),
      specRow('2.2', 'Internal Length', '7,892 mm'),
      specRow('2.3', 'Width (Internal)', '2,395 mm'),
      specRow('2.4', 'Height', '3,676 mm'),
      specRow('2.5', 'Internal Height', '1,800 mm'),
    ],
  },
  {
    sectionType: 'custom',
    title: 'Construction (Plate Thickness)',
    content: '',
    sequenceNo: 7,
    editable: true,
    contentFormat: 'spec_table',
    specRows: [
      specRow('3.1', 'Side Wall', 'BSK 46, 4 mm thickness'),
      specRow('3.2', 'Floor', 'BSK 46, 5 mm thickness'),
      specRow('3.3', 'Head Board', 'BSK 46, 4 mm and 3 mm thickness'),
      specRow('3.4', 'Tail Door', 'BSK 46, 4 mm thickness'),
      specRow(
        '3.5',
        'Chassis',
        'Fabricated from High Tensile Steel 6, 8 and 10 mm with welded cross members',
      ),
    ],
  },
  {
    sectionType: 'custom',
    title: 'Electrical, Tipping & Paint',
    content: '',
    sequenceNo: 8,
    editable: true,
    contentFormat: 'spec_table',
    specRows: [
      specRow(
        '4.1',
        'Electrical',
        '24-volt electrical system with 7-pin electrical connector; parking, brake and indicator lights',
      ),
      specRow(
        '4.2',
        'Tipping Equipment',
        'Hyva Make FC-191-5-6025 type tipping kit — 45° tipping, with pump',
      ),
      specRow('4.3', 'Surface Preparation', 'Completely shot blasted'),
      specRow(
        '4.4',
        'Paint',
        'Two layers of anti-corrosive metal primer, PU surface and PU paint (without lettering)',
      ),
    ],
  },
  {
    sectionType: 'custom',
    title: 'Running Gear',
    content: '',
    sequenceNo: 9,
    editable: true,
    contentFormat: 'spec_table',
    specRows: [
      specRow(
        '5.1',
        'Axles',
        '02 Nos. York make round beam axle, 17-ton; 01 No. York make round beam axle with lift — Model 6625',
      ),
      specRow('5.2', 'Axle Capacity', '13.0 tons per axle at 105 km/hr'),
      specRow('5.3', 'Axle Beam', '6 inch (square axle beam)'),
      specRow('5.4', 'Track Length', '1,950 mm'),
      specRow('5.5', 'King Pin', '50.4 mm YORK make, bolted on 12 mm steel plate'),
      specRow(
        '5.6',
        'Suspension',
        'York Make 1 No. mono air suspension with manual lift axle; tandem mechanical suspension, 18 MT capacity',
      ),
      specRow(
        '5.7',
        'Landing Legs',
        '2-speed — static capacity 64 tons; lift capacity 28 tons per pair',
      ),
      specRow('5.8', 'Tyres', '12 Nos., 10.00×R20, MRF radial tyres'),
      specRow('5.9', 'Wheel Rims', '12 Nos., 7.5″ × 20″ 10 holes, Wheels India make'),
      specRow(
        '5.10',
        'Brakes',
        '2-line air brake system with two air tanks (70 ltrs) and mechanical slack adjusters',
      ),
      specRow(
        '5.11',
        'Relay Valve',
        'RE 6 emergency relay valve M332930 of Wabco Ltd — M 22 × 1.5 reservoir port, M 14 × 1.5 ports for service, M 16 × 1.5 ports for emergency and 4 Nos. delivery',
      ),
      specRow('5.12', 'Brake Chamber', 'Type 30, port size M 16 × 1.5, 6 Nos.'),
      specRow('5.13', 'Other Accessories', 'RUPD and full mudguard'),
    ],
  },
  {
    sectionType: 'custom',
    title: 'Optional / Chargeable Items',
    content: [
      'Extra cabin supports, extra “U” bolts, flat-belt, chassis support, truck bumper, and male coupler are chargeable if required.',
      'Any other connections and flanges required will be on chargeable basis.',
      'RTO registration tax & other charges, insurance will be extra.',
    ].join('\n'),
    sequenceNo: 10,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'scope',
    title: 'Scope of Work',
    content: [
      '1. We will manufacture the 34 m³ Tip Semi Trailer as per the above specifications.',
      '2. This is standard equipment; any changes requested by the customer will be subject to revised rates.',
      '3. Major maintenance will be done at our works. Owner has to send the vehicle by own arrangement; all expenses on owner’s account.',
      '4. RTO registration tax & other charges, insurance will be extra.',
    ].join('\n'),
    sequenceNo: 11,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'terms',
    title: 'General Sales Terms',
    content: '',
    sequenceNo: 12,
    editable: true,
    contentFormat: 'spec_table',
    specRows: [
      specRow('T.1', 'Jurisdiction', 'Subject to Chhapi Jurisdiction'),
      specRow('T.2', 'Terms of Delivery', 'Ex-works Chhapi, Banaskantha, North Gujarat'),
      specRow(
        'T.3',
        'Payment Terms',
        '40% advance with purchase order and balance against proforma invoice. Advance is non-refundable on cancellation.',
      ),
      specRow('T.4', 'Delivery Time', '8 weeks from receipt of confirmed order with advance'),
      specRow(
        'T.5',
        'Warranty',
        '12 months against defective material and workmanship. Not responsible for mishandling, accident damage, or consequential loss. No warranty on hydraulic equipment and parts; bought-out items carry OEM warranty.',
      ),
      specRow('T.6', 'Validity', 'Up to 20 days from quotation date'),
    ],
  },
  {
    sectionType: 'introduction',
    title: 'Closing Paragraph',
    content: [
      'We believe and hope that our affordable rate and other details will be acceptable to you.',
      '',
      'We anticipate accepting your esteemed buy request.',
      '',
      'Thanking you.',
      'Yours faithfully,',
    ].join('\n'),
    sequenceNo: 13,
    editable: true,
    contentFormat: 'richtext',
  },
  {
    sectionType: 'signature',
    title: 'Authorized Signatory',
    content: [
      'For, {{company_name}}',
      '',
      '',
      '{{authorized_person}}',
      '{{designation}}',
    ].join('\n'),
    sequenceNo: 14,
    editable: true,
    contentFormat: 'richtext',
  },
]
