/**
 * 76 — 26 KL ISO Tank Container quotation sections.
 * Source: `76. 26 KL ISO Tank.docx` / `76-26KL-ISO-Tank.docx` (VF/QUO/26-27/76).
 * Synced from frontend/src/data/quotations/templates/isoTank26Kl.ts
 */

export const ISO_TANK_26KL_SEED_VERSION = 9

export const ISO_TANK_26KL_SEED_SECTIONS: Array<Record<string, unknown>> = [
  {
    sectionType: "cover",
    title: "Quotation",
    content: "QUOTATION\n\nQuotation No.: {{quotation_no}}\nRef. No.: {{reference_no}}\nDate: {{quotation_date}}\n\nSub: Quotation for supply of 26 KL ISO Tank Container\nWithout Insulation (CSC, IMDG, 4G, RID, Impact Test certificate)",
    sequenceNo: 1,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "customer_details",
    title: "Customer Details",
    content: "To,\n{{customer_name}}\n{{customer_address}}\n\nKind Attn: {{contact_person}}\nMobile: {{contact_mobile}}\nEmail: {{contact_email}}",
    sequenceNo: 2,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "introduction",
    title: "Opening Paragraph",
    content: "Dear Sir,\n\nWe appreciate your interest in our products and are delighted to provide the following price for your requirement of 26 KL ISO Tank Container.\n\nWe trust that our offer will meet your technical and commercial expectations and look forward to your valued enquiry/order.",
    sequenceNo: 3,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "price_table",
    title: "Commercial Price",
    content: "",
    sequenceNo: 4,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "specification",
    title: "1.0 Technical Specifications — Tank, Dimensions & Ratings",
    content: "",
    sequenceNo: 5,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "1.1",
        label: "Tank Type",
        value: "20' ISO full frame collar tank, Type UN Portable T7",
        required: true,
      },
      {
        sectionNo: "1.2",
        label: "Design Regulations",
        value: "Tanker: ASME VIII Div. 1 (NCS), where applicable | Frame: CSC, ISO 1496/3 (ICC) | General: IMDG / ADR / RID / UN Portable Tank T7, TIR, TC, and UIC included",
        required: true,
      },
      {
        sectionNo: "1.3",
        label: "Classification Society",
        value: "BV (or as agreed)",
        required: true,
      },
      {
        sectionNo: "1.4",
        label: "Capacity (Nominal ±1%)",
        value: "26,000 Liters (26 KL)",
        required: true,
      },
      {
        sectionNo: "1.5",
        label: "Frame Dimensions",
        value: "6058 mm Long × 2438 mm Wide × 2591 mm High",
        required: true,
      },
      {
        sectionNo: "1.5.1",
        label: "Tank Dimensions",
        value: "Ø 2414 mm (I/DA) × 6020 mm (L)",
        required: true,
      },
      {
        sectionNo: "1.5.2",
        label: "Shell Calculated Thickness",
        value: "5.84 mm",
        required: true,
      },
      {
        sectionNo: "1.5.3",
        label: "Shell Corrosion Allowance",
        value: "NA",
        required: true,
      },
      {
        sectionNo: "1.5.4",
        label: "Shell Manufacture Thickness",
        value: "6.0 mm",
        required: true,
      },
      {
        sectionNo: "1.5.5",
        label: "Head Calculated Thickness",
        value: "5.84 mm",
        required: true,
      },
      {
        sectionNo: "1.5.6",
        label: "Head Corrosion Allowance",
        value: "NA",
        required: true,
      },
      {
        sectionNo: "1.5.7",
        label: "Head After Forming Thickness",
        value: "5.84 mm",
        required: true,
      },
      {
        sectionNo: "1.6",
        label: "Products",
        value: "HSD, Motor Spirit, EBMS and General Purpose Liquid",
        required: true,
      },
      {
        sectionNo: "1.7",
        label: "Tare (Nominal ±3%)",
        value: "4,200 Kg",
        required: true,
      },
      {
        sectionNo: "1.7.1",
        label: "Max. Payload",
        value: "32,200 kg",
        required: true,
      },
      {
        sectionNo: "1.7.2",
        label: "Max. Gross",
        value: "36,000 kg",
        required: true,
      },
      {
        sectionNo: "1.7.3",
        label: "Stacking Weight",
        value: "216,000 kg",
        required: true,
      },
      {
        sectionNo: "1.8",
        label: "Tank M.A.W.P.",
        value: "2.67 bar",
        required: true,
      },
      {
        sectionNo: "1.8.1",
        label: "Tank Test Pressure",
        value: "4 bar",
        required: true,
      },
      {
        sectionNo: "1.8.2",
        label: "Tank External Pressure",
        value: "0.41 bar / 5.9 psi",
        required: true,
      },
      {
        sectionNo: "1.8.3",
        label: "Tank Design Temperature",
        value: "−40°C to 130°C",
        required: true,
      },
      {
        sectionNo: "1.8.4",
        label: "Ambient Temperature",
        value: "−10°C to 65°C",
        required: true,
      },
      {
        sectionNo: "1.8.5",
        label: "Steam Tube M.A.W.P. / Test",
        value: "NA",
        required: true,
      }
    ],
  },
  {
    sectionType: "technical",
    title: "2.0 Material of Construction",
    content: "",
    sequenceNo: 6,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "2.1",
        label: "Shell Material",
        value: "SA 516 Gr 70",
        required: true,
      },
      {
        sectionNo: "2.1.1",
        label: "Dished Ends",
        value: "SA 516 Gr 70",
        required: true,
      },
      {
        sectionNo: "2.1.2",
        label: "Frame to Shell",
        value: "IS 2062 E350 or Equivalent",
        required: true,
      },
      {
        sectionNo: "2.1.3",
        label: "Steam Tubes",
        value: "NA",
        required: true,
      },
      {
        sectionNo: "2.2",
        label: "Baffle",
        value: "2 Sets",
        required: true,
      },
      {
        sectionNo: "2.3",
        label: "Vacuum Stiffening Ring — Quantity",
        value: "3 off",
        required: true,
      },
      {
        sectionNo: "2.3.1",
        label: "Vacuum Stiffening Ring — Material",
        value: "IS 2062 E350 or Equivalent",
        required: true,
      },
      {
        sectionNo: "2.3.2",
        label: "Vacuum Stiffening Ring — Remark",
        value: "Not used for steam heating",
        required: true,
      },
      {
        sectionNo: "2.4",
        label: "Framework Material",
        value: "YST 310 or Higher",
        required: true,
      },
      {
        sectionNo: "2.5",
        label: "Corner Castings",
        value: "To ISO 1161 — standard ISO castings",
        required: true,
      },
      {
        sectionNo: "2.6",
        label: "Saddles",
        value: "NA",
        required: true,
      },
      {
        sectionNo: "2.7",
        label: "Non-Destructive Examination",
        value: "As per ASME BPVC Section VIII-1",
        required: true,
      },
      {
        sectionNo: "2.7.1",
        label: "Radiography — Shell",
        value: "Spot",
        required: true,
      },
      {
        sectionNo: "2.7.2",
        label: "Radiography — Ends",
        value: "Full (100%)",
        required: true,
      },
      {
        sectionNo: "2.7.3",
        label: "Joint Efficiency — Shell",
        value: "0.85",
        required: true,
      },
      {
        sectionNo: "2.7.4",
        label: "Joint Efficiency — Ends",
        value: "1.0",
        required: true,
      }
    ],
  },
  {
    sectionType: "custom",
    title: "3.0 Surface Finish and Cleaning",
    content: "",
    sequenceNo: 7,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "3.1",
        label: "Shell Surface Finish",
        value: "Hot Rolled",
        required: true,
      },
      {
        sectionNo: "3.1.1",
        label: "Dished Ends",
        value: "As Rolled",
        required: true,
      },
      {
        sectionNo: "3.1.2",
        label: "Longitudinal Welds",
        value: "As welded",
        required: true,
      },
      {
        sectionNo: "3.1.3",
        label: "Circumferential Welds",
        value: "As welded but with 400 mm ground flush on bottom centre line",
        required: true,
      },
      {
        sectionNo: "3.1.4",
        label: "Internal Nozzle Welds",
        value: "As Welded",
        required: true,
      },
      {
        sectionNo: "3.2",
        label: "Cleaning",
        value: "On completion of fabrication, the vessel's internal surface is shot blasted and cleaned. Opening points are sealed so the tank is supplied clean and ready for use. A Cleaning Certificate will be issued by VFPL and placed in the document holder before ex-works.",
        required: true,
      }
    ],
  },
  {
    sectionType: "custom",
    title: "4.0 Tank Fittings",
    content: "",
    sequenceNo: 8,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "4.1",
        label: "Manlid",
        value: "Ø 500 mm ID — Centre spillbox — Carbon Steel, open to 135° max from rear to front, 6-point SS wing nuts, low profile; Gasket: PTFE; Dipstick and bracket: Not fitted",
        required: true,
      },
      {
        sectionNo: "4.2",
        label: "Safety Relief Valve",
        value: "2.5\" (DN 65) — Centre spillbox — SS, 3.3 bar pressure/vacuum SRV without flame proof gauze; weld-in flange fitted tangentially off centre line; Gasket: Envelope PTFE",
        required: true,
      },
      {
        sectionNo: "4.3",
        label: "Air Inlet",
        value: "1.5\" (DN40) — Rear spillbox — SS 1.5\" BSP ball valve with 1.5\" BSP outlet and dust cap on SS chain; tapped hole/plug for future pressure gauge; Gasket: N/A",
        required: true,
      },
      {
        sectionNo: "4.4",
        label: "Top Discharge Provision",
        value: "3\" (DN80) — Rear spillbox — SS recessed weld-in flange with blank flange; siphon tube retaining plate fitted; dual drilled/tapped PCD; Gasket: Envelope PTFE",
        required: true,
      },
      {
        sectionNo: "4.5",
        label: "Bottom Discharge",
        value: "3\" (DN80) — Bottom cabinet — SS 3\" 45° high-lift foot valve and 3\" clamped butterfly valves with 3\" BSP terminal and dust cap; remote cable closure; Gasket: Envelope PTFE",
        required: true,
      }
    ],
  },
  {
    sectionType: "custom",
    title: "5.0 Other Accessories",
    content: "",
    sequenceNo: 9,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "5.1",
        label: "Spillage Boxes",
        value: "Two — Hot Dip Galvanized; centre box: Manlid + SRV; rear box: air inlet + top discharge; DN25 PVC drain tubes; HDG covers open ~135°; SS label plates",
        required: true,
      },
      {
        sectionNo: "5.2",
        label: "Bottom Cabinet",
        value: "One — Hot Dip Galvanized floor and cover (open >170°) containing bottom discharge assembly; SS label plates",
        required: true,
      },
      {
        sectionNo: "5.3",
        label: "Top Longitudinal Member",
        value: "Top longitudinal rectangular members connecting front and rear end frame top corner castings",
        required: true,
      },
      {
        sectionNo: "5.4",
        label: "Bottom Longitudinal Member",
        value: "Bottom longitudinal rectangular members connecting front and rear end frames above bottom corner castings",
        required: true,
      },
      {
        sectionNo: "5.5",
        label: "Miss Stacking Pickets",
        value: "Top: miss-stacking corner plates adjacent to top castings | Bottom: cross-members recessed adjacent to corner castings",
        required: true,
      },
      {
        sectionNo: "5.6",
        label: "Walkway",
        value: "Width 475 mm, Hot dip galvanized, “A” type — two full-length longitudinal walkways (three pieces each) + three traverse walkways at Manlid spillbox, rear spillbox and front end frame",
        required: true,
      },
      {
        sectionNo: "5.7",
        label: "Handrail",
        value: "Provision space for future fitting on right-hand side",
        required: true,
      },
      {
        sectionNo: "5.8",
        label: "Ladder",
        value: "One × 300 mm wide Stainless Steel — rear end right side; bolted fasteners tack welded",
        required: true,
      },
      {
        sectionNo: "5.9",
        label: "Earth Connection",
        value: "One — Mild steel painted 40 × 30 × 3 mm with Ø9 mm hole — rear bottom cross member adjacent to ladder",
        required: true,
      },
      {
        sectionNo: "5.10",
        label: "Document Holder",
        value: "NA (Plastic Ø75 × 325 mm position reserved on RH longitudinal member if fitted)",
        required: true,
      },
      {
        sectionNo: "5.11",
        label: "Data Plate",
        value: "One SS data plate to code requirements — rear end left-hand side",
        required: true,
      },
      {
        sectionNo: "5.12",
        label: "Calibration Plate",
        value: "One SS calibration plate marked in cm/litres tack welded inside neck of central spill box",
        required: true,
      },
      {
        sectionNo: "5.13",
        label: "Statutory Decals",
        value: "Supplied and fitted by manufacturer",
        required: true,
      },
      {
        sectionNo: "5.14",
        label: "Owner Logos",
        value: "Supplied and fitted by manufacturer",
        required: true,
      }
    ],
  },
  {
    sectionType: "custom",
    title: "6.0 Painting",
    content: "",
    sequenceNo: 10,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "6.1",
        label: "Framework Treatment",
        value: "All carbon steel frame parts shot blasted to Swedish Standard SA 2½",
        required: true,
      },
      {
        sectionNo: "6.2",
        label: "Primer Coat",
        value: "Epoxy zinc rich primer — 50 microns min DFT",
        required: true,
      },
      {
        sectionNo: "6.2.1",
        label: "Intermediate Coat",
        value: "Epoxy primer — 50 microns min DFT",
        required: true,
      },
      {
        sectionNo: "6.2.2",
        label: "Top Coat",
        value: "Polyurethane — 50 microns min DFT",
        required: true,
      },
      {
        sectionNo: "6.2.3",
        label: "Total DFT",
        value: "150 microns min DFT",
        required: true,
      },
      {
        sectionNo: "6.2.4",
        label: "Colour",
        value: "As per customer details",
        required: true,
      },
      {
        sectionNo: "6.2.5",
        label: "Paint Brand",
        value: "Esdee, Asian Paints or Equivalent",
        required: true,
      },
      {
        sectionNo: "6.3",
        label: "Vessel Painting",
        value: "Same as frame paint specification",
        required: true,
      }
    ],
  },
  {
    sectionType: "custom",
    title: "7.0 Test and Approvals",
    content: "• CSC Certificate will be provided.\n• Hydro test as per design with certificate.",
    sequenceNo: 11,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "custom",
    title: "8.0 Documents to be Provided",
    content: "• Details and GA drawings with indication of the serial number\n• Technical data sheet",
    sequenceNo: 12,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "scope",
    title: "Scope of Work",
    content: "We will make the ISO tanker as per the above specifications. This is standard equipment.\nAny changes requested by the customer will be subject to revised rates.\n\nNDE / radiography as mentioned above is included.",
    sequenceNo: 13,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "terms",
    title: "General Sales Terms",
    content: "",
    sequenceNo: 14,
    editable: true,
    contentFormat: "spec_table",
    specRows: [
      {
        sectionNo: "T.1",
        label: "Jurisdiction",
        value: "Subject to Chhapi Jurisdiction",
        required: true,
      },
      {
        sectionNo: "T.2",
        label: "Terms of Delivery",
        value: "Ex works Chhapi, Banaskantha, North Gujarat",
        required: true,
      },
      {
        sectionNo: "T.3",
        label: "Payment Terms",
        value: "30% advance with purchase order; balance against proforma invoice",
        required: true,
      },
      {
        sectionNo: "T.4",
        label: "Delivery Time",
        value: "5 months from receipt of drawing approval",
        required: true,
      },
      {
        sectionNo: "T.5",
        label: "Warranty",
        value: "12 months against defective material and workmanship. Not responsible for mishandling, accident damage, or consequential loss. No warranty on hydraulic equipment; bought-out items carry OEM warranty. Major maintenance at our works — owner bears transport.",
        required: true,
      },
      {
        sectionNo: "T.6",
        label: "Extra Connections / Flanges",
        value: "Any other connection and flanges required will be on chargeable basis",
        required: true,
      },
      {
        sectionNo: "T.7",
        label: "Validity",
        value: "Up to 60 days from quotation date",
        required: true,
      }
    ],
  },
  {
    sectionType: "introduction",
    title: "Closing Paragraph",
    content: "We believe and hope that our affordable rate and other details will be acceptable to you.\nWe anticipate accepting your esteemed buy request.\n\nYours faithfully,",
    sequenceNo: 15,
    editable: true,
    contentFormat: "richtext",
  },
  {
    sectionType: "signature",
    title: "Authorized Signatory",
    content: "For, {{company_name}}\n\n\n{{authorized_person}}\n{{designation}}",
    sequenceNo: 16,
    editable: true,
    contentFormat: "richtext",
  }
]
