-- Gate & Security foundation — physical entry/exit only (no inventory / attendance / vouchers).

CREATE TABLE `gate_settings` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `payloadJson` JSON NOT NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_settings_tenantId_key` (`tenantId`),
  CONSTRAINT `gate_settings_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_locations` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `plant` VARCHAR(120) NOT NULL,
  `entryTypesAllowed` JSON NOT NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `gate_locations_tenantId_isActive_idx` (`tenantId`, `isActive`),
  CONSTRAINT `gate_locations_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_visitor_profiles` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `mobile` VARCHAR(30) NOT NULL,
  `company` VARCHAR(200) NULL,
  `email` VARCHAR(255) NULL,
  `photoUrl` VARCHAR(500) NULL,
  `idType` VARCHAR(64) NULL,
  `idReferenceMasked` VARCHAR(64) NULL,
  `lastHost` VARCHAR(200) NULL,
  `lastVehicleNumber` VARCHAR(40) NULL,
  `lastVisitAt` DATETIME(3) NULL,
  `totalVisits` INTEGER NOT NULL DEFAULT 0,
  `isBlacklisted` BOOLEAN NOT NULL DEFAULT false,
  `blacklistReason` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_visitor_profiles_tenantId_mobile_key` (`tenantId`, `mobile`),
  INDEX `gate_visitor_profiles_tenantId_isBlacklisted_idx` (`tenantId`, `isBlacklisted`),
  CONSTRAINT `gate_visitor_profiles_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_visitor_visits` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `visitorProfileId` VARCHAR(191) NULL,
  `visitorName` VARCHAR(200) NOT NULL,
  `mobile` VARCHAR(30) NOT NULL,
  `company` VARCHAR(200) NULL,
  `email` VARCHAR(255) NULL,
  `visitorType` VARCHAR(40) NOT NULL,
  `visitorCount` INTEGER NOT NULL DEFAULT 1,
  `photoUrl` VARCHAR(500) NULL,
  `idType` VARCHAR(64) NULL,
  `idReferenceMasked` VARCHAR(64) NULL,
  `hostName` VARCHAR(200) NOT NULL,
  `department` VARCHAR(120) NOT NULL,
  `purpose` VARCHAR(300) NOT NULL,
  `expectedDurationMinutes` INTEGER NULL,
  `meetingLocation` VARCHAR(200) NULL,
  `remarks` TEXT NULL,
  `vehicleNumber` VARCHAR(40) NULL,
  `vehicleType` VARCHAR(64) NULL,
  `laptopCarried` BOOLEAN NOT NULL DEFAULT false,
  `equipmentCarried` BOOLEAN NOT NULL DEFAULT false,
  `bagCount` INTEGER NOT NULL DEFAULT 0,
  `belongingsDescription` TEXT NULL,
  `safetyDeclarationAccepted` BOOLEAN NOT NULL DEFAULT false,
  `ppeRequired` BOOLEAN NOT NULL DEFAULT false,
  `ndaRequired` BOOLEAN NOT NULL DEFAULT false,
  `hostApprovalRequired` BOOLEAN NOT NULL DEFAULT false,
  `approvalStatus` VARCHAR(32) NOT NULL DEFAULT 'not_required',
  `approvalRemarks` TEXT NULL,
  `approvedBy` VARCHAR(200) NULL,
  `approvedAt` DATETIME(3) NULL,
  `gate` VARCHAR(120) NOT NULL,
  `visitDate` VARCHAR(10) NOT NULL,
  `expectedArrival` VARCHAR(64) NULL,
  `entryTime` DATETIME(3) NULL,
  `exitTime` DATETIME(3) NULL,
  `exitRemarks` TEXT NULL,
  `badgeReturned` BOOLEAN NULL,
  `instructions` TEXT NULL,
  `approvalHistoryJson` JSON NOT NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_visitor_visits_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_visitor_visits_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `gate_visitor_visits_tenantId_visitDate_idx` (`tenantId`, `visitDate`),
  INDEX `gate_visitor_visits_tenantId_mobile_idx` (`tenantId`, `mobile`),
  CONSTRAINT `gate_visitor_visits_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gate_visitor_visits_visitorProfileId_fkey` FOREIGN KEY (`visitorProfileId`) REFERENCES `gate_visitor_profiles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_expected_visitors` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `reference` VARCHAR(40) NOT NULL,
  `visitorName` VARCHAR(200) NOT NULL,
  `mobile` VARCHAR(30) NOT NULL,
  `company` VARCHAR(200) NULL,
  `visitDate` VARCHAR(10) NOT NULL,
  `expectedArrival` VARCHAR(64) NOT NULL,
  `hostName` VARCHAR(200) NOT NULL,
  `department` VARCHAR(120) NOT NULL,
  `purpose` VARCHAR(300) NOT NULL,
  `gate` VARCHAR(120) NOT NULL,
  `vehicleNumber` VARCHAR(40) NULL,
  `instructions` TEXT NULL,
  `status` VARCHAR(32) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_expected_visitors_tenantId_reference_key` (`tenantId`, `reference`),
  INDEX `gate_expected_visitors_tenantId_visitDate_status_idx` (`tenantId`, `visitDate`, `status`),
  CONSTRAINT `gate_expected_visitors_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_vehicles` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `vehicleNumber` VARCHAR(40) NOT NULL,
  `vehicleType` VARCHAR(64) NOT NULL,
  `purpose` VARCHAR(300) NOT NULL,
  `companyName` VARCHAR(200) NULL,
  `transporter` VARCHAR(200) NULL,
  `driverName` VARCHAR(200) NOT NULL,
  `driverMobile` VARCHAR(30) NULL,
  `licenceVerified` VARCHAR(32) NOT NULL DEFAULT 'not_checked',
  `relatedDocument` VARCHAR(120) NULL,
  `gate` VARCHAR(120) NOT NULL,
  `plannedLocation` VARCHAR(200) NULL,
  `currentLocation` VARCHAR(200) NULL,
  `sealNumber` VARCHAR(64) NULL,
  `remarks` TEXT NULL,
  `entryTime` DATETIME(3) NULL,
  `exitTime` DATETIME(3) NULL,
  `exitRemarks` TEXT NULL,
  `timelineJson` JSON NOT NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_vehicles_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_vehicles_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `gate_vehicles_tenantId_vehicleNumber_idx` (`tenantId`, `vehicleNumber`),
  CONSTRAINT `gate_vehicles_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_material_inwards` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `inwardType` VARCHAR(40) NOT NULL,
  `vendorName` VARCHAR(200) NULL,
  `poNumber` VARCHAR(80) NULL,
  `challanNumber` VARCHAR(80) NULL,
  `invoiceNumber` VARCHAR(80) NULL,
  `lrNumber` VARCHAR(80) NULL,
  `vehicleNumber` VARCHAR(40) NULL,
  `vehicleType` VARCHAR(64) NULL,
  `transporter` VARCHAR(200) NULL,
  `driverName` VARCHAR(200) NULL,
  `driverMobile` VARCHAR(30) NULL,
  `sealNumber` VARCHAR(64) NULL,
  `materialSummary` VARCHAR(500) NOT NULL,
  `packages` INTEGER NOT NULL DEFAULT 0,
  `approxQty` DOUBLE NULL,
  `uom` VARCHAR(32) NULL,
  `grossWeight` VARCHAR(64) NULL,
  `warehouse` VARCHAR(120) NULL,
  `unloadingLocation` VARCHAR(200) NULL,
  `documentPhotoUrl` VARCHAR(500) NULL,
  `materialPhotoUrl` VARCHAR(500) NULL,
  `remarks` TEXT NULL,
  `gate` VARCHAR(120) NOT NULL,
  `arrivalTime` DATETIME(3) NULL,
  `linesJson` JSON NOT NULL,
  `linkedGrnNumber` VARCHAR(80) NULL,
  `linkedQcNumber` VARCHAR(80) NULL,
  `timelineJson` JSON NOT NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_material_inwards_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_material_inwards_tenantId_status_idx` (`tenantId`, `status`),
  CONSTRAINT `gate_material_inwards_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_material_outwards` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `outwardType` VARCHAR(40) NOT NULL,
  `documentType` VARCHAR(80) NOT NULL,
  `documentNumber` VARCHAR(80) NOT NULL,
  `documentApproved` BOOLEAN NOT NULL DEFAULT false,
  `partyName` VARCHAR(200) NULL,
  `vehicleNumber` VARCHAR(40) NULL,
  `driverName` VARCHAR(200) NULL,
  `driverMobile` VARCHAR(30) NULL,
  `transporter` VARCHAR(200) NULL,
  `sealNumber` VARCHAR(64) NULL,
  `materialSummary` VARCHAR(500) NOT NULL,
  `packagesExpected` INTEGER NOT NULL DEFAULT 0,
  `packagesVerified` INTEGER NULL,
  `approvalStatus` VARCHAR(32) NOT NULL DEFAULT 'not_required',
  `plannedTime` DATETIME(3) NULL,
  `releasedAt` DATETIME(3) NULL,
  `releasedBy` VARCHAR(200) NULL,
  `holdRemarks` TEXT NULL,
  `mismatchRemarks` TEXT NULL,
  `rejectRemarks` TEXT NULL,
  `checklistJson` JSON NOT NULL,
  `gate` VARCHAR(120) NOT NULL,
  `linesJson` JSON NOT NULL,
  `timelineJson` JSON NOT NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_material_outwards_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_material_outwards_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `gate_material_outwards_tenantId_documentNumber_idx` (`tenantId`, `documentNumber`),
  CONSTRAINT `gate_material_outwards_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_passes` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `passKind` VARCHAR(32) NOT NULL,
  `movementType` VARCHAR(80) NOT NULL,
  `department` VARCHAR(120) NOT NULL,
  `responsibleEmployee` VARCHAR(200) NOT NULL,
  `carriedBy` VARCHAR(200) NOT NULL,
  `partyName` VARCHAR(200) NULL,
  `purpose` VARCHAR(300) NOT NULL,
  `outwardDate` DATETIME(3) NOT NULL,
  `expectedReturnDate` DATETIME(3) NULL,
  `approverName` VARCHAR(200) NULL,
  `approvalStatus` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `approvalRemarks` TEXT NULL,
  `returnsJson` JSON NOT NULL,
  `gate` VARCHAR(120) NOT NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_passes_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_passes_tenantId_status_idx` (`tenantId`, `status`),
  CONSTRAINT `gate_passes_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_pass_items` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `gatePassId` VARCHAR(191) NOT NULL,
  `itemDescription` VARCHAR(500) NOT NULL,
  `serialNumber` VARCHAR(120) NULL,
  `quantity` DOUBLE NOT NULL,
  `uom` VARCHAR(32) NOT NULL,
  `conditionOut` VARCHAR(200) NULL,
  `returnedQuantity` DOUBLE NOT NULL DEFAULT 0,
  `remarks` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `gate_pass_items_tenantId_gatePassId_idx` (`tenantId`, `gatePassId`),
  CONSTRAINT `gate_pass_items_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gate_pass_items_gatePassId_fkey` FOREIGN KEY (`gatePassId`) REFERENCES `gate_passes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_contractor_entries` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `workerName` VARCHAR(200) NOT NULL,
  `mobile` VARCHAR(30) NOT NULL,
  `contractorCompany` VARCHAR(200) NOT NULL,
  `workReference` VARCHAR(120) NULL,
  `department` VARCHAR(120) NOT NULL,
  `supervisor` VARCHAR(200) NOT NULL,
  `workLocation` VARCHAR(200) NOT NULL,
  `validFrom` VARCHAR(10) NOT NULL,
  `validUntil` VARCHAR(10) NOT NULL,
  `safetyInductionDone` BOOLEAN NOT NULL DEFAULT false,
  `ppeIssued` BOOLEAN NOT NULL DEFAULT false,
  `toolsCarried` TEXT NULL,
  `photoUrl` VARCHAR(500) NULL,
  `purpose` VARCHAR(300) NOT NULL,
  `remarks` TEXT NULL,
  `gate` VARCHAR(120) NOT NULL,
  `entryTime` DATETIME(3) NULL,
  `exitTime` DATETIME(3) NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_contractor_entries_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_contractor_entries_tenantId_status_idx` (`tenantId`, `status`),
  CONSTRAINT `gate_contractor_entries_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_courier_entries` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `entryNumber` VARCHAR(40) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `direction` VARCHAR(16) NOT NULL,
  `courierCompany` VARCHAR(120) NOT NULL,
  `trackingNumber` VARCHAR(80) NULL,
  `senderName` VARCHAR(200) NULL,
  `recipientEmployee` VARCHAR(200) NULL,
  `department` VARCHAR(120) NULL,
  `parcelType` VARCHAR(80) NULL,
  `parcelDescription` TEXT NULL,
  `receivedTime` DATETIME(3) NULL,
  `receivedBy` VARCHAR(200) NULL,
  `handoverTime` DATETIME(3) NULL,
  `handedOverTo` VARCHAR(200) NULL,
  `dispatchTime` DATETIME(3) NULL,
  `charges` DOUBLE NULL,
  `remarks` TEXT NULL,
  `gate` VARCHAR(120) NOT NULL,
  `createdBy` VARCHAR(200) NOT NULL,
  `updatedBy` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_courier_entries_tenantId_entryNumber_key` (`tenantId`, `entryNumber`),
  INDEX `gate_courier_entries_tenantId_status_idx` (`tenantId`, `status`),
  CONSTRAINT `gate_courier_entries_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_approvals` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `requestNumber` VARCHAR(40) NOT NULL,
  `requestType` VARCHAR(40) NOT NULL,
  `requestedBy` VARCHAR(200) NOT NULL,
  `subject` VARCHAR(500) NOT NULL,
  `reason` TEXT NOT NULL,
  `requestedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `priority` VARCHAR(16) NOT NULL DEFAULT 'normal',
  `status` VARCHAR(32) NOT NULL,
  `sourceType` VARCHAR(40) NOT NULL,
  `sourceId` VARCHAR(191) NOT NULL,
  `actionedBy` VARCHAR(200) NULL,
  `actionedAt` DATETIME(3) NULL,
  `actionRemarks` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gate_approvals_tenantId_requestNumber_key` (`tenantId`, `requestNumber`),
  INDEX `gate_approvals_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `gate_approvals_tenantId_sourceType_sourceId_idx` (`tenantId`, `sourceType`, `sourceId`),
  CONSTRAINT `gate_approvals_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `gate_activities` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `event` VARCHAR(40) NOT NULL,
  `recordType` VARCHAR(40) NOT NULL,
  `recordId` VARCHAR(191) NOT NULL,
  `recordLabel` VARCHAR(500) NOT NULL,
  `company` VARCHAR(200) NULL,
  `gate` VARCHAR(120) NOT NULL,
  `operator` VARCHAR(200) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gate_activities_tenantId_time_idx` (`tenantId`, `time`),
  CONSTRAINT `gate_activities_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
