/** Geography master seed — countries, Indian states/UTs, and major cities */

export const GEO_COUNTRY_SEED: Array<{ code: string; name: string }> = [
  { code: 'IN', name: 'India' },
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AU', name: 'Australia' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'CA', name: 'Canada' },
  { code: 'CN', name: 'China' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IT', name: 'Italy' },
  { code: 'JP', name: 'Japan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'OM', name: 'Oman' },
  { code: 'QA', name: 'Qatar' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'TH', name: 'Thailand' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'VN', name: 'Vietnam' },
]

export const GEO_STATE_SEED: Array<{ code: string; name: string }> = [
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'CT', name: 'Chhattisgarh' },
  { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HR', name: 'Haryana' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'JK', name: 'Jammu and Kashmir' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'MN', name: 'Manipur' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OR', name: 'Odisha' },
  { code: 'PY', name: 'Puducherry' },
  { code: 'PB', name: 'Punjab' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TS', name: 'Telangana' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UK', name: 'Uttarakhand' },
  { code: 'WB', name: 'West Bengal' },
]

/** Cities keyed by state code — major commercial / industrial hubs */
export const GEO_CITY_SEED: Record<string, string[]> = {
  AN: ['Port Blair'],
  AP: ['Visakhapatnam', 'Vijayawada', 'Tirupati', 'Guntur'],
  AR: ['Itanagar'],
  AS: ['Guwahati', 'Dibrugarh', 'Silchar'],
  BR: ['Patna', 'Gaya', 'Muzaffarpur'],
  CH: ['Chandigarh'],
  CT: ['Raipur', 'Bhilai', 'Bilaspur'],
  DN: ['Silvassa', 'Daman'],
  DL: ['New Delhi', 'Delhi'],
  GA: ['Panaji', 'Margao', 'Vasco da Gama'],
  GJ: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Vapi', 'Gandhinagar', 'Bhavnagar', 'Jamnagar'],
  HR: ['Gurugram', 'Faridabad', 'Panipat', 'Ambala'],
  HP: ['Shimla', 'Solan', 'Dharamshala'],
  JK: ['Srinagar', 'Jammu'],
  JH: ['Ranchi', 'Jamshedpur', 'Dhanbad'],
  KA: ['Bengaluru', 'Mysuru', 'Hubli', 'Mangaluru', 'Belagavi'],
  KL: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur'],
  LA: ['Leh'],
  LD: ['Kavaratti'],
  MP: ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior'],
  MH: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Thane', 'Navi Mumbai', 'Kolhapur'],
  MN: ['Imphal'],
  ML: ['Shillong'],
  MZ: ['Aizawl'],
  NL: ['Kohima', 'Dimapur'],
  OR: ['Bhubaneswar', 'Cuttack', 'Rourkela'],
  PY: ['Puducherry'],
  PB: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Mohali'],
  RJ: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Ajmer'],
  SK: ['Gangtok'],
  TN: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'],
  TS: ['Hyderabad', 'Warangal', 'Karimnagar'],
  TR: ['Agartala'],
  UP: ['Lucknow', 'Kanpur', 'Varanasi', 'Noida', 'Ghaziabad', 'Agra'],
  UK: ['Dehradun', 'Haridwar', 'Haldwani'],
  WB: ['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri'],
}
