-- Dispatch Phase 7C4 — Delivery Challan (document only; no stock / fulfilment posting).

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER', 'LEAD', 'CONTACT', 'CRM_COMPANY', 'OPPORTUNITY', 'QUOTATION', 'SALES_ORDER',
  'PRODUCTION_DEMAND', 'PRODUCTION_ORDER', 'DAILY_PRODUCTION_BATCH', 'PRODUCTION_ISSUE',
  'STOCK_MOVEMENT', 'STOCK_RESERVATION', 'PURCHASE_REQUISITION',
  'QUALITY_INSPECTION', 'QUALITY_NCR', 'JOB_WORK_ORDER', 'PRODUCTION_RUNTIME_CHANGE',
  'PRODUCTION_WIP_MOVEMENT', 'MANUFACTURING_CORRECTION', 'PRODUCTION_PLAN',
  'DEMAND_CONSOLIDATION_PLAN', 'OUTBOUND_DISPATCH', 'PRODUCTION_FG_RECEIPT',
  'DISPATCH_REQUIREMENT', 'DISPATCH_PICK_LIST', 'DISPATCH_PACKING_SESSION', 'DISPATCH_PACKAGE',
  'DELIVERY_CHALLAN'
) NOT NULL;

CREATE TABLE `delivery_challans` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `challanNumber` VARCHAR(64) NULL,
  `status` ENUM('DRAFT', 'READY_FOR_REVIEW', 'APPROVED', 'ISSUED', 'SENT_BACK', 'CANCELLED', 'SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
  `versionNumber` INT NOT NULL DEFAULT 1,
  `supersedesChallanId` VARCHAR(191) NULL,
  `supersededByChallanId` VARCHAR(191) NULL,
  `outboundDispatchId` VARCHAR(191) NOT NULL,
  `packingSessionId` VARCHAR(191) NOT NULL,
  `customerId` VARCHAR(191) NULL,
  `shipToKey` VARCHAR(200) NULL,
  `sourceWarehouseId` VARCHAR(191) NOT NULL,
  `documentDate` DATE NOT NULL,
  `movementDate` DATE NULL,
  `movementReason` ENUM('SALES_DELIVERY', 'JOB_WORK_DISPATCH', 'SAMPLE', 'DEMONSTRATION', 'REPAIR', 'REPLACEMENT', 'STOCK_TRANSFER', 'RETURNABLE_MATERIAL', 'NON_RETURNABLE_MATERIAL', 'OTHER') NOT NULL DEFAULT 'SALES_DELIVERY',
  `transportMode` VARCHAR(64) NULL,
  `transporterName` VARCHAR(200) NULL,
  `transporterDocumentRef` VARCHAR(100) NULL,
  `vehicleNumber` VARCHAR(64) NULL,
  `driverName` VARCHAR(120) NULL,
  `driverPhone` VARCHAR(32) NULL,
  `lrGrNumber` VARCHAR(100) NULL,
  `lrGrDate` DATE NULL,
  `eWayBillReference` VARCHAR(100) NULL,
  `eWayBillDate` DATE NULL,
  `destination` VARCHAR(300) NULL,
  `totalPackages` INT NOT NULL DEFAULT 0,
  `totalQuantity` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `grossWeight` DECIMAL(18, 4) NULL,
  `netWeight` DECIMAL(18, 4) NULL,
  `weightUomId` VARCHAR(191) NULL,
  `remarks` TEXT NULL,
  `termsText` TEXT NULL,
  `sourceVersion` INT NOT NULL DEFAULT 1,
  `sourceFingerprint` VARCHAR(128) NULL,
  `customerSnapshotJson` JSON NULL,
  `shipToSnapshotJson` JSON NULL,
  `legalEntitySnapshotJson` JSON NULL,
  `salesOrderRefsJson` JSON NULL,
  `documentHtml` LONGTEXT NULL,
  `documentGenStatus` ENUM('NOT_GENERATED', 'GENERATING', 'GENERATED', 'FAILED', 'SUPERSEDED') NOT NULL DEFAULT 'NOT_GENERATED',
  `documentFileKey` VARCHAR(500) NULL,
  `documentGenError` TEXT NULL,
  `issuedAt` DATETIME(3) NULL,
  `issuedBy` VARCHAR(191) NULL,
  `approvedAt` DATETIME(3) NULL,
  `approvedBy` VARCHAR(191) NULL,
  `cancelledAt` DATETIME(3) NULL,
  `cancelledBy` VARCHAR(191) NULL,
  `cancellationReason` TEXT NULL,
  `sentBackAt` DATETIME(3) NULL,
  `sentBackBy` VARCHAR(191) NULL,
  `sendBackReason` TEXT NULL,
  `idempotencyKey` VARCHAR(150) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `delivery_challan_tenant_number_uidx`(`tenantId`, `challanNumber`),
  UNIQUE INDEX `delivery_challan_tenant_idem_uidx`(`tenantId`, `idempotencyKey`),
  INDEX `delivery_challan_tenant_status_idx`(`tenantId`, `status`),
  INDEX `delivery_challan_tenant_ob_idx`(`tenantId`, `outboundDispatchId`),
  INDEX `delivery_challan_tenant_pack_sess_idx`(`tenantId`, `packingSessionId`),
  INDEX `delivery_challan_tenant_customer_idx`(`tenantId`, `customerId`),
  INDEX `delivery_challan_tenant_doc_date_idx`(`tenantId`, `documentDate`),
  INDEX `delivery_challan_tenant_issued_idx`(`tenantId`, `issuedAt`),
  INDEX `delivery_challan_tenant_del_idx`(`tenantId`, `deletedAt`),
  CONSTRAINT `delivery_challans_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challans_outboundDispatchId_fkey` FOREIGN KEY (`outboundDispatchId`) REFERENCES `outbound_dispatches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challans_packingSessionId_fkey` FOREIGN KEY (`packingSessionId`) REFERENCES `dispatch_packing_sessions`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challans_sourceWarehouseId_fkey` FOREIGN KEY (`sourceWarehouseId`) REFERENCES `master_warehouses`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challans_weightUomId_fkey` FOREIGN KEY (`weightUomId`) REFERENCES `master_uoms`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `delivery_challans_supersedesChallanId_fkey` FOREIGN KEY (`supersedesChallanId`) REFERENCES `delivery_challans`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `delivery_challan_lines` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `deliveryChallanId` VARCHAR(191) NOT NULL,
  `lineNumber` INT NOT NULL,
  `outboundDispatchLineId` VARCHAR(191) NOT NULL,
  `dispatchRequirementId` VARCHAR(191) NULL,
  `salesOrderId` VARCHAR(191) NULL,
  `salesOrderLineId` VARCHAR(64) NULL,
  `packingSessionId` VARCHAR(191) NULL,
  `itemId` VARCHAR(191) NOT NULL,
  `itemCodeSnapshot` VARCHAR(64) NOT NULL,
  `itemNameSnapshot` VARCHAR(300) NOT NULL,
  `itemDescriptionSnapshot` TEXT NULL,
  `hsnSacSnapshot` VARCHAR(16) NULL,
  `uomId` VARCHAR(191) NULL,
  `uomCodeSnapshot` VARCHAR(32) NULL,
  `packedQuantity` DECIMAL(18, 4) NOT NULL,
  `challanQuantity` DECIMAL(18, 4) NOT NULL,
  `packageCount` INT NULL,
  `grossWeight` DECIMAL(18, 4) NULL,
  `netWeight` DECIMAL(18, 4) NULL,
  `remarks` TEXT NULL,
  `sourceVersion` INT NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `delivery_challan_line_challan_line_uidx`(`deliveryChallanId`, `lineNumber`),
  INDEX `delivery_challan_line_tenant_challan_idx`(`tenantId`, `deliveryChallanId`),
  INDEX `delivery_challan_line_tenant_ob_line_idx`(`tenantId`, `outboundDispatchLineId`),
  INDEX `delivery_challan_line_tenant_so_line_idx`(`tenantId`, `salesOrderLineId`),
  INDEX `delivery_challan_line_tenant_item_idx`(`tenantId`, `itemId`),
  CONSTRAINT `delivery_challan_lines_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challan_lines_deliveryChallanId_fkey` FOREIGN KEY (`deliveryChallanId`) REFERENCES `delivery_challans`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `delivery_challan_packages` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `deliveryChallanId` VARCHAR(191) NOT NULL,
  `packageId` VARCHAR(191) NOT NULL,
  `packageNumberSnapshot` VARCHAR(64) NOT NULL,
  `packageTypeSnapshot` VARCHAR(64) NULL,
  `grossWeight` DECIMAL(18, 4) NULL,
  `netWeight` DECIMAL(18, 4) NULL,
  `dimensionsSnapshot` VARCHAR(200) NULL,
  `sealNumberSnapshot` VARCHAR(64) NULL,
  `status` ENUM('ACTIVE', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  UNIQUE INDEX `delivery_challan_pkg_challan_pkg_uidx`(`deliveryChallanId`, `packageId`),
  INDEX `delivery_challan_pkg_tenant_challan_idx`(`tenantId`, `deliveryChallanId`),
  INDEX `delivery_challan_pkg_tenant_pkg_idx`(`tenantId`, `packageId`),
  CONSTRAINT `delivery_challan_packages_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challan_packages_deliveryChallanId_fkey` FOREIGN KEY (`deliveryChallanId`) REFERENCES `delivery_challans`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `delivery_challan_packages_packageId_fkey` FOREIGN KEY (`packageId`) REFERENCES `dispatch_packages`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `delivery_challan_tracking_allocations` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `deliveryChallanId` VARCHAR(191) NOT NULL,
  `deliveryChallanLineId` VARCHAR(191) NOT NULL,
  `packageId` VARCHAR(191) NULL,
  `lotRef` VARCHAR(100) NULL,
  `serialRef` VARCHAR(100) NULL,
  `heatNumber` VARCHAR(100) NULL,
  `quantity` DECIMAL(18, 4) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  INDEX `delivery_challan_trk_tenant_line_idx`(`tenantId`, `deliveryChallanLineId`),
  INDEX `delivery_challan_trk_tenant_challan_idx`(`tenantId`, `deliveryChallanId`),
  INDEX `delivery_challan_trk_tenant_serial_idx`(`tenantId`, `serialRef`),
  INDEX `delivery_challan_trk_tenant_lot_idx`(`tenantId`, `lotRef`),
  CONSTRAINT `delivery_challan_tracking_allocations_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_challan_tracking_allocations_deliveryChallanId_fkey` FOREIGN KEY (`deliveryChallanId`) REFERENCES `delivery_challans`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `delivery_challan_tracking_allocations_deliveryChallanLineId_fkey` FOREIGN KEY (`deliveryChallanLineId`) REFERENCES `delivery_challan_lines`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
