import type { ReceiptValidationIssue } from './customer-receipt-calculation.types.js'

export function receiptError(
  code: string,
  message: string,
  field?: string,
  extras?: Partial<Pick<ReceiptValidationIssue, 'rowIndex' | 'invoiceId' | 'invoiceOpenItemId' | 'details'>>,
): ReceiptValidationIssue {
  return {
    code,
    message,
    field,
    severity: 'ERROR',
    ...extras,
  }
}

export function receiptWarning(
  code: string,
  message: string,
  field?: string,
  extras?: Partial<Pick<ReceiptValidationIssue, 'rowIndex' | 'invoiceId' | 'invoiceOpenItemId' | 'details'>>,
): ReceiptValidationIssue {
  return {
    code,
    message,
    field,
    severity: 'WARNING',
    ...extras,
  }
}

/** Controlled customer-TDS percentage values (common Indian rates). */
export const CONTROLLED_TDS_PERCENTAGES = ['0', '0.1', '1', '2', '5', '10'] as const

/** Default maximum TDS percentage when finance config is absent. */
export const DEFAULT_MAX_TDS_PERCENTAGE = '100'

export const RECEIPT_ERROR_CODES = {
  CUSTOMER_RECEIPT_AMOUNT_REQUIRED: 'CUSTOMER_RECEIPT_AMOUNT_REQUIRED',
  CUSTOMER_RECEIPT_BANK_AMOUNT_INVALID: 'CUSTOMER_RECEIPT_BANK_AMOUNT_INVALID',
  CUSTOMER_RECEIPT_GROSS_AMOUNT_INVALID: 'CUSTOMER_RECEIPT_GROSS_AMOUNT_INVALID',
  CUSTOMER_RECEIPT_ALLOCATABLE_AMOUNT_INVALID: 'CUSTOMER_RECEIPT_ALLOCATABLE_AMOUNT_INVALID',
  CUSTOMER_RECEIPT_UNALLOCATED_AMOUNT_INVALID: 'CUSTOMER_RECEIPT_UNALLOCATED_AMOUNT_INVALID',
  CUSTOMER_TDS_AMOUNT_INVALID: 'CUSTOMER_TDS_AMOUNT_INVALID',
  CUSTOMER_TDS_PERCENTAGE_INVALID: 'CUSTOMER_TDS_PERCENTAGE_INVALID',
  CUSTOMER_TDS_BASE_REQUIRED: 'CUSTOMER_TDS_BASE_REQUIRED',
  CUSTOMER_TDS_ACCOUNT_MISSING: 'CUSTOMER_TDS_ACCOUNT_MISSING',
  CUSTOMER_TDS_CALCULATION_INVALID: 'CUSTOMER_TDS_CALCULATION_INVALID',
  BANK_CHARGE_AMOUNT_INVALID: 'BANK_CHARGE_AMOUNT_INVALID',
  BANK_CHARGE_ACCOUNT_MISSING: 'BANK_CHARGE_ACCOUNT_MISSING',
  OTHER_DEDUCTION_AMOUNT_INVALID: 'OTHER_DEDUCTION_AMOUNT_INVALID',
  OTHER_DEDUCTION_ACCOUNT_MISSING: 'OTHER_DEDUCTION_ACCOUNT_MISSING',
  RECEIPT_CUSTOMER_NOT_FOUND: 'RECEIPT_CUSTOMER_NOT_FOUND',
  RECEIPT_CUSTOMER_INACTIVE: 'RECEIPT_CUSTOMER_INACTIVE',
  RECEIPT_BANK_CASH_ACCOUNT_MISSING: 'RECEIPT_BANK_CASH_ACCOUNT_MISSING',
  RECEIPT_BANK_CASH_ACCOUNT_INVALID: 'RECEIPT_BANK_CASH_ACCOUNT_INVALID',
  RECEIPT_RECEIVABLE_ACCOUNT_MISSING: 'RECEIPT_RECEIVABLE_ACCOUNT_MISSING',
  RECEIPT_RECEIVABLE_ACCOUNT_INVALID: 'RECEIPT_RECEIVABLE_ACCOUNT_INVALID',
  RECEIPT_PAYMENT_METHOD_INVALID: 'RECEIPT_PAYMENT_METHOD_INVALID',
  RECEIPT_INSTRUMENT_NUMBER_REQUIRED: 'RECEIPT_INSTRUMENT_NUMBER_REQUIRED',
  RECEIPT_INSTRUMENT_DATE_REQUIRED: 'RECEIPT_INSTRUMENT_DATE_REQUIRED',
  RECEIPT_TRANSACTION_REFERENCE_REQUIRED: 'RECEIPT_TRANSACTION_REFERENCE_REQUIRED',
  RECEIPT_CURRENCY_INVALID: 'RECEIPT_CURRENCY_INVALID',
  RECEIPT_EXCHANGE_RATE_INVALID: 'RECEIPT_EXCHANGE_RATE_INVALID',
  RECEIPT_MULTI_CURRENCY_DISABLED: 'RECEIPT_MULTI_CURRENCY_DISABLED',
  RECEIPT_POSTING_DATE_INVALID: 'RECEIPT_POSTING_DATE_INVALID',
  RECEIPT_POSTING_PERIOD_CLOSED: 'RECEIPT_POSTING_PERIOD_CLOSED',
  RECEIPT_POSTING_PERIOD_UNDER_REVIEW: 'RECEIPT_POSTING_PERIOD_UNDER_REVIEW',
  RECEIPT_ALLOCATION_AMOUNT_INVALID: 'RECEIPT_ALLOCATION_AMOUNT_INVALID',
  RECEIPT_ALLOCATION_EXCEEDS_RECEIPT: 'RECEIPT_ALLOCATION_EXCEEDS_RECEIPT',
  RECEIPT_ALLOCATION_EXCEEDS_INVOICE: 'RECEIPT_ALLOCATION_EXCEEDS_INVOICE',
  RECEIPT_ALLOCATION_CUSTOMER_MISMATCH: 'RECEIPT_ALLOCATION_CUSTOMER_MISMATCH',
  RECEIPT_ALLOCATION_CURRENCY_MISMATCH: 'RECEIPT_ALLOCATION_CURRENCY_MISMATCH',
  RECEIPT_ALLOCATION_OPEN_ITEM_INVALID: 'RECEIPT_ALLOCATION_OPEN_ITEM_INVALID',
  RECEIPT_ALLOCATION_DUPLICATE: 'RECEIPT_ALLOCATION_DUPLICATE',
  RECEIPT_POSTING_PREVIEW_UNBALANCED: 'RECEIPT_POSTING_PREVIEW_UNBALANCED',
} as const

export const RECEIPT_WARNING_CODES = {
  RECEIPT_REFERENCE_MISSING: 'RECEIPT_REFERENCE_MISSING',
  CUSTOMER_GSTIN_MISSING: 'CUSTOMER_GSTIN_MISSING',
  CUSTOMER_PAN_MISSING: 'CUSTOMER_PAN_MISSING',
  CUSTOMER_TDS_BASE_USER_SUPPLIED: 'CUSTOMER_TDS_BASE_USER_SUPPLIED',
  CUSTOMER_TDS_SECTION_NOT_PROVIDED: 'CUSTOMER_TDS_SECTION_NOT_PROVIDED',
  CHEQUE_CLEARING_NOT_TRACKED: 'CHEQUE_CLEARING_NOT_TRACKED',
  CUSTOM_PAYMENT_METHOD_USED: 'CUSTOM_PAYMENT_METHOD_USED',
  UNALLOCATED_RECEIPT_REMAINS: 'UNALLOCATED_RECEIPT_REMAINS',
  PARTIAL_INVOICE_ALLOCATION: 'PARTIAL_INVOICE_ALLOCATION',
  RECEIPT_VALUE_DATE_DIFFERS: 'RECEIPT_VALUE_DATE_DIFFERS',
  BACKDATED_RECEIPT: 'BACKDATED_RECEIPT',
  LARGE_RECEIPT_AMOUNT: 'LARGE_RECEIPT_AMOUNT',
  OTHER_DEDUCTION_REVIEW_REQUIRED: 'OTHER_DEDUCTION_REVIEW_REQUIRED',
  CUSTOM_TDS_RATE_USED: 'CUSTOM_TDS_RATE_USED',
} as const
