import { AppError } from '../../../utils/errors.js'

export type ApprovalErrorCode =
  | 'APPROVAL_REQUEST_NOT_FOUND'
  | 'APPROVAL_REQUEST_ALREADY_EXISTS'
  | 'APPROVAL_REQUEST_MISSING'
  | 'APPROVAL_REQUEST_NOT_PENDING'
  | 'APPROVAL_STEP_NOT_FOUND'
  | 'APPROVAL_STEP_NOT_PENDING'
  | 'APPROVAL_STEP_NOT_CURRENT'
  | 'APPROVER_NOT_ELIGIBLE'
  | 'SELF_APPROVAL_NOT_ALLOWED'
  | 'APPROVAL_COMMENTS_REQUIRED'
  | 'JOURNAL_NOT_PENDING_APPROVAL'
  | 'JOURNAL_ALREADY_APPROVED'
  | 'JOURNAL_ALREADY_REJECTED'
  | 'APPROVAL_WORKFLOW_INCOMPLETE'
  | 'APPROVAL_RULE_CONFIGURATION_INVALID'
  | 'APPROVAL_CONCURRENT_ACTION'
  | 'APPROVAL_UNAUTHORIZED'
  // Legacy aliases kept for existing call sites / tests
  | 'APPROVAL_NOT_FOUND'
  | 'APPROVAL_NOT_PENDING'
  | 'APPROVAL_NOT_ELIGIBLE'
  | 'APPROVAL_PENDING_EXISTS'
  | 'APPROVAL_DOCUMENT_WRONG_STATUS'
  | 'APPROVAL_WORKFLOW_EMPTY'

const STATUS_BY_CODE: Record<ApprovalErrorCode, number> = {
  APPROVAL_REQUEST_NOT_FOUND: 404,
  APPROVAL_REQUEST_ALREADY_EXISTS: 409,
  APPROVAL_REQUEST_MISSING: 422,
  APPROVAL_REQUEST_NOT_PENDING: 422,
  APPROVAL_STEP_NOT_FOUND: 422,
  APPROVAL_STEP_NOT_PENDING: 422,
  APPROVAL_STEP_NOT_CURRENT: 422,
  APPROVER_NOT_ELIGIBLE: 403,
  SELF_APPROVAL_NOT_ALLOWED: 403,
  APPROVAL_COMMENTS_REQUIRED: 400,
  JOURNAL_NOT_PENDING_APPROVAL: 422,
  JOURNAL_ALREADY_APPROVED: 422,
  JOURNAL_ALREADY_REJECTED: 422,
  APPROVAL_WORKFLOW_INCOMPLETE: 422,
  APPROVAL_RULE_CONFIGURATION_INVALID: 422,
  APPROVAL_CONCURRENT_ACTION: 409,
  APPROVAL_UNAUTHORIZED: 403,
  APPROVAL_NOT_FOUND: 404,
  APPROVAL_NOT_PENDING: 422,
  APPROVAL_NOT_ELIGIBLE: 403,
  APPROVAL_PENDING_EXISTS: 409,
  APPROVAL_DOCUMENT_WRONG_STATUS: 422,
  APPROVAL_WORKFLOW_EMPTY: 422,
}

export class ApprovalError extends AppError {
  constructor(
    code: ApprovalErrorCode,
    message: string,
    errors?: Array<{ field: string; message: string }>,
  ) {
    super(STATUS_BY_CODE[code] ?? 422, message, code, errors)
    this.name = 'ApprovalError'
  }
}
