-- Manufacturing Phase 7A4 — ProductionFinishedGoodsReceipt + FG_RECEIVED activity

ALTER TABLE `production_activities` MODIFY COLUMN `activityType` ENUM(
  'CREATED', 'DEMAND_CREATED', 'DEMAND_CONVERTED', 'RELEASED', 'STARTED', 'HELD', 'RESUMED',
  'STAGE_READY', 'STAGE_STARTED', 'PROGRESS_RECORDED', 'STAGE_COMPLETED', 'COMPLETED',
  'CANCELLED', 'CORRECTION', 'ASSIGNED', 'DUE_DATE_CHANGED', 'PRIORITY_CHANGED',
  'OPERATOR_ASSIGNED', 'MACHINE_ASSIGNED', 'WORK_REASSIGNED', 'ASSIGNMENT_CANCELLED',
  'ASSIGNMENT_ACCEPTED', 'TASK_STARTED', 'TASK_PAUSED', 'TASK_RESUMED', 'TASK_COMPLETED',
  'DAILY_PRODUCTION_SUBMITTED', 'DAILY_PRODUCTION_CORRECTED', 'ISSUE_REPORTED',
  'ISSUE_ACKNOWLEDGED', 'ISSUE_RESOLVED', 'ISSUE_CANCELLED', 'DOWNTIME_STARTED',
  'DOWNTIME_ENDED', 'QC_REQUESTED', 'QC_PASSED', 'QC_REWORK', 'QC_REJECTED', 'NCR_OPENED',
  'NCR_CLOSED', 'RUNTIME_CHANGE_REQUESTED', 'RUNTIME_CHANGE_APPROVED',
  'RUNTIME_CHANGE_REJECTED', 'RUNTIME_CHANGE_APPLIED', 'RUNTIME_CHANGE_FAILED',
  'STAGE_HELD', 'STAGE_RESUMED', 'WIP_MOVED', 'MATERIAL_TRANSFERRED', 'WO_TO_WO_TRANSFERRED',
  'CORRECTION_REQUESTED', 'CORRECTION_APPROVED', 'CORRECTION_REJECTED', 'CORRECTION_APPLIED',
  'CORRECTION_FAILED', 'TRANSACTION_REVERSED', 'TRANSACTION_REPLACED', 'FG_RECEIVED'
) NOT NULL;

CREATE TABLE `production_finished_goods_receipts` (
    `id` VARCHAR(191) NOT NULL,
    `tenantId` VARCHAR(191) NOT NULL,
    `receiptNumber` VARCHAR(64) NOT NULL,
    `productionOrderId` VARCHAR(191) NOT NULL,
    `itemId` VARCHAR(191) NOT NULL,
    `uomId` VARCHAR(191) NOT NULL,
    `receiptQuantity` DECIMAL(18, 4) NOT NULL,
    `acceptedQuantity` DECIMAL(18, 4) NOT NULL,
    `warehouseId` VARCHAR(191) NOT NULL,
    `qualityInspectionId` VARCHAR(191) NULL,
    `qualityStatus` VARCHAR(32) NULL,
    `batchOrLotNumber` VARCHAR(64) NULL,
    `serialNumbersJson` JSON NULL,
    `inventoryMovementId` VARCHAR(191) NULL,
    `status` ENUM('DRAFT', 'POSTED', 'PARTIALLY_REVERSED', 'FULLY_REVERSED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
    `receiptDate` DATE NOT NULL,
    `remarks` TEXT NULL,
    `idempotencyKey` VARCHAR(150) NULL,
    `reversalStatus` VARCHAR(32) NULL,
    `latestCorrectionId` VARCHAR(191) NULL,
    `postedBy` VARCHAR(191) NULL,
    `postedAt` DATETIME(3) NULL,
    `createdBy` VARCHAR(191) NULL,
    `updatedBy` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`),
    UNIQUE INDEX `production_finished_goods_receipts_tenantId_receiptNumber_key` (`tenantId`, `receiptNumber`),
    UNIQUE INDEX `production_finished_goods_receipts_tenantId_idempotencyKey_key` (`tenantId`, `idempotencyKey`),
    INDEX `prod_fg_rcp_tenant_idx` (`tenantId`),
    INDEX `prod_fg_rcp_tenant_wo_idx` (`tenantId`, `productionOrderId`),
    INDEX `prod_fg_rcp_tenant_status_idx` (`tenantId`, `status`),
    INDEX `prod_fg_rcp_tenant_del_idx` (`tenantId`, `deletedAt`),
    CONSTRAINT `prod_fg_rcp_tenant_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `prod_fg_rcp_wo_fkey` FOREIGN KEY (`productionOrderId`) REFERENCES `production_orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `prod_fg_rcp_item_fkey` FOREIGN KEY (`itemId`) REFERENCES `master_items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `prod_fg_rcp_uom_fkey` FOREIGN KEY (`uomId`) REFERENCES `master_uoms` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `prod_fg_rcp_wh_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `master_warehouses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
