-- Maintenance V1 — tickets, parts, photos

ALTER TABLE `code_series` MODIFY `entityType` ENUM(
  'USER','LEAD','CONTACT','CRM_COMPANY','OPPORTUNITY','QUOTATION','SALES_ORDER',
  'PRODUCTION_DEMAND','PRODUCTION_ORDER','DAILY_PRODUCTION_BATCH','PRODUCTION_ISSUE',
  'STOCK_MOVEMENT','STOCK_RESERVATION','PURCHASE_REQUISITION','PURCHASE_PLANNING',
  'REQUEST_FOR_QUOTATION','VENDOR_QUOTATION','VENDOR_COMPARISON','PURCHASE_ORDER',
  'GOODS_RECEIPT','QUALITY_INSPECTION','QUALITY_NCR','PURCHASE_INVOICE','PURCHASE_RETURN',
  'JOB_WORK_ORDER','PRODUCTION_RUNTIME_CHANGE','PRODUCTION_WIP_MOVEMENT','MANUFACTURING_CORRECTION',
  'PRODUCTION_PLAN','DEMAND_CONSOLIDATION_PLAN','OUTBOUND_DISPATCH','PRODUCTION_FG_RECEIPT',
  'DISPATCH_REQUIREMENT','DISPATCH_PICK_LIST','DISPATCH_PACKING_SESSION','DISPATCH_PACKAGE',
  'DELIVERY_CHALLAN','PURCHASE_QUALITY_INSPECTION','INVENTORY_TRANSFER','INVENTORY_STOCK_COUNT',
  'INVENTORY_ADJUSTMENT','MANUFACTURING_ROUTING','DISPATCH_POSTING','DISPATCH_REVERSAL',
  'MAINTENANCE_TICKET'
) NOT NULL;

CREATE TABLE `maintenance_tickets` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `ticketNumber` VARCHAR(32) NOT NULL,
  `machineId` VARCHAR(191) NOT NULL,
  `workCentreId` VARCHAR(191) NULL,
  `sourceType` ENUM('MANUAL','MY_WORK','WORK_ORDER','JOB_CARD','OPERATION') NOT NULL DEFAULT 'MANUAL',
  `sourceDocumentId` VARCHAR(64) NULL,
  `workOrderId` VARCHAR(191) NULL,
  `jobCardId` VARCHAR(64) NULL,
  `jobCardCode` VARCHAR(64) NULL,
  `operationId` VARCHAR(191) NULL,
  `operationCode` VARCHAR(64) NULL,
  `operationName` VARCHAR(200) NULL,
  `problem` TEXT NOT NULL,
  `priority` ENUM('LOW','NORMAL','HIGH','CRITICAL') NOT NULL DEFAULT 'NORMAL',
  `status` ENUM('REPORTED','IN_REPAIR','WAITING_FOR_PART','ON_HOLD','TESTING','CLOSED','CANCELLED') NOT NULL DEFAULT 'REPORTED',
  `failureCategory` ENUM('MECHANICAL','ELECTRICAL','HYDRAULIC','PNEUMATIC','CONTROL','OTHER') NULL,
  `reportedByUserId` VARCHAR(191) NULL,
  `reportedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `repairStartedAt` DATETIME(3) NULL,
  `technicianType` ENUM('INTERNAL','EXTERNAL') NULL,
  `technicianUserId` VARCHAR(191) NULL,
  `contractorId` VARCHAR(191) NULL,
  `technicianName` VARCHAR(200) NULL,
  `repairDetails` TEXT NULL,
  `testResult` ENUM('PASS','FAIL') NULL,
  `testedByUserId` VARCHAR(191) NULL,
  `testedAt` DATETIME(3) NULL,
  `testRemarks` TEXT NULL,
  `closingRemarks` TEXT NULL,
  `closedByUserId` VARCHAR(191) NULL,
  `closedAt` DATETIME(3) NULL,
  `downtimeEndedAt` DATETIME(3) NULL,
  `downtimeMinutes` INT NULL,
  `partsCost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `serviceCost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `otherCost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `totalCost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `serviceDescription` TEXT NULL,
  `invoiceNumber` VARCHAR(64) NULL,
  `invoiceDate` DATETIME(3) NULL,
  `holdReason` TEXT NULL,
  `inventoryPostingPending` BOOLEAN NOT NULL DEFAULT true,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `maintenance_tickets_tenantId_ticketNumber_key`(`tenantId`, `ticketNumber`),
  INDEX `maintenance_tickets_tenantId_idx`(`tenantId`),
  INDEX `maintenance_tickets_tenantId_status_idx`(`tenantId`, `status`),
  INDEX `maintenance_tickets_tenantId_machineId_idx`(`tenantId`, `machineId`),
  INDEX `maintenance_tickets_tenantId_deletedAt_idx`(`tenantId`, `deletedAt`),
  INDEX `maintenance_tickets_tenantId_reportedAt_idx`(`tenantId`, `reportedAt`),
  CONSTRAINT `maintenance_tickets_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `maintenance_tickets_machineId_fkey` FOREIGN KEY (`machineId`) REFERENCES `manufacturing_machines`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `maintenance_tickets_contractorId_fkey` FOREIGN KEY (`contractorId`) REFERENCES `master_vendors`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `maintenance_parts` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `ticketId` VARCHAR(191) NOT NULL,
  `itemId` VARCHAR(191) NULL,
  `description` VARCHAR(300) NOT NULL,
  `qty` DECIMAL(18, 4) NOT NULL,
  `unitCost` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalCost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `remarks` VARCHAR(500) NULL,
  `inventoryMovementId` VARCHAR(191) NULL,
  `shortageQty` DECIMAL(18, 4) NULL,
  `purchaseRequisitionId` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `maintenance_parts_tenantId_idx`(`tenantId`),
  INDEX `maintenance_parts_tenantId_ticketId_idx`(`tenantId`, `ticketId`),
  INDEX `maintenance_parts_tenantId_deletedAt_idx`(`tenantId`, `deletedAt`),
  CONSTRAINT `maintenance_parts_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `maintenance_parts_ticketId_fkey` FOREIGN KEY (`ticketId`) REFERENCES `maintenance_tickets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `maintenance_parts_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `master_items`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `maintenance_attachments` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `ticketId` VARCHAR(191) NOT NULL,
  `category` ENUM('BEFORE','DURING','AFTER','OTHER') NOT NULL DEFAULT 'OTHER',
  `originalFilename` VARCHAR(255) NOT NULL,
  `storedFilename` VARCHAR(255) NOT NULL,
  `mimeType` VARCHAR(120) NOT NULL,
  `fileSize` INT NOT NULL,
  `storagePath` VARCHAR(500) NOT NULL,
  `uploadedBy` VARCHAR(191) NULL,
  `uploadedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `maintenance_attachments_tenantId_idx`(`tenantId`),
  INDEX `maintenance_attachments_tenantId_ticketId_idx`(`tenantId`, `ticketId`),
  CONSTRAINT `maintenance_attachments_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `maintenance_attachments_ticketId_fkey` FOREIGN KEY (`ticketId`) REFERENCES `maintenance_tickets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
