export const PERMISSIONS = [
  'tenant.view',
  'tenant.create',
  'tenant.update',
  'tenant.delete',
  'tenant.manage',

  'user.view',
  'user.create',
  'user.update',
  'user.delete',
  'user.assign_role',

  'role.view',
  'role.create',
  'role.update',
  'role.delete',

  'crm.lead.view',
  'crm.lead.create',
  'crm.lead.update',
  'crm.lead.delete',
  'crm.lead.assign',
  'crm.lead.qualify',
  'crm.lead.convert',

  'crm.contact.view',
  'crm.contact.create',
  'crm.contact.update',
  'crm.contact.delete',

  'crm.company.view',
  'crm.company.create',
  'crm.company.update',
  'crm.company.delete',

  'crm.activity.view',
  'crm.activity.create',
  'crm.activity.update',
  'crm.activity.complete',
  'crm.activity.delete',

  'crm.pipeline.view',
  'crm.pipeline.manage',

  'crm.opportunity.view',
  'crm.opportunity.create',
  'crm.opportunity.update',
  'crm.opportunity.close',
  'crm.opportunity.delete',

  'crm.quotation.view',
  'crm.quotation.create',
  'crm.quotation.update',
  'crm.quotation.delete',
  'crm.quotation.approve',
  /** Convert approved quotation → sales order (maps from product code convert_sales_order). */
  'crm.quotation.convert',

  'crm.sales_order.view',
  'crm.sales_order.create',
  'crm.sales_order.update',
  'crm.sales_order.delete',
  'crm.sales_order.confirm',

  'crm.follow_up.view',
  'crm.follow_up.create',
  'crm.follow_up.update',
  'crm.follow_up.delete',

  'crm.import.view',
  'crm.import.execute',

  'crm.master.view',
  'crm.master.create',
  'crm.master.update',
  'crm.master.delete',

  'crm.dashboard.view',
  'crm.report.view',
  'crm.search.view',
  'crm.export.view',
  'crm.export.execute',
  'crm.note.view',
  'crm.note.create',
  'crm.note.update',
  'crm.note.delete',
  'crm.attachment.view',
  'crm.attachment.create',
  'crm.attachment.delete',

  'master.lookup.view',

  'master.country.view',
  'master.country.create',
  'master.country.update',
  'master.country.delete',

  'master.state.view',
  'master.state.create',
  'master.state.update',
  'master.state.delete',

  'master.city.view',
  'master.city.create',
  'master.city.update',
  'master.city.delete',

  'master.uom.view',
  'master.uom.create',
  'master.uom.update',
  'master.uom.delete',

  'master.warehouse.view',
  'master.warehouse.create',
  'master.warehouse.update',
  'master.warehouse.delete',

  'master.location.view',
  'master.location.create',
  'master.location.update',
  'master.location.delete',

  'master.item_category.view',
  'master.item_category.create',
  'master.item_category.update',
  'master.item_category.delete',

  'master.hsn.view',
  'master.hsn.create',
  'master.hsn.update',
  'master.hsn.delete',

  'master.gst_group.view',
  'master.gst_group.create',
  'master.gst_group.update',
  'master.gst_group.delete',

  'master.gst_rate.view',
  'master.gst_rate.create',
  'master.gst_rate.update',
  'master.gst_rate.delete',

  'master.item.view',
  'master.item.create',
  'master.item.update',
  'master.item.delete',
  'master.item.import',

  'master.product.view',
  'master.product.create',
  'master.product.update',
  'master.product.delete',

  'master.vendor.view',
  'master.vendor.create',
  'master.vendor.update',
  'master.vendor.delete',
  'master.vendor.import',

  'master.hsn.import',

  // Purchase module (catalog reserved for future purchase API — FE gates on these keys today)
  /** Module shell / nav gate (Route matrix `purchase.view`). */
  'purchase.view',
  'purchase.dashboard.view',
  'purchase.requisition.view',
  'purchase.requisition.create',
  'purchase.requisition.edit',
  'purchase.requisition.submit',
  'purchase.requisition.approve',
  'purchase.rfq.view',
  'purchase.rfq.create',
  'purchase.rfq.send',
  'purchase.quotation.view',
  'purchase.quotation.create',
  'purchase.quotation.compare',
  'purchase.order.view',
  'purchase.order.create',
  'purchase.order.edit',
  'purchase.order.approve',
  'purchase.order.release',
  'purchase.order.cancel',
  'purchase.grn.view',
  'purchase.grn.create',
  'purchase.grn.post',
  'purchase.quality.view',
  'purchase.quality.inspect',
  'purchase.invoice.view',
  'purchase.invoice.create',
  'purchase.invoice.verify',
  'purchase.invoice.approve',
  'purchase.invoice.post',
  'purchase.return.view',
  'purchase.return.create',
  'purchase.return.post',
  'purchase.reports.view',
  'purchase.setup.manage',

  // Finance / Accounting Phase 1 — setup only (no GL posting)
  'finance.view',
  'finance.settings.view',
  'finance.settings.manage',
  'finance.legal_entity.view',
  'finance.legal_entity.manage',
  'finance.branch.view',
  'finance.branch.manage',
  'finance.financial_year.view',
  'finance.financial_year.manage',
  'finance.period.view',
  'finance.period.manage',
  'finance.period.close',
  'finance.period.reopen',
  'finance.coa.view',
  'finance.coa.manage',
  'finance.default_mapping.view',
  'finance.default_mapping.manage',
  'finance.number_series.view',
  'finance.number_series.manage',
  'finance.cost_centre.view',
  'finance.cost_centre.manage',
  'finance.approval_rule.view',
  'finance.approval_rule.manage',
  'finance.activate',
  'finance.audit.view',
] as const

export type PermissionName = (typeof PERMISSIONS)[number]

const MASTER_VIEW_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('master.') && p.endsWith('.view'))
const PURCHASE_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('purchase.'))
const PURCHASE_OPS = PURCHASE_PERMISSIONS.filter((p) => p !== 'purchase.setup.manage')
const FINANCE_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('finance.'))
const FINANCE_VIEW_PERMISSIONS = FINANCE_PERMISSIONS.filter(
  (p) => p.endsWith('.view') || p === 'finance.view' || p === 'finance.audit.view',
)
const FINANCE_EXECUTIVE_MANAGE: PermissionName[] = [
  'finance.settings.manage',
  'finance.coa.manage',
  'finance.default_mapping.manage',
  'finance.cost_centre.manage',
  'finance.number_series.manage',
]

export const ROLE_PERMISSIONS: Record<string, PermissionName[]> = {
  'Super Admin': [...PERMISSIONS],
  /** Full tenant workspace access (includes all `purchase.*` except platform tenant.*). */
  'Tenant Admin': PERMISSIONS.filter((p) => p !== 'tenant.manage' && p !== 'tenant.create' && p !== 'tenant.delete'),
  /** Alias some tenants may use — same grant set as Tenant Admin. */
  Admin: PERMISSIONS.filter((p) => p !== 'tenant.manage' && p !== 'tenant.create' && p !== 'tenant.delete'),
  /** Product persona name — same grant set as Tenant Admin (includes purchase.setup.manage). */
  Administrator: PERMISSIONS.filter((p) => p !== 'tenant.manage' && p !== 'tenant.create' && p !== 'tenant.delete'),
  'Master Data Manager': PERMISSIONS.filter((p) => p.startsWith('master.')),
  'Purchase Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'master.vendor.create',
    'master.vendor.update',
    'master.vendor.delete',
    'master.vendor.import',
    ...PURCHASE_OPS,
  ],
  'Purchase Executive': [
    ...MASTER_VIEW_PERMISSIONS,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.requisition.view',
    'purchase.requisition.create',
    'purchase.requisition.edit',
    'purchase.requisition.submit',
    'purchase.rfq.view',
    'purchase.rfq.create',
    'purchase.rfq.send',
    'purchase.quotation.view',
    'purchase.quotation.create',
    'purchase.quotation.compare',
    'purchase.order.view',
    'purchase.order.create',
    'purchase.order.edit',
    'purchase.grn.view',
    'purchase.quality.view',
    'purchase.invoice.view',
    'purchase.return.view',
    'purchase.reports.view',
  ],
  Requester: [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.requisition.view',
    'purchase.requisition.create',
    'purchase.requisition.edit',
    'purchase.requisition.submit',
    'master.lookup.view',
    'master.item.view',
  ],
  'Department Head': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.requisition.view',
    'purchase.requisition.create',
    'purchase.requisition.edit',
    'purchase.requisition.submit',
    'purchase.requisition.approve',
    'purchase.reports.view',
    'master.lookup.view',
    'master.item.view',
  ],
  'Store Executive': [
    ...MASTER_VIEW_PERMISSIONS,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.order.view',
    'purchase.grn.view',
    'purchase.grn.create',
    'purchase.grn.post',
    'purchase.quality.view',
    'purchase.return.view',
    'purchase.return.create',
    'purchase.return.post',
    'purchase.reports.view',
  ],
  'Quality Inspector': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.grn.view',
    'purchase.quality.view',
    'purchase.quality.inspect',
    'purchase.return.view',
    'master.lookup.view',
    'master.item.view',
  ],
  'Finance Executive': [
    ...FINANCE_VIEW_PERMISSIONS,
    ...FINANCE_EXECUTIVE_MANAGE,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.order.view',
    'purchase.grn.view',
    'purchase.invoice.view',
    'purchase.invoice.create',
    'purchase.invoice.verify',
    'purchase.return.view',
    'purchase.reports.view',
    'master.lookup.view',
    'master.vendor.view',
  ],
  'Finance Manager': [
    ...FINANCE_PERMISSIONS,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.order.view',
    'purchase.grn.view',
    'purchase.invoice.view',
    'purchase.invoice.create',
    'purchase.invoice.verify',
    'purchase.invoice.approve',
    'purchase.invoice.post',
    'purchase.return.view',
    'purchase.reports.view',
    'master.lookup.view',
    'master.vendor.view',
  ],
  Management: [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.requisition.view',
    'purchase.requisition.approve',
    'purchase.rfq.view',
    'purchase.quotation.view',
    'purchase.quotation.compare',
    'purchase.order.view',
    'purchase.order.approve',
    'purchase.order.release',
    'purchase.order.cancel',
    'purchase.grn.view',
    'purchase.quality.view',
    'purchase.invoice.view',
    'purchase.invoice.approve',
    'purchase.return.view',
    'purchase.reports.view',
  ],
  'Inventory Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'master.item.create',
    'master.item.update',
    'master.item.delete',
    'master.item.import',
    'master.item_category.create',
    'master.item_category.update',
    'master.item_category.delete',
    'master.uom.create',
    'master.uom.update',
    'master.uom.delete',
    'master.warehouse.create',
    'master.warehouse.update',
    'master.warehouse.delete',
    'master.location.create',
    'master.location.update',
    'master.location.delete',
  ],
  'Sales Manager': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update', 'crm.lead.delete', 'crm.lead.assign', 'crm.lead.qualify', 'crm.lead.convert',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update', 'crm.contact.delete',
    'crm.company.view', 'crm.company.create', 'crm.company.update', 'crm.company.delete',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete', 'crm.activity.delete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update', 'crm.follow_up.delete',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update', 'crm.opportunity.close', 'crm.opportunity.delete',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update', 'crm.quotation.delete', 'crm.quotation.approve',
    'crm.quotation.convert',
    'crm.sales_order.view', 'crm.sales_order.create', 'crm.sales_order.update', 'crm.sales_order.delete', 'crm.sales_order.confirm',
    'crm.import.view', 'crm.import.execute',
    'crm.master.view', 'crm.master.create', 'crm.master.update', 'crm.master.delete',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view', 'crm.export.view', 'crm.export.execute',
    'crm.note.view', 'crm.note.create', 'crm.note.update', 'crm.note.delete',
    'crm.attachment.view', 'crm.attachment.create', 'crm.attachment.delete',
    'user.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
  ],
  'Production Manager': [
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
    'master.item_category.view',
    'master.uom.view',
    'master.warehouse.view',
    'master.location.view',
  ],
  'CRM Admin': PERMISSIONS.filter(
    (p) => p.startsWith('crm.') || p === 'user.view' || p === 'master.product.view' || p === 'master.lookup.view',
  ),
  'Sales Executive': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update',
    'crm.company.view',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update', 'crm.quotation.convert',
    'crm.sales_order.view', 'crm.sales_order.create', 'crm.sales_order.update',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
  ],
  Viewer: [
    'crm.lead.view', 'crm.contact.view', 'crm.company.view',
    'crm.activity.view', 'crm.follow_up.view', 'crm.pipeline.view', 'crm.opportunity.view',
    'crm.quotation.view', 'crm.sales_order.view',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view',
    'user.view',
    ...MASTER_VIEW_PERMISSIONS,
  ],
}

/** Canonical CRM opportunity pipeline — keep in sync with frontend opportunity-stages master / OPPORTUNITY_STAGES. */
export const DEFAULT_PIPELINE_STAGES = [
  { name: 'New Lead', slug: 'new_lead', sequence: 1, probability: 10 },
  { name: 'Qualified', slug: 'qualified', sequence: 2, probability: 20 },
  { name: 'Requirement Discussion', slug: 'requirement_discussion', sequence: 3, probability: 30 },
  { name: 'Technical Review', slug: 'technical_review', sequence: 4, probability: 40 },
  { name: 'Quotation Prepared', slug: 'quotation_prepared', sequence: 5, probability: 55 },
  { name: 'Quotation Sent', slug: 'quotation_sent', sequence: 6, probability: 65 },
  { name: 'Negotiation', slug: 'negotiation', sequence: 7, probability: 75 },
  { name: 'Won', slug: 'won', sequence: 8, probability: 100, isClosedWon: true },
  { name: 'Lost', slug: 'lost', sequence: 9, probability: 0, isClosedLost: true },
  { name: 'On Hold', slug: 'on_hold', sequence: 10, probability: 15 },
] as const
