export const PERMISSIONS = [
  'tenant.view',
  'tenant.create',
  'tenant.update',
  'tenant.delete',
  'tenant.manage',

  'user.view',
  'user.create',
  'user.update',
  'user.delete',
  'user.assign_role',

  'department.view',
  'department.create',
  'department.update',
  'department.delete',

  'scope.view',
  'scope.manage',

  'responsibility.view',
  'responsibility.create',
  'responsibility.update',
  'responsibility.delete',

  'access.view',
  'access.review',

  'security.view',
  'security.manage',

  'module.view',
  'module.manage',

  'role.view',
  'role.create',
  'role.update',
  'role.delete',

  'crm.lead.view',
  'crm.lead.create',
  'crm.lead.update',
  'crm.lead.delete',
  'crm.lead.assign',
  'crm.lead.qualify',
  'crm.lead.convert',

  'crm.contact.view',
  'crm.contact.create',
  'crm.contact.update',
  'crm.contact.delete',

  'crm.company.view',
  'crm.company.create',
  'crm.company.update',
  'crm.company.delete',

  'crm.activity.view',
  'crm.activity.create',
  'crm.activity.update',
  'crm.activity.complete',
  'crm.activity.delete',

  'crm.pipeline.view',
  'crm.pipeline.manage',

  'crm.opportunity.view',
  'crm.opportunity.create',
  'crm.opportunity.update',
  'crm.opportunity.close',
  'crm.opportunity.delete',

  'crm.quotation.view',
  'crm.quotation.create',
  'crm.quotation.update',
  'crm.quotation.delete',
  'crm.quotation.approve',
  /** Convert approved quotation â†’ sales order (maps from product code convert_sales_order). */
  'crm.quotation.convert',

  'crm.sales_order.view',
  'crm.sales_order.create',
  'crm.sales_order.update',
  'crm.sales_order.delete',
  'crm.sales_order.confirm',

  /** CRM commercial & receivables (lightweight â€” no Accounting module required). */
  'crm.commercial.view',
  'crm.commercial.receipt.view',
  'crm.commercial.receipt.create',
  'crm.commercial.receipt.accounting_draft.create',
  'crm.commercial.invoice.view',
  'crm.commercial.invoice.create',
  'crm.commercial.invoice.post',
  'crm.commercial.invoice.cancel',
  'crm.commercial.allocation.view',
  'crm.commercial.allocation.create',
  'crm.commercial.allocation.reverse',

  'crm.follow_up.view',
  'crm.follow_up.create',
  'crm.follow_up.update',
  'crm.follow_up.delete',

  'crm.import.view',
  'crm.import.execute',

  'crm.master.view',
  'crm.master.create',
  'crm.master.update',
  'crm.master.delete',

  'crm.dashboard.view',
  'crm.report.view',
  'crm.search.view',
  'crm.export.view',
  'crm.export.execute',
  'crm.note.view',
  'crm.note.create',
  'crm.note.update',
  'crm.note.delete',
  'crm.attachment.view',
  'crm.attachment.create',
  'crm.attachment.delete',

  'crm.indiamart.view',
  'crm.indiamart.enquiry.view',
  'crm.indiamart.enquiry.import',
  'crm.indiamart.enquiry.assign',
  'crm.indiamart.enquiry.ignore',
  'crm.indiamart.enquiry.bulk_manage',
  'crm.indiamart.sync.run',
  'crm.indiamart.sync_history.view',
  'crm.indiamart.settings.view',
  'crm.indiamart.settings.manage',
  'crm.indiamart.credentials.manage',
  'crm.indiamart.product_mapping.manage',

  'master.lookup.view',

  'master.country.view',
  'master.country.create',
  'master.country.update',
  'master.country.delete',

  'master.state.view',
  'master.state.create',
  'master.state.update',
  'master.state.delete',

  'master.city.view',
  'master.city.create',
  'master.city.update',
  'master.city.delete',

  'master.uom.view',
  'master.uom.create',
  'master.uom.update',
  'master.uom.delete',

  'master.plant.view',
  'master.plant.create',
  'master.plant.update',
  'master.plant.delete',

  'master.warehouse.view',
  'master.warehouse.create',
  'master.warehouse.update',
  'master.warehouse.delete',

  'master.location.view',
  'master.location.create',
  'master.location.update',
  'master.location.delete',

  'master.bin.view',
  'master.bin.create',
  'master.bin.update',
  'master.bin.delete',

  'master.item_category.view',
  'master.item_category.create',
  'master.item_category.update',
  'master.item_category.delete',

  'master.hsn.view',
  'master.hsn.create',
  'master.hsn.update',
  'master.hsn.delete',

  'master.receiving_tolerance.view',
  'master.receiving_tolerance.create',
  'master.receiving_tolerance.update',
  'master.receiving_tolerance.delete',

  'master.gst_group.view',
  'master.gst_group.create',
  'master.gst_group.update',
  'master.gst_group.delete',

  'master.gst_rate.view',
  'master.gst_rate.create',
  'master.gst_rate.update',
  'master.gst_rate.delete',

  'master.item.view',
  'master.item.create',
  'master.item.update',
  'master.item.delete',
  'master.item.import',

  'master.product.view',
  'master.product.create',
  'master.product.update',
  'master.product.delete',

  'master.vendor.view',
  'master.vendor.create',
  'master.vendor.update',
  'master.vendor.delete',
  'master.vendor.import',

  'master.hsn.import',

  // Purchase module â€” canonical keys (PR / Planning / RFQ / PO)
  /** Module shell / nav gate (Route matrix `purchase.view`). */
  'purchase.view',
  'purchase.dashboard.view',
  'purchase.pr.view',
  'purchase.pr.create',
  'purchase.pr.edit',
  'purchase.pr.submit',
  'purchase.pr.approve',
  'purchase.pr.reject',
  'purchase.pr.cancel',
  'purchase.pr.reopen',
  'purchase.pr.revise',
  'purchase.planning.view',
  'purchase.planning.edit',
  'purchase.planning.assign_buyer',
  'purchase.planning.select_vendor',
  'purchase.planning.approve',
  'purchase.planning.create_po',
  'purchase.planning.cancel',
  'purchase.rfq.view',
  'purchase.rfq.create',
  'purchase.rfq.send',
  'purchase.rfq.enter_quote',
  'purchase.rfq.compare',
  'purchase.rfq.award',
  'purchase.rfq.convert_to_po',
  'purchase.po.view',
  'purchase.po.create',
  'purchase.po.edit',
  'purchase.po.approve',
  'purchase.po.send',
  'purchase.po.cancel',
  'purchase.po.close',
  /**
   * Maker-checker override: approve documents you created/requested yourself.
   * Only effective when Purchase Setup selfApprovalPolicy = PERMISSION_ONLY.
   * Deliberately excluded from PURCHASE_OPS â€” grant explicitly (admin/CEO roles get it via full sets).
   */
  'purchase.approvals.self_approve',
  'purchase.grn.view',
  'purchase.grn.create',
  'purchase.grn.post',
  'purchase.quality.view',
  'purchase.quality.inspect',
  'purchase.qi.view',
  'purchase.qi.create',
  'purchase.qi.edit',
  'purchase.qi.complete',
  'purchase.qi.cancel',
  'purchase.invoice.view',
  'purchase.invoice.create',
  'purchase.invoice.edit',
  'purchase.invoice.submit',
  'purchase.invoice.verify',
  'purchase.invoice.approve',
  'purchase.invoice.post',
  'purchase.invoice.cancel',
  'purchase.return.view',
  'purchase.return.create',
  'purchase.return.edit',
  'purchase.return.submit',
  'purchase.return.complete',
  'purchase.return.cancel',
  'purchase.return.post',
  'purchase.reports.view',
  'purchase.setup.view',
  'purchase.setup.manage',

  // Finance / Accounting Phase 1 â€” setup only (no GL posting)
  'finance.view',
  'finance.settings.view',
  'finance.settings.manage',
  'finance.legal_entity.view',
  'finance.legal_entity.manage',
  'finance.branch.view',
  'finance.branch.manage',
  'finance.financial_year.view',
  'finance.financial_year.manage',
  'finance.period.view',
  'finance.period.manage',
  'finance.period.close',
  'finance.period.reopen',
  'finance.period.reopen_request',
  'finance.period.reopen_approve',
  // Period-close FX revaluation
  'finance.fx_revaluation.view',
  'finance.fx_revaluation.manage',
  'finance.fx_revaluation.preview',
  'finance.fx_revaluation.post',
  'finance.fx_revaluation.reverse',
  // Period-close adjustments â€” month-end accruals + prepaid amortisation
  'finance.period_adjustment.view',
  'finance.period_adjustment.manage',
  'finance.period_adjustment.post',
  'finance.period_adjustment.reverse',
  'finance.coa.view',
  'finance.coa.manage',
  'finance.default_mapping.view',
  'finance.default_mapping.manage',
  'finance.number_series.view',
  'finance.number_series.manage',
  'finance.cost_centre.view',
  'finance.cost_centre.manage',
  'finance.approval_rule.view',
  'finance.approval_rule.manage',
  'finance.activate',
  'finance.audit.view',

  // Organisation foundation setup (aliases + org-specific)
  'organisation.view',
  'organisation.create',
  'organisation.update',
  'finance.chart_accounts.view',
  'finance.chart_accounts.create',
  'finance.account_mapping.manage',
  'finance.fiscal_year.manage',
  'finance.posting_period.manage',

  // Finance Phase 2A/2B â€” ledger foundation + internal posting engine
  'finance.voucher.view',
  'finance.voucher.create',
  'finance.voucher.edit',
  'finance.voucher.submit',
  'finance.voucher.approve',
  'finance.voucher.post',
  'finance.voucher.reverse',
  'finance.voucher.cancel',
  'finance.gl.view',
  'finance.posting_event.view',
  'finance.posting_rule.view',
  'finance.posting_rule.manage',

  // Finance Phase 3A1 â€” AR foundation (DB + repos; no HTTP invoice routes in 3A1)
  'finance.ar.view',
  'finance.ar.invoice.view',
  'finance.ar.invoice.create',
  'finance.ar.invoice.edit',
  'finance.ar.invoice.post',
  'finance.ar.invoice.cancel',
  'finance.ar.invoice.reverse',
  'finance.ar.reconcile.view',
  'finance.ar.receipt.view',
  'finance.ar.receipt.create',
  'finance.ar.receipt.edit',
  'finance.ar.receipt.post',
  'finance.ar.receipt.cancel',
  'finance.ar.receipt.reverse',
  'finance.ar.allocation.view',
  'finance.ar.allocation.create',
  'finance.ar.allocation.reverse',
  'finance.ar.crm_receipt_migration.view',
  'finance.ar.crm_receipt_migration.manage',
  'finance.ar.crm_receipt_duplicate.override',
  'finance.ar.credit_note.view',
  'finance.ar.credit_note.create',
  'finance.ar.credit_note.edit',
  'finance.ar.credit_note.submit',
  'finance.ar.credit_note.approve',
  'finance.ar.credit_note.cancel',
  'finance.ar.credit_note.post',
  'finance.ar.credit_note.mark_ready',
  'finance.ar.credit_note.reverse',

  // Finance Phase 4A1 â€” AP foundation (DB + repos; no HTTP vendor-invoice routes in 4A1)
  // Phase 4A3 adds draft workflow HTTP routes (submit/approve/reject/revise/mark-ready/cancel).
  'finance.ap.view',
  'finance.ap.vendor_invoice.view',
  'finance.ap.vendor_invoice.create',
  'finance.ap.vendor_invoice.edit',
  'finance.ap.vendor_invoice.submit',
  'finance.ap.vendor_invoice.approve',
  'finance.ap.vendor_invoice.post',
  'finance.ap.vendor_invoice.cancel',
  'finance.ap.vendor_invoice.reverse',
  'finance.ap.vendor_invoice.mark_ready',
  'finance.ap.open_item.view',

  // Finance Phase 4B1 â€” AP payment / allocation foundation (DB + repos; no HTTP routes)
  'finance.ap.payment.view',
  'finance.ap.payment.create',
  'finance.ap.payment.edit',
  'finance.ap.payment.submit',
  'finance.ap.payment.approve',
  'finance.ap.payment.post',
  'finance.ap.payment.cancel',
  'finance.ap.payment.reverse',
  'finance.ap.payment.mark_ready',
  'finance.ap.allocation.view',
  'finance.ap.allocation.create',
  'finance.ap.allocation.reverse',
  'finance.ap.advance.view',

  // Finance Phase 4C2 â€” vendor adjustments / Money Out corrections
  'finance.ap.adjustment.view',
  'finance.ap.adjustment.create',
  'finance.ap.adjustment.edit',
  'finance.ap.adjustment.submit',
  'finance.ap.adjustment.approve',
  'finance.ap.adjustment.post',
  'finance.ap.adjustment.cancel',
  'finance.ap.adjustment.reverse',
  'finance.ap.adjustment.mark_ready',
  'finance.ap.corrections.view',

  // Finance Phase 4D2 â€” AP-to-GL reconciliation + close gate (persisted runs; no GL/period mutation)
  'finance.ap.reconciliation.view',
  'finance.ap.reconciliation.run',
  'finance.ap.reconciliation.export',
  'finance.ap.reconciliation.exception.view',
  'finance.ap.reconciliation.exception.acknowledge',
  'finance.ap.close_gate.view',
  'finance.ap.close_gate.run',
  'finance.ap.close_gate.export',

  // Finance Phase 5A1 â€” Bank & Cash treasury foundation (account master + GL mapping +
  // payment-account routing + reconciliation settings + bank-statement DB foundation).
  // Statement perms are registered for the future import/match/reconcile phase; no HTTP
  // route checks them yet in 5A1.
  'finance.treasury.account.view',
  'finance.treasury.account.create',
  'finance.treasury.account.edit',
  'finance.treasury.account.activate',
  'finance.treasury.account.deactivate',
  'finance.treasury.account.close',
  'finance.treasury.bank_account.view',
  'finance.treasury.cash_account.view',
  'finance.treasury.payment_mapping.view',
  'finance.treasury.payment_mapping.manage',
  'finance.treasury.reconciliation_settings.view',
  'finance.treasury.reconciliation_settings.manage',
  'finance.treasury.statement.view',
  'finance.treasury.statement.import',
  'finance.treasury.statement.manual_entry',
  'finance.treasury.statement.edit',
  'finance.treasury.statement.validate',
  'finance.treasury.statement.cancel',
  'finance.treasury.statement.mapping.view',
  'finance.treasury.statement.mapping.manage',
  'finance.treasury.statement.file.download',
  'finance.treasury.statement.match',
  'finance.treasury.statement.reconcile',

  // Finance Phase 5A3 â€” bank reconciliation workspace (fine-grained)
  'finance.bank.reconciliation.view',
  'finance.bank.reconciliation.run_auto_match',
  'finance.bank.reconciliation.match',
  'finance.bank.reconciliation.group_match',
  'finance.bank.reconciliation.partial_match',
  'finance.bank.reconciliation.unmatch',
  'finance.bank.reconciliation.finalize',
  'finance.bank.reconciliation.finalize_with_exceptions',
  'finance.bank.reconciliation.reopen',
  'finance.bank.reconciliation.exception_manage',
  'finance.bank.reconciliation.clearing_post',
  'finance.bank.reconciliation.adjustment_draft_create',

  // Finance Phase 5B1 â€” internal treasury transfers
  'finance.treasury.transfer.view',
  'finance.treasury.transfer.create',
  'finance.treasury.transfer.edit',
  'finance.treasury.transfer.submit',
  'finance.treasury.transfer.approve',
  'finance.treasury.transfer.post',
  'finance.treasury.transfer.dispatch',
  'finance.treasury.transfer.receive',
  'finance.treasury.transfer.cancel',
  'finance.treasury.transfer.reverse',
  'finance.treasury.transfer.in_transit.view',

  // Finance Phase 5B2 â€” cheque management
  'finance.treasury.cheque.view',
  'finance.treasury.cheque.create',
  'finance.treasury.cheque.edit',
  'finance.treasury.cheque.submit',
  'finance.treasury.cheque.approve',
  'finance.treasury.cheque.issue',
  'finance.treasury.cheque.deposit',
  'finance.treasury.cheque.clear',
  'finance.treasury.cheque.bounce',
  'finance.treasury.cheque.stop',
  'finance.treasury.cheque.cancel',
  'finance.treasury.cheque.reverse',

  // Finance Phase 5B3 â€” treasury adjustments (bank charges/interest/direct debit-credit)
  'finance.treasury.adjustment.view',
  'finance.treasury.adjustment.create',
  'finance.treasury.adjustment.edit',
  'finance.treasury.adjustment.submit',
  'finance.treasury.adjustment.approve',
  'finance.treasury.adjustment.post',
  'finance.treasury.adjustment.cancel',
  'finance.treasury.adjustment.reverse',

  // Finance Phase 5B3 â€” bank statement classification / posting rules
  'finance.treasury.posting_rule.view',
  'finance.treasury.posting_rule.manage',

  // Finance Phase 5B3 â€” standing instructions (draft-only generation)
  'finance.treasury.standing_instruction.view',
  'finance.treasury.standing_instruction.manage',
  'finance.treasury.standing_instruction.generate',

  // Finance Phase 5B3 â€” bankbook / cashbook (read-only)
  'finance.treasury.book.view',

  // Finance Phase 5C1 â€” cash position / liquidity / day-close controls
  'finance.treasury.liquidity.view',
  'finance.treasury.closing.view',
  'finance.treasury.closing.manage',

  // Finance Phase 5D1 â€” bank connector scaffold (no live bank APIs)
  'finance.bank_connector.view',
  'finance.bank_connector.manage',
  'finance.bank_connector.sync',

  // Tax compliance extracts (GST outward/inward/summary + future export)
  'finance.tax.view',
  'finance.tax.extract',
  // Tax compliance Phase 2 â€” e-invoice / e-way (simulated NIC by default)
  'finance.tax.einvoice.manage',
  'finance.tax.eway.manage',

  // Finance Fixed Assets Phase 1â€“2 â€” register, capitalize, depreciate, simple dispose
  'finance.fa.view',
  'finance.fa.create',
  'finance.fa.edit',
  'finance.fa.capitalize',
  'finance.fa.depreciate',
  'finance.fa.dispose',
  'finance.fa.transfer',
  'finance.fa.revalue',
  'finance.fa.impair',
  'finance.fa.maintain',

  // Finance Budgeting Phase 1 â€” versions, annual lines, budget vs actual
  'finance.budget.view',
  'finance.budget.create',
  'finance.budget.edit',
  'finance.budget.approve',

  // â”€â”€ Frontend route-matrix module keys (PermissionModule.PermissionAction) â”€â”€
  // SPA soft-gates and nav shells; reserved for future APIs. Keep in sync with
  // frontend/src/config/permissionMatrix.ts modules Ã— actions.
  'masters.view', 'masters.create', 'masters.edit', 'masters.submit', 'masters.approve',
  'masters.release', 'masters.post', 'masters.cancel', 'masters.close', 'masters.print',
  'masters.export', 'masters.override',

  'engineering.view', 'engineering.create', 'engineering.edit', 'engineering.submit', 'engineering.approve',
  'engineering.release', 'engineering.post', 'engineering.cancel', 'engineering.close', 'engineering.print',
  'engineering.export', 'engineering.override',

  // purchase.* fine-grained keys above; matrix also uses purchase.create|edit|â€¦
  'purchase.create', 'purchase.edit', 'purchase.submit', 'purchase.approve', 'purchase.release',
  'purchase.post', 'purchase.cancel', 'purchase.close', 'purchase.print', 'purchase.export',
  'purchase.override',

  'inventory.view', 'inventory.create', 'inventory.edit', 'inventory.submit', 'inventory.approve',
  'inventory.release', 'inventory.post', 'inventory.cancel', 'inventory.close', 'inventory.print',
  'inventory.export', 'inventory.override',
  'inventory.view_cost', 'inventory.items.view', 'inventory.items.create', 'inventory.items.edit',
  'inventory.items.deactivate', 'inventory.stock.view', 'inventory.view_audit',
  'inventory.receipts.view', 'inventory.receipts.create', 'inventory.receipts.edit',
  'inventory.receipts.post', 'inventory.receipts.cancel',
  'inventory.quality.view', 'inventory.quality.inspect', 'inventory.quality.release',
  'inventory.quality.accept_deviation',
  'inventory.issues.view', 'inventory.issues.create', 'inventory.issues.edit', 'inventory.issues.post',
  'inventory.issues.reverse', 'inventory.issues.cancel', 'inventory.issues.override_negative_stock',
  'inventory.transfers.view', 'inventory.transfers.create', 'inventory.transfers.dispatch',
  'inventory.transfers.receive', 'inventory.transfers.cancel',
  'inventory.adjustments.view', 'inventory.adjustments.create', 'inventory.adjustments.submit',
  'inventory.adjustments.approve', 'inventory.adjustments.post',
  'inventory.returns.view', 'inventory.returns.create', 'inventory.returns.post',
  'inventory.batch.view', 'inventory.serial.view',
  'inventory.reservations.view', 'inventory.reservations.manage',
  'inventory.view_item_ledger', 'inventory.traceability.view', 'inventory.planning.view',
  'inventory.reports.view', 'inventory.setup.manage',
  'inventory.stock_count.view', 'inventory.stock_count.create', 'inventory.stock_count.count',
  'inventory.stock_count.reveal_system_quantity', 'inventory.stock_count.review',
  'inventory.stock_count.request_recount', 'inventory.stock_count.approve', 'inventory.stock_count.post',

  'production.view', 'production.create', 'production.edit', 'production.submit', 'production.approve',
  'production.release', 'production.post', 'production.cancel', 'production.close', 'production.print',
  'production.export', 'production.override',

  'manufacturing.view', 'manufacturing.dashboard.view',
  'manufacturing.bom.view', 'manufacturing.bom.create', 'manufacturing.bom.edit',
  'manufacturing.bom.activate', 'manufacturing.bom.deactivate', 'manufacturing.bom.view_cost',
  'manufacturing.bom.import',
  'manufacturing.production_plan.view',
  'manufacturing.production_plan.create',
  'manufacturing.production_plan.edit',
  'manufacturing.production_plan.release',
  'manufacturing.production_plan.close',
  'manufacturing.production_plan.create_work_order',
  'manufacturing.view_audit',
  'manufacturing.work_orders.view', 'manufacturing.work_orders.create', 'manufacturing.work_orders.edit',
  'manufacturing.work_orders.start', 'manufacturing.work_orders.hold', 'manufacturing.work_orders.resume',
  'manufacturing.work_orders.cancel', 'manufacturing.work_orders.close',
  'manufacturing.work_orders.close_with_difference', 'manufacturing.work_orders.reopen',
  'manufacturing.work_orders.override_route',
  // Phase 2A â€” Production Demand + Work Order execution (no inventory/quality/GL)
  'manufacturing.demand.view', 'manufacturing.demand.create', 'manufacturing.demand.convert',
  'manufacturing.work_orders.release', 'manufacturing.work_orders.assign',
  'manufacturing.stage.view', 'manufacturing.stage.execute',
  'manufacturing.progress.record', 'manufacturing.progress.correct',
  'manufacturing.progress.reverse',
  'manufacturing.timeline.view', 'manufacturing.control_room.view',
  // Phase 2B â€” assignments, daily production, issues, operator UX
  'manufacturing.daily_production.view', 'manufacturing.daily_production.create', 'manufacturing.daily_production.submit',
  'manufacturing.daily_production.reverse',
  'manufacturing.assignment.view', 'manufacturing.assignment.manage', 'manufacturing.assignment.reassign',
  'manufacturing.operator.my_work', 'manufacturing.operator.start', 'manufacturing.operator.pause', 'manufacturing.operator.complete',
  'manufacturing.issue.view', 'manufacturing.issue.report', 'manufacturing.issue.acknowledge', 'manufacturing.issue.resolve',
  'manufacturing.downtime.view', 'manufacturing.downtime.manage',
  'manufacturing.materials.view', 'manufacturing.materials.reserve',
  'manufacturing.materials.create_requirement', 'manufacturing.materials.issue',
  'manufacturing.materials.return', 'manufacturing.materials.transfer',
  'manufacturing.material_position.view',
  'manufacturing.material.reconcile',
  'manufacturing.material.release_reservation',
  'manufacturing.material.reallocate',
  'manufacturing.material.additional_issue',
  'manufacturing.material_issue.reverse',
  'manufacturing.material_return.reverse',
  'manufacturing.material_transfer.reverse',
  'manufacturing.wip.move',
  'manufacturing.wip.reverse',
  'manufacturing.production.complete', 'manufacturing.production.complete_and_close',
  'manufacturing.quality.view', 'manufacturing.quality.inspect', 'manufacturing.quality.accept_deviation',
  'manufacturing.scrap.record', 'manufacturing.rework.manage',
  'manufacturing.cost.view', 'manufacturing.variance.view',
  // Phase 7E â€” manufacturing costing + accounting productionisation
  'manufacturing.costing_policy.view', 'manufacturing.costing_policy.manage',
  'manufacturing.account_mapping.view', 'manufacturing.account_mapping.manage',
  'manufacturing.cost.calculate', 'manufacturing.cost.details', 'manufacturing.cost.provisional_view',
  'manufacturing.accounting.view', 'manufacturing.accounting.validate', 'manufacturing.accounting.post',
  'manufacturing.accounting.retry', 'manufacturing.accounting.financial_close',
  'manufacturing.accounting.reconcile',
  'manufacturing.accounting.readiness',
  'manufacturing.accounting.reconcile_signoff',
  'manufacturing.accounting.finance_signoff',
  'manufacturing.accounting.enable',
  'manufacturing.accounting.disable',
  'manufacturing.accounting.failed_events.view',
  'manufacturing.accounting.failed_events.retry',
  'manufacturing.cost_reports.view', 'manufacturing.cost_reports.export',
  'manufacturing.job_work.view', 'manufacturing.job_work.create', 'manufacturing.job_work.edit',
  'manufacturing.job_work.dispatch', 'manufacturing.job_work.receive',
  'manufacturing.job_work.return_material', 'manufacturing.job_work.reconcile',
  'manufacturing.job_work.approve_difference', 'manufacturing.job_work.link_invoice',
  'manufacturing.job_work.close', 'manufacturing.job_work.cancel', 'manufacturing.job_work.view_cost',
  'manufacturing.job_work_dispatch.reverse',
  'manufacturing.job_work_receipt.reverse',
  'manufacturing.split.reverse',
  // Phase 5C â€” transaction corrections / reversals
  'manufacturing.correction.view',
  'manufacturing.correction.request',
  'manufacturing.correction.approve',
  'manufacturing.correction.reject',
  'manufacturing.correction.apply',
  'manufacturing.correction.admin',
  'manufacturing.reports.view', 'manufacturing.reports.export',
  'manufacturing.settings.view', 'manufacturing.settings.manage',
  // Phase 5A â€” runtime change requests (manufacturing-scoped approval workflow)
  'manufacturing.runtime_change.view', 'manufacturing.runtime_change.request',
  'manufacturing.runtime_change.apply', 'manufacturing.runtime_change.approve',
  'manufacturing.runtime_change.reject', 'manufacturing.runtime_change.quantity',
  'manufacturing.runtime_change.schedule', 'manufacturing.runtime_change.assignment',
  'manufacturing.runtime_change.machine', 'manufacturing.runtime_change.work_centre',
  'manufacturing.runtime_change.route', 'manufacturing.runtime_change.skip',
  'manufacturing.runtime_change.job_work', 'manufacturing.runtime_change.hold',
  'manufacturing.runtime_change.admin',
  'manufacturing.routes.view', 'manufacturing.routes.create', 'manufacturing.routes.edit',
  'manufacturing.routes.activate',
  'manufacturing.routes.validate',
  'manufacturing.routes.certify',
  'manufacturing.routes.version',
  'manufacturing.routes.close',
  'manufacturing.setup.view',
  'manufacturing.profile.view', 'manufacturing.profile.manage',
  'manufacturing.warehouse_mapping.view', 'manufacturing.warehouse_mapping.manage',
  'manufacturing.store_workbench.view',
  'manufacturing.wip_stock.view',
  'manufacturing.fg_receipt.view', 'manufacturing.fg_receipt.create', 'manufacturing.fg_receipt.post',
  'manufacturing.fg_receipt.reverse',
  'manufacturing.work_order.close_readiness',
  'manufacturing.work_centre.view', 'manufacturing.work_centre.manage',
  'manufacturing.machine.view', 'manufacturing.machine.manage',

  // Maintenance V1
  'maintenance.view',
  'maintenance.create',
  'maintenance.start',
  'maintenance.update',
  'maintenance.test',
  'maintenance.close',
  'maintenance.cost.view',
  'maintenance.cost.manage',
  'maintenance.report.view',

  // HRMS Phase 1 â€” foundation + employee master
  'hrms.employee.view',
  'hrms.employee.create',
  'hrms.employee.edit',
  'hrms.employee.sensitive.view',
  'hrms.designation.view',
  'hrms.designation.manage',
  'hrms.shift.view',
  'hrms.shift.manage',
  'hrms.holiday.view',
  'hrms.holiday.manage',
  'hrms.roster.view',
  'hrms.roster.manage',
  'hrms.leave.view',
  'hrms.leave.apply',
  'hrms.leave.approve',
  'hrms.leave.manage',
  'hrms.leave.balance.view',
  'hrms.leave.balance.manage',
  'hrms.leave.type.manage',
  'hrms.attendance.view',
  'hrms.attendance.manage',

  // HRMS Phase 5 â€” Overtime management
  'hrms.overtime.view',
  'hrms.overtime.create',
  'hrms.overtime.approve',
  'hrms.overtime.manage',
  'hrms.overtime.override_limit',

  // HRMS Phase 6 â€” Salary structure & assignments
  'hrms.salary.component.view',
  'hrms.salary.component.manage',
  'hrms.salary.structure.view',
  'hrms.salary.structure.manage',
  'hrms.salary.assignment.view',
  'hrms.salary.assignment.manage',

  // HRMS Phase 7 â€” Payroll run & calculation
  'hrms.payroll.view',
  'hrms.payroll.create',
  'hrms.payroll.calculate',
  'hrms.payroll.review',
  'hrms.payroll.finalize',

  // HRMS Phase 8 â€” Statutory (PF/ESIC/PT/TDS/LWF) rules, profiles & registers
  'hrms.statutory.view',
  'hrms.statutory.manage',
  'hrms.statutory.override',
  'hrms.statutory.reports',

  // HRMS Phase 9 â€” Payslip + payroll accounting + salary payment
  'hrms.payslip.view',
  'hrms.payslip.generate',
  'hrms.payroll.accounting.view',
  'hrms.payroll.accounting.post',
  'hrms.salary_payment.view',
  'hrms.salary_payment.create',
  'hrms.salary_payment.approve',
  'hrms.salary_payment.confirm',
  'hrms.salary_payment.export',

  // HRMS Phase 10 â€” Loans & salary advances
  'hrms.loan.view',
  'hrms.loan.create',
  'hrms.loan.approve',
  'hrms.loan.disburse',
  'hrms.loan.manage',
  'hrms.loan.repayment',

  // HRMS Phase 11 â€” Exit & Full & Final
  'hrms.exit.view',
  'hrms.exit.create',
  'hrms.exit.approve',
  'hrms.exit.clearance',
  'hrms.fnf.view',
  'hrms.fnf.calculate',
  'hrms.fnf.approve',
  'hrms.fnf.post',
  'hrms.fnf.pay',

  // Phase 7D â€” reporting foundation (saved views, exception centre, traceability)
  'manufacturing.reports.saved_views',
  'manufacturing.reports.shared_views',
  'manufacturing.reports.production',
  'manufacturing.reports.shopfloor',
  'manufacturing.reports.shift',
  'manufacturing.reports.work_centres',
  'manufacturing.reports.downtime',
  'manufacturing.reports.materials',
  'manufacturing.reports.wip',
  'manufacturing.reports.job_work',
  'manufacturing.traceability.view',
  'manufacturing.traceability.export',

  'quality.view', 'quality.create', 'quality.edit', 'quality.submit', 'quality.approve',
  'quality.release', 'quality.post', 'quality.cancel', 'quality.close', 'quality.print',
  'quality.export', 'quality.override',
  'quality.decision.correct',
  // Incoming Quality Unification (queue/workspace; writes remain purchase.qi.*)
  'quality.incoming.view',
  'quality.incoming.assign',
  'quality.incoming.report',
  'inventory.stock_status.view',
  // Phase 7D â€” quality reporting
  'quality.reports.view',
  'quality.reports.production',
  'quality.reports.ncr',

  'dispatch.view', 'dispatch.create', 'dispatch.edit', 'dispatch.submit', 'dispatch.approve',
  'dispatch.release', 'dispatch.post', 'dispatch.cancel', 'dispatch.close', 'dispatch.print',
  'dispatch.pod.view', 'dispatch.pod.record',
  'dispatch.export', 'dispatch.override',
  // Phase 7C5 â€” reverse / reconciliation
  'dispatch.reverse.request',
  'dispatch.reverse.approve',
  'dispatch.reverse.apply',
  'dispatch.reconciliation.view',
  'dispatch.reconciliation.export',
  // Commercial O2C policy (partial / multi / invoice mode / POD)
  'dispatch.settings.view',
  'dispatch.settings.manage',
  // Phase 7C1 â€” requirements / readiness / draft orders
  'dispatch.requirement.view',
  'dispatch.requirement.synchronise',
  'dispatch.requirement.hold',
  'dispatch.requirement.release_hold',
  'dispatch.readiness.view',
  'dispatch.fulfilment.view',
  'dispatch.exceptions.view',
  'dispatch.order.view',
  'dispatch.order.create',
  'dispatch.order.edit',
  'dispatch.order.cancel',
  'dispatch.basic_confirm',
  'dispatch.legacy_7c0_use',
  // Phase 7C2 â€” reservation + picking
  'dispatch.reservation.view',
  'dispatch.reservation.create',
  'dispatch.reservation.release',
  'dispatch.reservation.reallocate',
  'dispatch.reservation.conflicts',
  'dispatch.pick_list.view',
  'dispatch.pick_list.create',
  'dispatch.pick_list.edit',
  'dispatch.pick_list.release',
  'dispatch.pick_list.assign',
  'dispatch.pick_list.start',
  'dispatch.pick_list.pick',
  'dispatch.pick_list.report_shortage',
  'dispatch.pick_list.resolve_shortage',
  'dispatch.pick_list.unpick',
  'dispatch.pick_list.complete',
  'dispatch.pick_list.cancel',
  'dispatch.tracking.view',
  'dispatch.tracking.allocate',
  // Phase 7C3 â€” packing (operational allocation)
  'dispatch.packing.view',
  'dispatch.packing.create',
  'dispatch.packing.edit',
  'dispatch.packing.start',
  'dispatch.packing.complete',
  'dispatch.packing.verify',
  'dispatch.packing.reopen',
  'dispatch.packing.cancel',
  'dispatch.package.view',
  'dispatch.package.create',
  'dispatch.package.edit',
  'dispatch.package.pack',
  'dispatch.package.unpack',
  'dispatch.package.move',
  'dispatch.package.complete',
  'dispatch.package.verify',
  'dispatch.package.reopen',
  'dispatch.package.cancel',
  'dispatch.packing_shortage.view',
  'dispatch.packing_shortage.report',
  'dispatch.packing_shortage.resolve',
  'dispatch.packing_reports.view',
  'dispatch.packing_reports.export',
  // Phase 7C4 â€” Delivery Challan (document only)
  'dispatch.challan.view',
  'dispatch.challan.create',
  'dispatch.challan.edit',
  'dispatch.challan.submit',
  'dispatch.challan.approve',
  'dispatch.challan.issue',
  'dispatch.challan.print',
  'dispatch.challan.download',
  'dispatch.challan.cancel',
  'dispatch.challan.supersede',
  'dispatch.challan.transport_edit',
  'dispatch.challan.override_warning',
  'dispatch.challan.reports',
  'dispatch.challan.export',
  // Phase 7D â€” dispatch reporting (7C0 SO fulfilment scope only)
  'dispatch.reports.view',
  'dispatch.reports.fulfilment',
  'dispatch.reports.invoice_readiness',

  // Gate & Security
  'gate.dashboard.view',
  'gate.register.view',
  'gate.visitor.view',
  'gate.visitor.create',
  'gate.visitor.edit',
  'gate.visitor.approve',
  'gate.visitor.entry',
  'gate.visitor.exit',
  'gate.vehicle.view',
  'gate.vehicle.create',
  'gate.vehicle.edit',
  'gate.vehicle.entry',
  'gate.vehicle.exit',
  'gate.material_inward.view',
  'gate.material_inward.create',
  'gate.material_inward.edit',
  'gate.material_outward.view',
  'gate.material_outward.verify',
  'gate.material_outward.release',
  'gate.pass.view',
  'gate.pass.create',
  'gate.pass.edit',
  'gate.pass.approve',
  'gate.pass.return',
  'gate.contractor.view',
  'gate.contractor.create',
  'gate.contractor.exit',
  'gate.courier.view',
  'gate.courier.create',
  'gate.courier.handover',
  'gate.approval.view',
  'gate.approval.action',
  'gate.report.view',
  'gate.settings.manage',

  // Phase 7D â€” cross-module operational exception centre
  'operations.exceptions.view',
  'operations.exceptions.manage',

  'sales.view', 'sales.create', 'sales.edit', 'sales.submit', 'sales.approve',
  'sales.release', 'sales.post', 'sales.cancel', 'sales.close', 'sales.print',
  'sales.export', 'sales.override',

  'accounts.view', 'accounts.create', 'accounts.edit', 'accounts.submit', 'accounts.approve',
  'accounts.release', 'accounts.post', 'accounts.cancel', 'accounts.close', 'accounts.print',
  'accounts.export', 'accounts.override',

  'dms.view', 'dms.create', 'dms.edit', 'dms.submit', 'dms.approve',
  'dms.release', 'dms.post', 'dms.cancel', 'dms.close', 'dms.print',
  'dms.export', 'dms.override',

  'approval.view', 'approval.create', 'approval.edit', 'approval.submit', 'approval.approve',
  'approval.release', 'approval.post', 'approval.cancel', 'approval.close', 'approval.print',
  'approval.export', 'approval.override',

  'reports.view', 'reports.create', 'reports.edit', 'reports.submit', 'reports.approve',
  'reports.release', 'reports.post', 'reports.cancel', 'reports.close', 'reports.print',
  'reports.export', 'reports.override',

  // CEO Executive Dashboard Builder
  'executive.dashboard.view',
  'executive.dashboard.configure',
  'executive.dashboard.share',

  'traceability.view', 'traceability.create', 'traceability.edit', 'traceability.submit',
  'traceability.approve', 'traceability.release', 'traceability.post', 'traceability.cancel',
  'traceability.close', 'traceability.print', 'traceability.export', 'traceability.override',

  'settings.view', 'settings.create', 'settings.edit', 'settings.submit', 'settings.approve',
  'settings.release', 'settings.post', 'settings.cancel', 'settings.close', 'settings.print',
  'settings.export', 'settings.override',// Knowledge Base / OpenKB (Wave 1)
  'kb.document.view',
  'kb.document.create',
  'kb.document.update',
  'kb.document.delete',
  'kb.document.reindex',
  'kb.search.view',
  'kb.chat.use',
  'kb.copilot.use',
  'kb.insights.view',
  'kb.analytics.view',
  'kb.category.manage',
  'kb.tag.manage',
  'kb.admin.manage',
] as const

export type PermissionName = (typeof PERMISSIONS)[number]

/** Platform-only permissions â€” never granted to tenant-scoped admin roles. */
const PLATFORM_ONLY_PERMISSIONS = new Set<PermissionName>([
  'tenant.manage',
  'tenant.create',
  'tenant.delete',
])

/**
 * Full workspace grant for Tenant Admin / Admin / Administrator.
 * Every catalog permission except platform tenant lifecycle keys.
 */
export const TENANT_ADMIN_PERMISSIONS: PermissionName[] = PERMISSIONS.filter(
  (p) => !PLATFORM_ONLY_PERMISSIONS.has(p),
)

const MASTER_VIEW_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('master.') && p.endsWith('.view'))
/** Knowledge read/use grants for typical operators and Viewer. */
const KB_USE_PERMISSIONS: PermissionName[] = PERMISSIONS.filter(
  (p) =>
    p === 'kb.document.view' ||
    p === 'kb.search.view' ||
    p === 'kb.chat.use' ||
    p === 'kb.copilot.use' ||
    p === 'kb.insights.view',
)
/** Full Knowledge admin suite (document write + taxonomy + settings). */
const KB_ADMIN_PERMISSIONS: PermissionName[] = PERMISSIONS.filter((p) => p.startsWith('kb.'))
const PURCHASE_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('purchase.'))
const PURCHASE_OPS = PURCHASE_PERMISSIONS.filter(
  (p) =>
    p !== 'purchase.setup.manage' &&
    p !== 'purchase.setup.view' &&
    p !== 'purchase.approvals.self_approve',
)
const FINANCE_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('finance.'))
const FINANCE_VIEW_PERMISSIONS = FINANCE_PERMISSIONS.filter(
  (p) => p.endsWith('.view') || p === 'finance.view' || p === 'finance.audit.view',
)
const PRODUCTION_PERMISSIONS = PERMISSIONS.filter(
  (p) => p.startsWith('production.') || p.startsWith('manufacturing.'),
)
const INVENTORY_MODULE_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('inventory.'))
const DISPATCH_MODULE_PERMISSIONS = PERMISSIONS.filter((p) => p.startsWith('dispatch.'))
const DISPATCH_7C1_MANAGER_PERMISSIONS = DISPATCH_MODULE_PERMISSIONS
const DISPATCH_7C1_USER_PERMISSIONS = PERMISSIONS.filter(
  (p) =>
    p === 'dispatch.view' ||
    p === 'dispatch.create' ||
    p === 'dispatch.edit' ||
    p === 'dispatch.cancel' ||
    p === 'dispatch.requirement.view' ||
    p === 'dispatch.readiness.view' ||
    p === 'dispatch.fulfilment.view' ||
    p === 'dispatch.exceptions.view' ||
    p === 'dispatch.order.view' ||
    p === 'dispatch.order.create' ||
    p === 'dispatch.order.edit' ||
    p === 'dispatch.order.cancel' ||
    p === 'dispatch.reservation.view' ||
    p === 'dispatch.pick_list.view' ||
    p === 'dispatch.packing.view' ||
    p === 'dispatch.package.view' ||
    p === 'dispatch.packing_shortage.view' ||
    p === 'dispatch.challan.view' ||
    p === 'dispatch.tracking.view' ||
    p === 'dispatch.reports.view' ||
    p === 'dispatch.reports.fulfilment',
)
const FINANCE_EXECUTIVE_MANAGE: PermissionName[] = [
  'finance.settings.manage',
  'finance.coa.manage',
  'finance.default_mapping.manage',
  'finance.cost_centre.manage',
  'finance.number_series.manage',
  'finance.voucher.create',
  'finance.voucher.edit',
  'finance.voucher.submit',
  'finance.gl.view',
  'finance.posting_event.view',
  'finance.posting_rule.view',
  'finance.ar.invoice.create',
  'finance.ar.invoice.edit',
  'finance.ar.invoice.cancel',
  'finance.ar.receipt.create',
  'finance.ar.receipt.edit',
  'finance.ar.receipt.cancel',
  'finance.ar.allocation.create',
  'finance.ar.credit_note.create',
  'finance.ar.credit_note.edit',
  'finance.ar.credit_note.submit',
  'finance.ar.credit_note.cancel',
  'finance.ar.credit_note.mark_ready',
  'finance.ap.vendor_invoice.create',
  'finance.ap.vendor_invoice.edit',
  'finance.ap.vendor_invoice.submit',
  'finance.ap.vendor_invoice.cancel',
  'finance.ap.vendor_invoice.mark_ready',
  'finance.ap.payment.create',
  'finance.ap.payment.edit',
  'finance.ap.payment.submit',
  'finance.ap.payment.cancel',
  'finance.ap.payment.mark_ready',
  'finance.ap.allocation.create',
  'finance.ap.adjustment.create',
  'finance.ap.adjustment.edit',
  'finance.ap.adjustment.submit',
  'finance.ap.adjustment.cancel',
  'finance.ap.adjustment.mark_ready',
  'finance.ap.reconciliation.run',
  'finance.ap.reconciliation.export',
  'finance.ap.reconciliation.exception.acknowledge',
  'finance.ap.close_gate.run',
  'finance.ap.close_gate.export',
  'finance.treasury.account.create',
  'finance.treasury.account.edit',
  'finance.treasury.account.activate',
  'finance.treasury.account.deactivate',
  'finance.treasury.account.close',
  'finance.treasury.payment_mapping.manage',
  'finance.treasury.reconciliation_settings.manage',
]

export const ROLE_PERMISSIONS: Record<string, PermissionName[]> = {
  'Super Admin': [...PERMISSIONS],
  /** Full tenant workspace access (all modules except platform tenant.*). */
  'Tenant Admin': [...TENANT_ADMIN_PERMISSIONS],
  /** Alias some tenants may use â€” same grant set as Tenant Admin. */
  Admin: [...TENANT_ADMIN_PERMISSIONS],
  /** Product persona name â€” same grant set as Tenant Admin (includes purchase.setup.manage). */
  Administrator: [...TENANT_ADMIN_PERMISSIONS],
  /** Executive alias â€” full workspace access for testing / leadership accounts. */
  CEO: [...TENANT_ADMIN_PERMISSIONS],
  'Master Data Manager': PERMISSIONS.filter((p) => p.startsWith('master.') || p.startsWith('masters.')),
  'Purchase Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'master.vendor.create',
    'master.vendor.update',
    'master.vendor.delete',
    'master.vendor.import',
    ...PURCHASE_OPS,
  ],
  'Purchase Executive': [
    ...MASTER_VIEW_PERMISSIONS,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.pr.view',
    'purchase.pr.create',
    'purchase.pr.edit',
    'purchase.pr.submit',
    'purchase.planning.view',
    'purchase.planning.edit',
    'purchase.planning.assign_buyer',
    'purchase.planning.select_vendor',
    'purchase.planning.create_po',
    'purchase.rfq.view',
    'purchase.rfq.create',
    'purchase.rfq.send',
    'purchase.rfq.enter_quote',
    'purchase.rfq.compare',
    'purchase.po.view',
    'purchase.po.create',
    'purchase.po.edit',
    'purchase.grn.view',
    'purchase.quality.view',
    'purchase.invoice.view',
    'purchase.return.view',
    'purchase.reports.view',
  ],
  /** Requester: create / edit own drafts / view / submit PR only. */
  Requester: [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.pr.view',
    'purchase.pr.create',
    'purchase.pr.edit',
    'purchase.pr.submit',
    'master.lookup.view',
    'master.item.view',
  ],
  /**
   * Department Manager â€” view department PRs; approve / reject / send back.
   * `Department Head` kept as an alias for existing tenants.
   */
  'Department Manager': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.pr.view',
    'purchase.pr.create',
    'purchase.pr.edit',
    'purchase.pr.submit',
    'purchase.pr.approve',
    'purchase.pr.reject',
    'purchase.reports.view',
    'master.lookup.view',
    'master.item.view',
  ],
  'Department Head': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.pr.view',
    'purchase.pr.create',
    'purchase.pr.edit',
    'purchase.pr.submit',
    'purchase.pr.approve',
    'purchase.pr.reject',
    'purchase.reports.view',
    'master.lookup.view',
    'master.item.view',
  ],
  'Store Executive': [
    ...MASTER_VIEW_PERMISSIONS,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.po.view',
    'purchase.grn.view',
    'purchase.grn.create',
    'purchase.grn.post',
    'purchase.quality.view',
    'purchase.qi.view',
    'purchase.return.view',
    'purchase.return.create',
    'purchase.return.edit',
    'purchase.return.submit',
    'purchase.return.complete',
    'purchase.return.cancel',
    'purchase.return.post',
    'purchase.reports.view',
    'dispatch.pick_list.view',
    'dispatch.pick_list.start',
    'dispatch.pick_list.pick',
    'dispatch.pick_list.report_shortage',
    'dispatch.pick_list.unpick',
    'dispatch.tracking.view',
  ],
  'Quality Inspector': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.grn.view',
    'purchase.quality.view',
    'purchase.quality.inspect',
    'purchase.qi.view',
    'purchase.qi.create',
    'purchase.qi.edit',
    'purchase.qi.complete',
    'purchase.qi.cancel',
    'purchase.return.view',
    // Incoming Quality Unification — inspector
    'quality.incoming.view',
    'quality.incoming.assign',
    'inventory.stock_status.view',
    // Manufacturing / shopfloor QC kiosk (module quality.* + manufacturing.quality.*)
    'quality.view',
    'quality.create',
    'quality.edit',
    'quality.submit',
    'quality.cancel',
    'quality.close',
    'quality.reports.view',
    'quality.reports.production',
    'quality.reports.ncr',
    'manufacturing.view',
    'manufacturing.quality.view',
    'manufacturing.quality.inspect',
    'manufacturing.work_orders.view',
    'master.lookup.view',
    'master.item.view',
  ],
  'Incoming QC Inspector': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.grn.view',
    'purchase.qi.view',
    'purchase.qi.create',
    'purchase.qi.edit',
    'purchase.qi.complete',
    'purchase.return.view',
    'quality.incoming.view',
    'quality.incoming.assign',
    'quality.view',
    'quality.create',
    'inventory.stock_status.view',
    'inventory.view',
    'master.lookup.view',
    'master.item.view',
    'master.vendor.view',
  ],
  'Quality Manager': [
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.grn.view',
    'purchase.qi.view',
    'purchase.qi.create',
    'purchase.qi.edit',
    'purchase.qi.complete',
    'purchase.qi.cancel',
    'purchase.return.view',
    'purchase.return.create',
    'quality.incoming.view',
    'quality.incoming.assign',
    'quality.incoming.report',
    'quality.view',
    'quality.create',
    'quality.edit',
    'quality.submit',
    'quality.approve',
    'quality.override',
    'quality.close',
    'quality.reports.view',
    'quality.reports.production',
    'quality.reports.ncr',
    'inventory.stock_status.view',
    'inventory.view',
    'manufacturing.view',
    'manufacturing.quality.view',
    'manufacturing.quality.inspect',
    'master.lookup.view',
    'master.item.view',
    'master.vendor.view',
  ],
  'Finance Executive': [
    ...FINANCE_VIEW_PERMISSIONS,
    ...FINANCE_EXECUTIVE_MANAGE,
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.po.view',
    'purchase.grn.view',
    'purchase.invoice.view',
    'purchase.invoice.create',
    'purchase.invoice.edit',
    'purchase.invoice.submit',
    'purchase.invoice.verify',
    'purchase.invoice.cancel',
    'purchase.return.view',
    'purchase.reports.view',
    'master.lookup.view',
    'master.vendor.view',
    'manufacturing.cost.view',
    'manufacturing.cost.details',
    'manufacturing.cost.provisional_view',
    'manufacturing.accounting.view',
    'manufacturing.accounting.validate',
    'manufacturing.accounting.reconcile',
    'manufacturing.accounting.readiness',
    'manufacturing.cost_reports.view',
  ],
  'Finance Manager': [
    ...FINANCE_PERMISSIONS,
    'organisation.view',
    'organisation.create',
    'organisation.update',
    'executive.dashboard.view',
    'executive.dashboard.configure',
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.po.view',
    'purchase.grn.view',
    'purchase.invoice.view',
    'purchase.invoice.create',
    'purchase.invoice.edit',
    'purchase.invoice.submit',
    'purchase.invoice.verify',
    'purchase.invoice.approve',
    'purchase.invoice.post',
    'purchase.invoice.cancel',
    'purchase.return.view',
    'purchase.reports.view',
    'master.lookup.view',
    'master.vendor.view',
    'manufacturing.cost.view',
    'manufacturing.cost.details',
    'manufacturing.cost.provisional_view',
    'manufacturing.costing_policy.view',
    'manufacturing.account_mapping.view',
    'manufacturing.account_mapping.manage',
    'manufacturing.accounting.view',
    'manufacturing.accounting.validate',
    'manufacturing.accounting.post',
    'manufacturing.accounting.retry',
    'manufacturing.accounting.financial_close',
    'manufacturing.accounting.reconcile',
    'manufacturing.accounting.readiness',
    'manufacturing.accounting.finance_signoff',
    'manufacturing.accounting.enable',
    'manufacturing.accounting.disable',
    'manufacturing.accounting.failed_events.view',
    'manufacturing.accounting.failed_events.retry',
    'manufacturing.cost_reports.view',
    'manufacturing.cost_reports.export',
  ],
  Management: [
    'executive.dashboard.view',
    'executive.dashboard.configure',
    'executive.dashboard.share',
    'purchase.view',
    'purchase.dashboard.view',
    'purchase.pr.view',
    'purchase.pr.approve',
    'purchase.pr.reject',
    'purchase.planning.view',
    'purchase.planning.approve',
    'purchase.rfq.view',
    'purchase.rfq.compare',
    'purchase.rfq.award',
    'purchase.po.view',
    'purchase.po.approve',
    'purchase.po.send',
    'purchase.po.cancel',
    'purchase.grn.view',
    'purchase.quality.view',
    'purchase.invoice.view',
    'purchase.invoice.approve',
    'purchase.return.view',
    'purchase.reports.view',
  ],
  'Inventory Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'master.item.create',
    'master.item.update',
    'master.item.delete',
    'master.item.import',
    'master.item_category.create',
    'master.item_category.update',
    'master.item_category.delete',
    'master.uom.create',
    'master.uom.update',
    'master.uom.delete',
    'master.plant.create',
    'master.plant.update',
    'master.plant.delete',
    'master.warehouse.create',
    'master.warehouse.update',
    'master.warehouse.delete',
    'master.location.create',
    'master.location.update',
    'master.location.delete',
    'master.bin.create',
    'master.bin.update',
    'master.bin.delete',
    ...INVENTORY_MODULE_PERMISSIONS,
    'manufacturing.accounting.view',
    'manufacturing.accounting.readiness',
    'manufacturing.accounting.reconcile',
    'manufacturing.accounting.reconcile_signoff',
    'dispatch.requirement.view',
    'dispatch.readiness.view',
    'dispatch.fulfilment.view',
    'dispatch.exceptions.view',
    'dispatch.order.view',
    'dispatch.reports.view',
    'dispatch.reports.fulfilment',
    'dispatch.reservation.view',
    'dispatch.reservation.create',
    'dispatch.reservation.release',
    'dispatch.reservation.reallocate',
    'dispatch.reservation.conflicts',
    'dispatch.pick_list.view',
    'dispatch.pick_list.create',
    'dispatch.pick_list.edit',
    'dispatch.pick_list.release',
    'dispatch.pick_list.assign',
    'dispatch.pick_list.start',
    'dispatch.pick_list.pick',
    'dispatch.pick_list.report_shortage',
    'dispatch.pick_list.resolve_shortage',
    'dispatch.pick_list.unpick',
    'dispatch.pick_list.complete',
    'dispatch.pick_list.cancel',
    'dispatch.packing.view',
    'dispatch.packing.create',
    'dispatch.packing.edit',
    'dispatch.packing.start',
    'dispatch.packing.complete',
    'dispatch.packing.verify',
    'dispatch.packing.reopen',
    'dispatch.packing.cancel',
    'dispatch.package.view',
    'dispatch.package.create',
    'dispatch.package.edit',
    'dispatch.package.pack',
    'dispatch.package.unpack',
    'dispatch.package.move',
    'dispatch.package.complete',
    'dispatch.package.verify',
    'dispatch.package.reopen',
    'dispatch.package.cancel',
    'dispatch.packing_shortage.view',
    'dispatch.packing_shortage.report',
    'dispatch.packing_shortage.resolve',
    'dispatch.packing_reports.view',
    'dispatch.packing_reports.export',
    'dispatch.challan.view',
    'dispatch.challan.create',
    'dispatch.challan.edit',
    'dispatch.challan.submit',
    'dispatch.challan.approve',
    'dispatch.challan.issue',
    'dispatch.challan.print',
    'dispatch.challan.download',
    'dispatch.challan.cancel',
    'dispatch.challan.supersede',
    'dispatch.challan.transport_edit',
    'dispatch.challan.override_warning',
    'dispatch.challan.reports',
    'dispatch.challan.export',
    'dispatch.tracking.view',
    'dispatch.tracking.allocate',
  ],
  'Dispatch Manager': [
    ...MASTER_VIEW_PERMISSIONS,
    'crm.sales_order.view',
    'crm.company.view',
    'inventory.stock.view',
    'inventory.view',
    'quality.view',
    'manufacturing.work_orders.view',
    'manufacturing.traceability.view',
    ...DISPATCH_7C1_MANAGER_PERMISSIONS,
  ],
  'Dispatch User': [
    ...MASTER_VIEW_PERMISSIONS,
    'crm.sales_order.view',
    'crm.company.view',
    'inventory.stock.view',
    'quality.view',
    ...DISPATCH_7C1_USER_PERMISSIONS,
    'dispatch.pick_list.create',
    'dispatch.pick_list.start',
    'dispatch.pick_list.pick',
    'dispatch.pick_list.report_shortage',
    'dispatch.pick_list.unpick',
    'dispatch.pick_list.complete',
    'dispatch.packing.create',
    'dispatch.packing.start',
    'dispatch.packing.complete',
    'dispatch.package.create',
    'dispatch.package.pack',
    'dispatch.package.unpack',
    'dispatch.package.move',
    'dispatch.package.complete',
    'dispatch.packing_shortage.report',
    'dispatch.challan.create',
    'dispatch.challan.edit',
    'dispatch.challan.submit',
    'dispatch.challan.print',
  ],
  'Sales Manager': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update', 'crm.lead.delete', 'crm.lead.assign', 'crm.lead.qualify', 'crm.lead.convert',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update', 'crm.contact.delete',
    'crm.company.view', 'crm.company.create', 'crm.company.update', 'crm.company.delete',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete', 'crm.activity.delete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update', 'crm.follow_up.delete',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update', 'crm.opportunity.close', 'crm.opportunity.delete',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update', 'crm.quotation.delete', 'crm.quotation.approve',
    'crm.quotation.convert',
    'crm.sales_order.view', 'crm.sales_order.create', 'crm.sales_order.update', 'crm.sales_order.delete', 'crm.sales_order.confirm',
    'crm.commercial.view',
    'crm.commercial.receipt.view', 'crm.commercial.receipt.create',
    'crm.commercial.receipt.accounting_draft.create',
    'crm.commercial.invoice.view', 'crm.commercial.invoice.create', 'crm.commercial.invoice.post', 'crm.commercial.invoice.cancel',
    'crm.commercial.allocation.view', 'crm.commercial.allocation.create', 'crm.commercial.allocation.reverse',
    'crm.import.view', 'crm.import.execute',
    'crm.master.view', 'crm.master.create', 'crm.master.update', 'crm.master.delete',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view', 'crm.export.view', 'crm.export.execute',
    'executive.dashboard.view',
    'crm.note.view', 'crm.note.create', 'crm.note.update', 'crm.note.delete',
    'crm.attachment.view', 'crm.attachment.create', 'crm.attachment.delete',
    'crm.indiamart.view',
    'crm.indiamart.enquiry.view', 'crm.indiamart.enquiry.import', 'crm.indiamart.enquiry.assign',
    'crm.indiamart.enquiry.ignore', 'crm.indiamart.enquiry.bulk_manage',
    'crm.indiamart.sync.run', 'crm.indiamart.sync_history.view',
    'crm.indiamart.settings.view', 'crm.indiamart.settings.manage', 'crm.indiamart.credentials.manage',
    'crm.indiamart.product_mapping.manage',
    'user.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
    'dispatch.requirement.view',
    'dispatch.readiness.view',
    'dispatch.fulfilment.view',
    'dispatch.exceptions.view',
    'dispatch.order.view',
    'dispatch.order.create',
    'dispatch.reports.view',
    'dispatch.reports.fulfilment',
    'dispatch.reservation.view',
    'dispatch.reservation.create',
    'dispatch.reservation.release',
    'dispatch.pick_list.view',
    'dispatch.pick_list.create',
    'dispatch.pick_list.edit',
    'dispatch.pick_list.release',
    'dispatch.pick_list.assign',
    'dispatch.pick_list.start',
    'dispatch.pick_list.pick',
    'dispatch.pick_list.report_shortage',
    'dispatch.pick_list.resolve_shortage',
    'dispatch.pick_list.unpick',
    'dispatch.pick_list.complete',
    'dispatch.pick_list.cancel',
    'dispatch.tracking.view',
    'dispatch.tracking.allocate',
  ],
  'Production Manager': [
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
    'master.item_category.view',
    'master.uom.view',
    'master.plant.view',
    'master.warehouse.view',
    'master.location.view',
    'master.bin.view',
    // Ops manufacturing only â€” Finance owns enable / sign-off / failed-event retry.
    ...PRODUCTION_PERMISSIONS.filter(
      (p) =>
        !p.startsWith('manufacturing.accounting.') ||
        p === 'manufacturing.accounting.view' ||
        p === 'manufacturing.accounting.readiness',
    ),
    // Manufacturing QC list/get needs module quality.view (decide can use manufacturing.quality.inspect)
    'quality.view',
    'quality.submit',
    // Phase 7D â€” cross-module reporting/exceptions visible to Production Manager
    'quality.reports.view',
    'quality.reports.production',
    'quality.reports.ncr',
    'dispatch.reports.view',
    'dispatch.reports.fulfilment',
    'dispatch.reports.invoice_readiness',
    'operations.exceptions.view',
    'operations.exceptions.manage',
    // Maintenance V1 â€” full operational access
    'maintenance.view',
    'maintenance.create',
    'maintenance.start',
    'maintenance.update',
    'maintenance.test',
    'maintenance.close',
    'maintenance.cost.view',
    'maintenance.cost.manage',
    'maintenance.report.view',
  ],
  'Production Supervisor': [
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
    'master.item_category.view',
    'master.uom.view',
    'master.warehouse.view',
    'master.location.view',
    'manufacturing.view',
    'manufacturing.setup.view',
    'manufacturing.profile.view',
    'manufacturing.bom.view',
    'manufacturing.routes.view',
    'manufacturing.work_centre.view',
    'manufacturing.machine.view',
    'manufacturing.work_orders.view',
    'manufacturing.dashboard.view',
    // Phase 2A â€” shopfloor execution (view + hands-on stage/progress work, no create/release)
    'manufacturing.demand.view',
    'manufacturing.work_orders.start',
    'manufacturing.work_orders.hold',
    'manufacturing.work_orders.resume',
    'manufacturing.work_orders.assign',
    'manufacturing.stage.view',
    'manufacturing.stage.execute',
    'manufacturing.progress.record',
    'manufacturing.timeline.view',
    'manufacturing.control_room.view',
    // Phase 2B â€” daily production + team assignments + issues
    'manufacturing.daily_production.view',
    'manufacturing.daily_production.create',
    'manufacturing.daily_production.submit',
    'manufacturing.assignment.view',
    'manufacturing.assignment.manage',
    'manufacturing.assignment.reassign',
    'manufacturing.operator.my_work',
    'manufacturing.issue.view',
    'manufacturing.issue.report',
    'manufacturing.issue.acknowledge',
    'manufacturing.issue.resolve',
    'manufacturing.downtime.view',
    'manufacturing.downtime.manage',
    // Phase 5A â€” runtime changes (assignment / hold / request)
    'manufacturing.runtime_change.view',
    'manufacturing.runtime_change.request',
    'manufacturing.runtime_change.apply',
    'manufacturing.runtime_change.assignment',
    'manufacturing.runtime_change.machine',
    'manufacturing.runtime_change.hold',
    // Phase 5B â€” WIP / material transfers
    'manufacturing.wip.move',
    'manufacturing.materials.transfer',
    'manufacturing.materials.view',
    'manufacturing.materials.issue',
    'manufacturing.materials.return',
    'manufacturing.material_position.view',
    'manufacturing.material.reconcile',
    'manufacturing.material.release_reservation',
    'manufacturing.material.reallocate',
    'manufacturing.material.additional_issue',
    // Maintenance V1 â€” coordinate repair / test (no cost manage / close)
    'maintenance.view',
    'maintenance.create',
    'maintenance.start',
    'maintenance.update',
    'maintenance.test',
    'maintenance.cost.view',
  ],
  'Production Operator': [
    'manufacturing.view',
    'manufacturing.operator.my_work',
    'manufacturing.operator.start',
    'manufacturing.operator.pause',
    'manufacturing.operator.complete',
    'manufacturing.issue.report',
    'manufacturing.issue.view',
    'manufacturing.downtime.view',
    // Product label on kiosk cards (read-only WO header fields)
    'manufacturing.work_orders.view',
    'master.item.view',
    // Maintenance V1 â€” report breakdown only
    'maintenance.view',
    'maintenance.create',
  ],
  'Production Engineer': [
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
    'master.item_category.view',
    'master.uom.view',
    'master.warehouse.view',
    'master.location.view',
    'manufacturing.view',
    'manufacturing.dashboard.view',
    'manufacturing.setup.view',
    'manufacturing.profile.view', 'manufacturing.profile.manage',
    'manufacturing.bom.view', 'manufacturing.bom.create', 'manufacturing.bom.edit',
    'manufacturing.bom.activate', 'manufacturing.bom.deactivate', 'manufacturing.bom.view_cost',
    'manufacturing.bom.import',
    'manufacturing.routes.view', 'manufacturing.routes.create', 'manufacturing.routes.edit',
    'manufacturing.routes.activate',
    'manufacturing.routes.validate',
    'manufacturing.routes.certify',
    'manufacturing.routes.version',
    'manufacturing.routes.close',
    'manufacturing.work_centre.view', 'manufacturing.work_centre.manage',
    'manufacturing.machine.view', 'manufacturing.machine.manage',
    'manufacturing.work_orders.view',
    // Phase 2A â€” planning/engineering visibility (no execution actions)
    'manufacturing.demand.view',
    'manufacturing.stage.view',
    'manufacturing.timeline.view',
    // Phase 2B â€” view assignments and issues only
    'manufacturing.assignment.view',
    'manufacturing.issue.view',
    'manufacturing.downtime.view',
    'manufacturing.daily_production.view',
    // Phase 5A â€” route / machine / work centre runtime changes
    'manufacturing.runtime_change.view',
    'manufacturing.runtime_change.request',
    'manufacturing.runtime_change.route',
    'manufacturing.runtime_change.skip',
    'manufacturing.runtime_change.machine',
    'manufacturing.runtime_change.work_centre',
    'manufacturing.runtime_change.schedule',
  ],
  'CRM Admin': PERMISSIONS.filter(
    (p) => p.startsWith('crm.') || p === 'user.view' || p === 'master.product.view' || p === 'master.lookup.view',
  ),
  'Sales Executive': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update',
    'crm.company.view',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update', 'crm.quotation.convert',
    'crm.sales_order.view', 'crm.sales_order.create', 'crm.sales_order.update', 'crm.sales_order.confirm',
    'crm.commercial.view',
    'crm.commercial.receipt.view', 'crm.commercial.receipt.create',
    'crm.commercial.receipt.accounting_draft.create',
    'crm.commercial.invoice.view', 'crm.commercial.invoice.create', 'crm.commercial.invoice.post', 'crm.commercial.invoice.cancel',
    'crm.commercial.allocation.view', 'crm.commercial.allocation.create',
    'crm.note.view', 'crm.note.create', 'crm.note.update',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view',
    'crm.indiamart.view', 'crm.indiamart.enquiry.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
  ],
  /** CRM-only persona â€” no purchase, manufacturing, inventory, finance, or admin modules. */
  'CRM User': [
    'crm.lead.view', 'crm.lead.create', 'crm.lead.update',
    'crm.contact.view', 'crm.contact.create', 'crm.contact.update',
    'crm.company.view',
    'crm.activity.view', 'crm.activity.create', 'crm.activity.update', 'crm.activity.complete',
    'crm.follow_up.view', 'crm.follow_up.create', 'crm.follow_up.update',
    'crm.pipeline.view',
    'crm.opportunity.view', 'crm.opportunity.create', 'crm.opportunity.update',
    'crm.quotation.view', 'crm.quotation.create', 'crm.quotation.update', 'crm.quotation.convert',
    'crm.sales_order.view', 'crm.sales_order.create', 'crm.sales_order.update', 'crm.sales_order.confirm',
    'crm.commercial.view',
    'crm.commercial.receipt.view', 'crm.commercial.receipt.create',
    'crm.commercial.receipt.accounting_draft.create',
    'crm.commercial.invoice.view', 'crm.commercial.invoice.create', 'crm.commercial.invoice.post', 'crm.commercial.invoice.cancel',
    'crm.commercial.allocation.view', 'crm.commercial.allocation.create',
    'crm.note.view', 'crm.note.create', 'crm.note.update',
    'crm.attachment.view', 'crm.attachment.create',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view', 'crm.export.view',
    'crm.indiamart.view', 'crm.indiamart.enquiry.view',
    'master.lookup.view',
    'master.item.view',
    'master.product.view',
  ],
  'HR Manager': [
    'hrms.employee.view',
    'hrms.employee.create',
    'hrms.employee.edit',
    'hrms.employee.sensitive.view',
    'hrms.designation.view',
    'hrms.designation.manage',
    'hrms.shift.view',
    'hrms.shift.manage',
    'hrms.holiday.view',
    'hrms.holiday.manage',
    'hrms.roster.view',
    'hrms.roster.manage',
    'hrms.leave.view',
    'hrms.leave.apply',
    'hrms.leave.approve',
    'hrms.leave.manage',
    'hrms.leave.balance.view',
    'hrms.leave.balance.manage',
    'hrms.leave.type.manage',
    'hrms.attendance.view',
    'hrms.attendance.manage',
    'hrms.overtime.view',
    'hrms.overtime.create',
    'hrms.overtime.approve',
    'hrms.overtime.manage',
    'hrms.overtime.override_limit',
    'hrms.salary.component.view',
    'hrms.salary.component.manage',
    'hrms.salary.structure.view',
    'hrms.salary.structure.manage',
    'hrms.salary.assignment.view',
    'hrms.salary.assignment.manage',
    'hrms.payroll.view',
    'hrms.payroll.create',
    'hrms.payroll.calculate',
    'hrms.payroll.review',
    'hrms.payroll.finalize',
    'hrms.statutory.view',
    'hrms.statutory.manage',
    'hrms.statutory.override',
    'hrms.statutory.reports',
    'hrms.payslip.view',
    'hrms.payslip.generate',
    'hrms.payroll.accounting.view',
    'hrms.payroll.accounting.post',
    'hrms.salary_payment.view',
    'hrms.salary_payment.create',
    'hrms.salary_payment.approve',
    'hrms.salary_payment.confirm',
    'hrms.salary_payment.export',
    'hrms.loan.view',
    'hrms.loan.create',
    'hrms.loan.approve',
    'hrms.loan.disburse',
    'hrms.loan.manage',
    'hrms.loan.repayment',
    'hrms.exit.view',
    'hrms.exit.create',
    'hrms.exit.approve',
    'hrms.exit.clearance',
    'hrms.fnf.view',
    'hrms.fnf.calculate',
    'hrms.fnf.approve',
    'hrms.fnf.post',
    'hrms.fnf.pay',
    'organisation.view',
    'finance.legal_entity.view',
    'finance.branch.view',
    'department.view',
    'manufacturing.work_centre.view',
    'user.view',
  ],
  'HR Executive': [
    'hrms.employee.view',
    'hrms.employee.create',
    'hrms.employee.edit',
    'hrms.designation.view',
    'hrms.designation.manage',
    'hrms.shift.view',
    'hrms.shift.manage',
    'hrms.holiday.view',
    'hrms.holiday.manage',
    'hrms.roster.view',
    'hrms.roster.manage',
    'hrms.leave.view',
    'hrms.leave.apply',
    'hrms.leave.approve',
    'hrms.leave.manage',
    'hrms.leave.balance.view',
    'hrms.leave.balance.manage',
    'hrms.leave.type.manage',
    'hrms.attendance.view',
    'hrms.attendance.manage',
    'hrms.overtime.view',
    'hrms.overtime.create',
    'hrms.overtime.approve',
    'hrms.overtime.manage',
    'hrms.overtime.override_limit',
    'hrms.salary.component.view',
    'hrms.salary.structure.view',
    'hrms.salary.assignment.view',
    'hrms.payroll.view',
    'hrms.payroll.create',
    'hrms.payroll.calculate',
    'hrms.payroll.review',
    'hrms.statutory.view',
    'hrms.statutory.reports',
    'hrms.payslip.view',
    'hrms.payslip.generate',
    'hrms.payroll.accounting.view',
    'hrms.salary_payment.view',
    'hrms.salary_payment.create',
    'hrms.loan.view',
    'hrms.loan.create',
    'hrms.exit.view',
    'hrms.exit.create',
    'hrms.exit.clearance',
    'hrms.fnf.view',
    'hrms.fnf.calculate',
    'organisation.view',
    'finance.legal_entity.view',
    'finance.branch.view',
    'department.view',
    'manufacturing.work_centre.view',
    'user.view',
  ],

  Viewer: [
    'crm.lead.view', 'crm.contact.view', 'crm.company.view',
    'crm.activity.view', 'crm.follow_up.view', 'crm.pipeline.view', 'crm.opportunity.view',
    'crm.quotation.view', 'crm.sales_order.view',
    'crm.dashboard.view', 'crm.report.view', 'crm.search.view',
    'crm.indiamart.view', 'crm.indiamart.enquiry.view',
    'user.view',
    ...MASTER_VIEW_PERMISSIONS,
    ...KB_USE_PERMISSIONS,
  ],

  /** Knowledge operators - full document lifecycle + chat without platform admin. */
  'Knowledge Manager': [...KB_ADMIN_PERMISSIONS],
}

/** Product / UI persona â€” same grants as Production Manager (includes manufacturing.bom.create). */
ROLE_PERMISSIONS['Production Head'] = [...ROLE_PERMISSIONS['Production Manager']]

/**
 * Legacy â†’ canonical purchase permission aliases.
 * Existing JWT / DB grants using old names still authorize the new route checks.
 */
export const PURCHASE_PERMISSION_ALIASES: Record<string, PermissionName> = {
  'purchase.requisition.view': 'purchase.pr.view',
  'purchase.requisition.create': 'purchase.pr.create',
  'purchase.requisition.edit': 'purchase.pr.edit',
  'purchase.requisition.submit': 'purchase.pr.submit',
  'purchase.requisition.approve': 'purchase.pr.approve',
  'purchase.requisition.revise': 'purchase.pr.revise',
  'purchase.quotation.view': 'purchase.rfq.view',
  'purchase.quotation.create': 'purchase.rfq.enter_quote',
  'purchase.quotation.compare': 'purchase.rfq.compare',
  'purchase.order.view': 'purchase.po.view',
  'purchase.order.create': 'purchase.po.create',
  'purchase.order.edit': 'purchase.po.edit',
  'purchase.order.approve': 'purchase.po.approve',
  'purchase.order.release': 'purchase.po.send',
  'purchase.order.cancel': 'purchase.po.cancel',
}

/** True if the permission set satisfies `required` (direct, alias, or tenant.manage). */
export function permissionSetIncludes(granted: readonly string[], required: string): boolean {
  if (granted.includes('tenant.manage') || granted.includes(required)) return true
  for (const g of granted) {
    const canonical = PURCHASE_PERMISSION_ALIASES[g]
    if (canonical === required) return true
  }
  const asCanonical = PURCHASE_PERMISSION_ALIASES[required]
  if (asCanonical && granted.includes(asCanonical)) return true
  return false
}

/** Canonical CRM opportunity pipeline â€” keep in sync with frontend opportunity-stages master / OPPORTUNITY_STAGES. */
export const DEFAULT_PIPELINE_STAGES = [
  { name: 'New Lead', slug: 'new_lead', sequence: 1, probability: 10 },
  { name: 'Qualified', slug: 'qualified', sequence: 2, probability: 20 },
  { name: 'Requirement Discussion', slug: 'requirement_discussion', sequence: 3, probability: 30 },
  { name: 'Technical Review', slug: 'technical_review', sequence: 4, probability: 40 },
  { name: 'Quotation Prepared', slug: 'quotation_prepared', sequence: 5, probability: 55 },
  { name: 'Quotation Sent', slug: 'quotation_sent', sequence: 6, probability: 65 },
  { name: 'Negotiation', slug: 'negotiation', sequence: 7, probability: 75 },
  { name: 'Won', slug: 'won', sequence: 8, probability: 100, isClosedWon: true },
  { name: 'Lost', slug: 'lost', sequence: 9, probability: 0, isClosedLost: true },
  { name: 'On Hold', slug: 'on_hold', sequence: 10, probability: 15 },
] as const
