-- Extend purchase status history document types for QI / Invoice / Return
ALTER TABLE `purchase_status_histories` MODIFY `documentType` ENUM(
  'PURCHASE_REQUISITION',
  'PURCHASE_REQUISITION_LINE',
  'PURCHASE_PLANNING_ROW',
  'REQUEST_FOR_QUOTATION',
  'VENDOR_QUOTATION',
  'VENDOR_COMPARISON',
  'PURCHASE_ORDER',
  'PURCHASE_APPROVAL',
  'GOODS_RECEIPT',
  'QUALITY_INSPECTION',
  'PURCHASE_INVOICE',
  'PURCHASE_RETURN'
) NOT NULL;