import type { VendorInvoiceValidationIssue } from './vendor-invoice-calculation.types.js'

export function calcError(code: string, message: string, field?: string): VendorInvoiceValidationIssue {
  return { code, message, field, severity: 'ERROR' }
}

export function calcWarning(code: string, message: string, field?: string): VendorInvoiceValidationIssue {
  return { code, message, field, severity: 'WARNING' }
}

export function calcInfo(code: string, message: string, field?: string): VendorInvoiceValidationIssue {
  return { code, message, field, severity: 'INFO' }
}

/** Error/warning/info codes emitted by the vendor invoice calculation engine. */
export const VENDOR_INVOICE_CALC_CODES = {
  VALIDATION_ERROR: 'VENDOR_INVOICE_VALIDATION_ERROR',

  QUANTITY_INVALID: 'VENDOR_INVOICE_QUANTITY_INVALID',
  UNIT_PRICE_INVALID: 'VENDOR_INVOICE_UNIT_PRICE_INVALID',
  LINE_DISCOUNT_INVALID: 'VENDOR_INVOICE_LINE_DISCOUNT_INVALID',
  TAX_RATE_INVALID: 'VENDOR_INVOICE_TAX_RATE_INVALID',
  CESS_RATE_INVALID: 'VENDOR_INVOICE_CESS_RATE_INVALID',
  EXPLICIT_RATE_SUPPLY_MISMATCH: 'VENDOR_INVOICE_EXPLICIT_RATE_SUPPLY_MISMATCH',
  HSN_SAC_INVALID: 'VENDOR_INVOICE_HSN_SAC_INVALID',
  HSN_SAC_LENGTH_WARNING: 'VENDOR_INVOICE_HSN_SAC_LENGTH_WARNING',

  COMPANY_STATE_REQUIRED: 'VENDOR_INVOICE_COMPANY_STATE_REQUIRED',
  PLACE_OF_SUPPLY_REQUIRED: 'VENDOR_INVOICE_PLACE_OF_SUPPLY_REQUIRED',
  SUPPLY_TYPE_MISMATCH: 'VENDOR_INVOICE_SUPPLY_TYPE_MISMATCH',

  HEADER_DISCOUNT_EXCEEDS_VALUE: 'VENDOR_INVOICE_HEADER_DISCOUNT_EXCEEDS_VALUE',
  HEADER_DISCOUNT_ALLOCATION_FAILED: 'VENDOR_INVOICE_HEADER_DISCOUNT_ALLOCATION_FAILED',

  INCLUSIVE_TAX_MISMATCH: 'VENDOR_INVOICE_INCLUSIVE_TAX_MISMATCH',
  CESS_ON_INCLUSIVE_EXCEEDS_PRICE: 'VENDOR_INVOICE_CESS_ON_INCLUSIVE_EXCEEDS_PRICE',

  FREIGHT_INVALID: 'VENDOR_INVOICE_FREIGHT_INVALID',
  OTHER_CHARGE_INVALID: 'VENDOR_INVOICE_OTHER_CHARGE_INVALID',

  INVALID_MANUAL_ROUND_OFF: 'VENDOR_INVOICE_INVALID_MANUAL_ROUND_OFF',
  ROUND_OFF_EXCEEDS_TOLERANCE: 'VENDOR_INVOICE_ROUND_OFF_EXCEEDS_TOLERANCE',
  NEGATIVE_TOTAL: 'VENDOR_INVOICE_NEGATIVE_TOTAL',
  TOTAL_CALCULATION_INVALID: 'VENDOR_INVOICE_TOTAL_CALCULATION_INVALID',

  ITC_ELIGIBLE_PERCENT_INVALID: 'VENDOR_INVOICE_ITC_ELIGIBLE_PERCENT_INVALID',
  ITC_PENDING_REVIEW: 'VENDOR_INVOICE_ITC_PENDING_REVIEW',

  TDS_RATE_INVALID: 'VENDOR_INVOICE_TDS_RATE_INVALID',
  TDS_BASE_INVALID: 'VENDOR_INVOICE_TDS_BASE_INVALID',
  TDS_EXCEEDS_GRAND_TOTAL: 'VENDOR_INVOICE_TDS_EXCEEDS_GRAND_TOTAL',
  TDS_AT_PAYMENT_NOTICE: 'VENDOR_INVOICE_TDS_AT_PAYMENT_NOTICE',

  BASE_CURRENCY_RATE_INVALID: 'VENDOR_INVOICE_BASE_CURRENCY_RATE_INVALID',
  EXCHANGE_RATE_INVALID: 'VENDOR_INVOICE_EXCHANGE_RATE_INVALID',

  REVERSE_CHARGE_TAX_EXCLUDED_FROM_PAYABLE: 'VENDOR_INVOICE_REVERSE_CHARGE_TAX_EXCLUDED_FROM_PAYABLE',

  DUPLICATE_SUPPLIER_INVOICE_BLOCKING: 'VENDOR_INVOICE_DUPLICATE_SUPPLIER_INVOICE_BLOCKING',
  DUPLICATE_SUPPLIER_INVOICE_SUSPECTED: 'VENDOR_INVOICE_DUPLICATE_SUPPLIER_INVOICE_SUSPECTED',

  ACCOUNT_NOT_CONFIGURED: 'VENDOR_INVOICE_ACCOUNT_NOT_CONFIGURED',
  ACCOUNT_NOT_FOUND: 'VENDOR_INVOICE_ACCOUNT_NOT_FOUND',
  ACCOUNT_IS_GROUP: 'VENDOR_INVOICE_ACCOUNT_IS_GROUP',
  ACCOUNT_INACTIVE: 'VENDOR_INVOICE_ACCOUNT_INACTIVE',
  ACCOUNT_READINESS_INCOMPLETE: 'VENDOR_INVOICE_ACCOUNT_READINESS_INCOMPLETE',

  ACCOUNTING_PREVIEW_UNBALANCED: 'VENDOR_INVOICE_ACCOUNTING_PREVIEW_UNBALANCED',
} as const

export type VendorInvoiceCalcCode = (typeof VENDOR_INVOICE_CALC_CODES)[keyof typeof VENDOR_INVOICE_CALC_CODES]
