-- HRMS Phase 9 — Payslip + Payroll Accounting + Salary Payment
-- Reuses Accounting post() engine, default mappings, Treasury, CodeSeries. No separate HR ledger.

ALTER TABLE `code_series` MODIFY COLUMN `entityType` ENUM(
  'USER','LEAD','CONTACT','CRM_COMPANY','OPPORTUNITY','QUOTATION','SALES_ORDER',
  'PRODUCTION_DEMAND','PRODUCTION_ORDER','DAILY_PRODUCTION_BATCH','PRODUCTION_ISSUE',
  'STOCK_MOVEMENT','STOCK_RESERVATION','PURCHASE_REQUISITION','PURCHASE_PLANNING',
  'REQUEST_FOR_QUOTATION','VENDOR_QUOTATION','VENDOR_COMPARISON','PURCHASE_ORDER',
  'GOODS_RECEIPT','QUALITY_INSPECTION','QUALITY_NCR','PURCHASE_INVOICE','PURCHASE_RETURN',
  'JOB_WORK_ORDER','PRODUCTION_RUNTIME_CHANGE','PRODUCTION_WIP_MOVEMENT','MANUFACTURING_CORRECTION',
  'PRODUCTION_PLAN','DEMAND_CONSOLIDATION_PLAN','OUTBOUND_DISPATCH','PRODUCTION_FG_RECEIPT',
  'DISPATCH_REQUIREMENT','DISPATCH_PICK_LIST','DISPATCH_PACKING_SESSION','DISPATCH_PACKAGE',
  'DELIVERY_CHALLAN','PURCHASE_QUALITY_INSPECTION','INVENTORY_TRANSFER','INVENTORY_STOCK_COUNT',
  'INVENTORY_ADJUSTMENT','MANUFACTURING_ROUTING','DISPATCH_POSTING','DISPATCH_REVERSAL',
  'MAINTENANCE_TICKET','PREVENTIVE_MAINTENANCE_PLAN','EMPLOYEE','PAYSLIP','SALARY_PAYMENT_BATCH'
) NOT NULL;

ALTER TABLE `default_account_mappings`
  MODIFY `mappingKey` ENUM(
    'CUSTOMER_RECEIVABLE',
    'VENDOR_PAYABLE',
    'SALES_REVENUE',
    'SALES_RETURN',
    'PURCHASE',
    'PURCHASE_RETURN',
    'RAW_MATERIAL_INVENTORY',
    'WIP_INVENTORY',
    'FINISHED_GOODS_INVENTORY',
    'STOCK_ADJUSTMENT',
    'MATERIAL_CONSUMPTION',
    'GRIR_CLEARING',
    'PURCHASE_PRICE_VARIANCE',
    'COST_OF_GOODS_SOLD',
    'LABOUR_ABSORPTION',
    'MACHINE_ABSORPTION',
    'JOB_WORK_ABSORPTION',
    'PRODUCTION_OVERHEAD_ABSORPTION',
    'PRODUCTION_VARIANCE',
    'SCRAP_INVENTORY',
    'SCRAP_LOSS',
    'SUBCONTRACTING_EXPENSE',
    'FREIGHT_INWARD',
    'FREIGHT_OUTWARD',
    'GST_INPUT_CGST',
    'GST_INPUT_SGST',
    'GST_INPUT_IGST',
    'GST_OUTPUT_CGST',
    'GST_OUTPUT_SGST',
    'GST_OUTPUT_IGST',
    'GST_OUTPUT_CESS',
    'TDS_RECEIVABLE',
    'TDS_PAYABLE',
    'BANK_CHARGES',
    'ROUNDING',
    'DEPRECIATION_EXPENSE',
    'ACCUMULATED_DEPRECIATION',
    'ASSET_DISPOSAL_GAIN',
    'ASSET_DISPOSAL_LOSS',
    'FIXED_ASSET_CLEARING',
    'ASSET_REVALUATION_SURPLUS',
    'ASSET_IMPAIRMENT_LOSS',
    'RETAINED_EARNINGS',
    'INTERNAL_TRANSFER_CLEARING',
    'CHEQUE_RECEIPT_CLEARING',
    'CHEQUE_PAYMENT_CLEARING',
    'BANK_INTEREST_INCOME',
    'BANK_INTEREST_EXPENSE',
    'COLLECTION_FEE_EXPENSE',
    'MERCHANT_FEE_EXPENSE',
    'ACCRUED_EXPENSE_LIABILITY',
    'PREPAID_EXPENSE_ASSET',
    'UNREALIZED_FX_GAIN',
    'UNREALIZED_FX_LOSS',
    'SALARY_BASIC_EXPENSE',
    'SALARY_HRA_EXPENSE',
    'SALARY_ALLOWANCE_EXPENSE',
    'SALARY_OT_EXPENSE',
    'SALARY_PAYABLE',
    'PF_EMPLOYEE_PAYABLE',
    'PF_EMPLOYER_PAYABLE',
    'PF_EMPLOYER_EXPENSE',
    'ESIC_EMPLOYEE_PAYABLE',
    'ESIC_EMPLOYER_PAYABLE',
    'ESIC_EMPLOYER_EXPENSE',
    'PT_PAYABLE',
    'TDS_SALARY_PAYABLE',
    'LWF_PAYABLE',
    'LWF_EMPLOYER_PAYABLE',
    'LWF_EMPLOYER_EXPENSE'
  ) NOT NULL;

ALTER TABLE `hr_payroll_runs`
  ADD COLUMN `accountingStatus` ENUM('NOT_POSTED','POSTED','FAILED') NOT NULL DEFAULT 'NOT_POSTED',
  ADD COLUMN `accountingVoucherId` VARCHAR(191) NULL,
  ADD COLUMN `postingEventId` VARCHAR(191) NULL,
  ADD COLUMN `accountingPostedAt` DATETIME(3) NULL,
  ADD COLUMN `accountingPostedByUserId` VARCHAR(191) NULL,
  ADD COLUMN `accountingError` VARCHAR(500) NULL,
  ADD COLUMN `payslipGeneratedAt` DATETIME(3) NULL,
  ADD COLUMN `paymentStatus` ENUM('NOT_STARTED','IN_PROGRESS','PARTIALLY_PAID','PAID') NOT NULL DEFAULT 'NOT_STARTED';

CREATE INDEX `hr_payroll_runs_tenantId_accountingStatus_idx`
  ON `hr_payroll_runs` (`tenantId`, `accountingStatus`);

CREATE TABLE `hr_payslips` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `payrollRunId` VARCHAR(191) NOT NULL,
  `payrollEmployeeResultId` VARCHAR(191) NOT NULL,
  `employeeId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `payslipNumber` VARCHAR(32) NOT NULL,
  `year` INTEGER NOT NULL,
  `month` INTEGER NOT NULL,
  `snapshotJson` LONGTEXT NOT NULL,
  `grossAmount` DECIMAL(14, 2) NOT NULL,
  `deductionAmount` DECIMAL(14, 2) NOT NULL,
  `employerAmount` DECIMAL(14, 2) NOT NULL,
  `netAmount` DECIMAL(14, 2) NOT NULL,
  `status` ENUM('GENERATED','VOID') NOT NULL DEFAULT 'GENERATED',
  `paymentStatus` ENUM('UNPAID','PARTIAL','PAID','FAILED') NOT NULL DEFAULT 'UNPAID',
  `generatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `generatedByUserId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_payslips_payrollEmployeeResultId_key` (`payrollEmployeeResultId`),
  UNIQUE INDEX `hr_payslips_tenantId_payslipNumber_key` (`tenantId`, `payslipNumber`),
  INDEX `hr_payslips_tenantId_idx` (`tenantId`),
  INDEX `hr_payslips_tenantId_payrollRunId_idx` (`tenantId`, `payrollRunId`),
  INDEX `hr_payslips_tenantId_employeeId_idx` (`tenantId`, `employeeId`),
  INDEX `hr_payslips_tenantId_year_month_idx` (`tenantId`, `year`, `month`),
  INDEX `hr_payslips_tenantId_paymentStatus_idx` (`tenantId`, `paymentStatus`),
  CONSTRAINT `hr_payslips_tenantId_fkey`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_payslips_payrollRunId_fkey`
    FOREIGN KEY (`payrollRunId`) REFERENCES `hr_payroll_runs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_payslips_payrollEmployeeResultId_fkey`
    FOREIGN KEY (`payrollEmployeeResultId`) REFERENCES `hr_payroll_employee_results` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_payslips_employeeId_fkey`
    FOREIGN KEY (`employeeId`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_payslips_legalEntityId_fkey`
    FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_salary_payment_batches` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `payrollRunId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `branchId` VARCHAR(191) NULL,
  `code` VARCHAR(32) NOT NULL,
  `treasuryAccountId` VARCHAR(191) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `employeeCount` INTEGER NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(16, 2) NOT NULL DEFAULT 0,
  `paidAmount` DECIMAL(16, 2) NOT NULL DEFAULT 0,
  `pendingAmount` DECIMAL(16, 2) NOT NULL DEFAULT 0,
  `failedCount` INTEGER NOT NULL DEFAULT 0,
  `status` ENUM('DRAFT','READY','APPROVED','PAID','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `reference` VARCHAR(120) NULL,
  `accountingVoucherId` VARCHAR(191) NULL,
  `postingEventId` VARCHAR(191) NULL,
  `accountingPostedAt` DATETIME(3) NULL,
  `approvedAt` DATETIME(3) NULL,
  `approvedByUserId` VARCHAR(191) NULL,
  `paidAt` DATETIME(3) NULL,
  `paidByUserId` VARCHAR(191) NULL,
  `createdBy` VARCHAR(191) NULL,
  `updatedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_salary_payment_batches_tenantId_code_key` (`tenantId`, `code`),
  INDEX `hr_salary_payment_batches_tenantId_idx` (`tenantId`),
  INDEX `hr_salary_payment_batches_tenantId_payrollRunId_idx` (`tenantId`, `payrollRunId`),
  INDEX `hr_salary_payment_batches_tenantId_legalEntityId_idx` (`tenantId`, `legalEntityId`),
  INDEX `hr_salary_payment_batches_tenantId_status_idx` (`tenantId`, `status`),
  INDEX `hr_salary_payment_batches_tenantId_deletedAt_idx` (`tenantId`, `deletedAt`),
  CONSTRAINT `hr_salary_payment_batches_tenantId_fkey`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_salary_payment_batches_payrollRunId_fkey`
    FOREIGN KEY (`payrollRunId`) REFERENCES `hr_payroll_runs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_salary_payment_batches_legalEntityId_fkey`
    FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_salary_payment_batches_branchId_fkey`
    FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `hr_salary_payment_lines` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `batchId` VARCHAR(191) NOT NULL,
  `employeeId` VARCHAR(191) NOT NULL,
  `payslipId` VARCHAR(191) NOT NULL,
  `netPay` DECIMAL(14, 2) NOT NULL,
  `bankName` VARCHAR(150) NULL,
  `accountHolderName` VARCHAR(150) NULL,
  `accountNumberMasked` VARCHAR(34) NULL,
  `accountNumber` VARCHAR(34) NULL,
  `ifsc` VARCHAR(11) NULL,
  `paymentStatus` ENUM('PENDING','READY','PAID','FAILED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  `paymentReference` VARCHAR(120) NULL,
  `failureReason` VARCHAR(500) NULL,
  `paidAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hr_salary_payment_lines_batchId_employeeId_key` (`batchId`, `employeeId`),
  UNIQUE INDEX `hr_salary_payment_lines_payslipId_batchId_key` (`payslipId`, `batchId`),
  INDEX `hr_salary_payment_lines_tenantId_idx` (`tenantId`),
  INDEX `hr_salary_payment_lines_tenantId_batchId_idx` (`tenantId`, `batchId`),
  INDEX `hr_salary_payment_lines_tenantId_employeeId_idx` (`tenantId`, `employeeId`),
  INDEX `hr_salary_payment_lines_tenantId_payslipId_idx` (`tenantId`, `payslipId`),
  INDEX `hr_salary_payment_lines_tenantId_paymentStatus_idx` (`tenantId`, `paymentStatus`),
  CONSTRAINT `hr_salary_payment_lines_tenantId_fkey`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `hr_salary_payment_lines_batchId_fkey`
    FOREIGN KEY (`batchId`) REFERENCES `hr_salary_payment_batches` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_salary_payment_lines_employeeId_fkey`
    FOREIGN KEY (`employeeId`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `hr_salary_payment_lines_payslipId_fkey`
    FOREIGN KEY (`payslipId`) REFERENCES `hr_payslips` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
