-- Phase 8 — GST payment / PMT-06 style challan register (books-side)

CREATE TABLE IF NOT EXISTS `gst_payment_challans` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `legalEntityId` VARCHAR(191) NOT NULL,
  `companyGstin` VARCHAR(20) NOT NULL,
  `returnPeriod` VARCHAR(7) NOT NULL,
  `status` ENUM(
    'DRAFT',
    'PROPOSED',
    'CONFIRMED_EXTERNAL',
    'POSTED_GL',
    'CLOSED',
    'VOID'
  ) NOT NULL DEFAULT 'DRAFT',
  `outputCgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `outputSgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `outputIgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `outputCess` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `rcmCgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `rcmSgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `rcmIgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `rcmCess` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `itcCgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `itcSgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `itcIgst` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `itcCess` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalLiability` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalItc` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `netTaxPayable` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `interestAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `lateFeeAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `roundOffAmount` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `totalPayable` DECIMAL(18, 4) NOT NULL DEFAULT 0,
  `cashLedgerJson` JSON NULL,
  `creditLedgerJson` JSON NULL,
  `liabilitySnapshotJson` JSON NULL,
  `cpin` VARCHAR(64) NULL,
  `challanNumber` VARCHAR(64) NULL,
  `bankReference` VARCHAR(128) NULL,
  `paymentDate` DATE NULL,
  `bankAccountId` VARCHAR(191) NULL,
  `remarks` VARCHAR(1000) NULL,
  `accountingVoucherId` VARCHAR(191) NULL,
  `postingEventId` VARCHAR(191) NULL,
  `proposedAt` DATETIME(3) NULL,
  `proposedBy` VARCHAR(191) NULL,
  `confirmedAt` DATETIME(3) NULL,
  `confirmedBy` VARCHAR(191) NULL,
  `postedAt` DATETIME(3) NULL,
  `postedBy` VARCHAR(191) NULL,
  `closedAt` DATETIME(3) NULL,
  `closedBy` VARCHAR(191) NULL,
  `voidedAt` DATETIME(3) NULL,
  `voidedBy` VARCHAR(191) NULL,
  `voidReason` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gst_pay_le_period_idx`(`tenantId`, `legalEntityId`, `returnPeriod`),
  INDEX `gst_pay_status_idx`(`tenantId`, `status`),
  INDEX `gst_pay_gstin_period_idx`(`tenantId`, `companyGstin`, `returnPeriod`),
  CONSTRAINT `gst_payment_challans_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `gst_payment_challans_legalEntityId_fkey` FOREIGN KEY (`legalEntityId`) REFERENCES `legal_entities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
