/** Quality depth is generated by production + GRN flows; no additional orphan NCRs */
export function seedDemoQuality(): void {
  /* QC inspections, NCRs, and reworks are created via demoBulkSeed store APIs */
}
