/** Saturation targets and realistic trailer-manufacturing reference data */

export const SATURATION_TARGETS = {
  customers: 30,
  customerContacts: 60,
  vendors: 30,
  items: 120,
  products: 25,
  boms: 25,
  routings: 25,
  workCenters: 20,
  warehouses: 12,
  leads: 50,
  opportunities: 30,
  quotations: 30,
  salesOrders: 30,
  mrpRuns: 20,
  purchaseRequisitions: 30,
  rfqs: 25,
  purchaseOrders: 30,
  grns: 30,
  inventoryMovements: 150,
  workOrders: 30,
  jobCards: 80,
  jobWorkOrders: 25,
  qcInspections: 40,
  ncrs: 25,
  reworks: 25,
  dispatches: 30,
  invoices: 30,
  payments: 25,
  ecrs: 25,
  ecos: 25,
  approvalRequests: 30,
  qrCodes: 80,
  barcodes: 50,
  serialNumbers: 80,
  documents: 100,
} as const

export const DEMO_CUSTOMER_NAMES = [
  'ABC Cement',
  'UltraBuild Logistics',
  'Shree Cement Transport',
  'Patel Bulk Carriers',
  'Metro Infra Logistics',
  'National Bulk Movers',
  'Western Cement Carriers',
  'Ambuja Logistics',
  'Sunrise Minerals',
  'Raj Transport',
  'Bharat Cement Carriers',
  'Apex Bulk Movers',
  'Maruti Infra Logistics',
  'Narmada Cement Logistics',
  'Supreme Tanker Services',
  'Galaxy Minerals',
  'Prime Cargo Movers',
  'Shakti Transport Co',
  'Unity Cement Logistics',
  'Dev Bulk Carriers',
  'R.K. Laxmi Logistics',
  'Om Sai Roadways',
  'Delta Minerals',
  'Krishna Bulk Movers',
  'BlueLine Logistics',
  'Ashapura Cement Movers',
  'Jalaram Transport',
  'Rapid Freight Bulk',
  'Mehta Industrial Carriers',
  'Zenith Bulk Solutions',
] as const

export const DEMO_VENDOR_NAMES = [
  'JOST India',
  'WABCO',
  'BPW',
  'York Transport Equipment',
  'Bharat Paints',
  'Local Steel Supplier',
  'Precision Axle Works',
  'Industrial Tyres Co',
  'Pneumatic Components Co',
  'Hydraulic Systems India',
  'Heavy Fabrication Works',
  'Sand Blasting Services',
  'PaintPro Coaters',
  'Fastener House',
  'Bearing Traders',
  'Electrical Harness India',
  'Compressor Supply Co',
  'ValveTech Industries',
  'Sheet Metal Works',
  'Rubber Seal Suppliers',
  'Welding Consumables Co',
  'Trailer Lights India',
  'Brake Systems Co',
  'Industrial Gas Supplier',
  'CNC Machining Works',
  'Surface Finish Vendors',
  'Steel Coil Traders',
  'Fabrication Outsource Hub',
  'Transport Spare Parts Co',
  'Allied Hardware Mart',
] as const

export const DEMO_PRODUCT_NAMES = [
  '45 M3 Bulker Trailer',
  '26 KL ISO Tank',
  '32 FT Side Wall Trailer',
  'Cement Bulker',
  'Fly Ash Bulker',
  'Pneumatic Bulker',
  'Stainless Steel Tanker',
  'Tipping Trailer',
  'Low Bed Trailer',
  'Flat Bed Trailer',
  'Bitumen Tanker',
  'Chemical Tanker',
  'Fuel Tanker',
  'Container Trailer',
  'Hydraulic Tipper',
  'Ash Handling Trailer',
  'Food Grade Tanker',
  'Heavy Duty Cargo Trailer',
  'Road Tanker',
  'Custom Industrial Trailer',
  '35 M3 Bulker',
  '40 M3 Bulker',
  '50 M3 Bulker',
  '20 KL Tanker',
  '30 KL Tanker',
] as const

export const SO_STATUS_DISTRIBUTION: Array<{ status: string; count: number }> = [
  { status: 'open', count: 3 },
  { status: 'confirmed', count: 9 },
  { status: 'in_production', count: 10 },
  { status: 'ready_dispatch', count: 3 },
  { status: 'dispatched', count: 2 },
  { status: 'invoiced', count: 2 },
  { status: 'closed', count: 1 },
]
